### ISSUE TITLE
New basic_xxxx keyboards are missing language examples

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1006]
When we deprecated the older KeymanWeb keyboards, e.g. replacing [albanian](https://github.com/keymanapp/keyboards/blob/master/legacy/a/albanian/albanian.keyboard_info) with [basic_kbdal](https://github.com/keymanapp/keyboards/blob/master/release/basic/basic_kbdal/basic_kbdal.keyboard_info), we didn't copy across the language example data. These examples can normally be seen on keymanweb.com, for example, at [keymanweb.com](https://keymanweb.com/#fa,Keyboard_dari_clra).

The examples took quite a lot of work to produce and have been valuable as a way of 'getting started' with a keyboard.

**Comment by DavidLRowe** [comment]
Sounds like a job for a script:
For each release/basic/basic_xxx keyboard that has no language example:
- check for one or more deprecated keyboards: legacy/x/xyz
- check for language example in legacy/x/xyz/xyz.keyboard_info

But whoever takes this on (whether manually or via script) should alert everyone else via the Keyman Slack channel, so we don't duplicate effort.

**Comment by LornaSIL** [comment]
Some of these also have fonts set up in keyboard_info. Since they are Windows keyboards I don't feel a huge need to include fonts. What do you think?
Example:
```
  "languages": {
    "sr": {
      "font": {
        "family": "LatinWeb",
        "source": [
          "DejaVuSans.ttf",
          "DejaVuSans.mobileconfig"
        ]
      }
    }
  },
```
Notice the language code is wrong (should be sr-Latn) so I don't want us just copying the whole thing over, we need to maintain the language codes since I spent a lot of time making those more accurate :(

**Comment by mcdurdin** [comment]
@DavidLRowe:
> Sounds like a job for a script:

Definitely. I can probably put something together pretty quickly (the exceptions where language code has changed etc will take a little longer!).

@LornaSIL:
> Since they are Windows keyboards I don't feel a huge need to include fonts.

The reason the font was included was for downlevel versions of Windows which did not support the script / keyboard, as well as cross-platform environments. In some cases this is probably not important (especially for well-supported languages) but there would be a huge amount of testing to validate font requirements across all our supported environments. So I would encourage inclusion of fonts for these keyboards unless we are very confident that the language is supported OOTB for all supported devices.
