### ISSUE TITLE
[sil_cameroon_qwerty] Issues within KeymanWeb

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#1138]
The first issue I noticed will also affect Keyman for Android and Keyman for iOS:  the shift-layer's question mark key provides no output.  I've tested this as far back as KMW 10.0, so this issue isn't due to any recent changes in the keyboard engine.

---

A second issue affects only desktop form-factor KMW:

<img width="569" alt="Screen Shot 2020-03-31 at 1 04 52 PM" src="https://user-images.githubusercontent.com/25213402/77992438-4034c700-7350-11ea-8f8c-35aa7ce8a76f.png">

Simply load the keyboard in KMW and view the OSK - this is what will be displayed.

The "CM" key, which has replaced the standard semi-colon here, does nothing.  No layer changes, no output of any kind.

**Comment by DavidLRowe** [comment]
(1) The ? key on the shift layer invokes T_003F
```
                "id": "T_003F",
                "text": "?",
                "nextlayer": "default"
```
but because no layer information is given, "shift" is passed, that is [SHIFT T_003F]. Since the .kmn file has:
```
+ [T_003F] > U+003F
```
there is no match and no output, and the user is returned to the default layer. 

The solution would be to explicitly designate the "default" layer for this key:
```
                "id": "T_003F",
                "text": "?",
                "nextlayer": "default",
                "layer": "default"
```

(2) The "CM" key is a dead key.
```
+ [NCAPS K_COLON] >  dk(003b)
+ [CAPS K_COLON] >  dk(003b)
```
For example, type ;o to get ɔ, type ; then space to get ;. Is this what you see?

**Comment by DavidLRowe** [comment]
@MattGyverLee If you agree with my fix for (1), I'd be willing to make that change.

**Comment by MattGyverLee** [comment]
1) @DavidLRowe I agree with the fix on the question mark. You can do that. I didn't think layer affected T_ keys.
2) @jahorton  Yes, it is currently acting as a dead key in KMW. I would **LOVE** to get a layer change in KMW to RALT (or SHIFT-RALT) upon pressing the CAM key on both keyboards! That would more closely match the touch keyboard. I didn't think that was possible. How in the world can I make the KMW CAM key act like RALT?

**Comment by jahorton** [comment]
I do see that behavior for the CAM key.  Not knowing the keyboard intimately, I found use of the special touch key on the desktop OSK odd, but knowing it has a purpose like that now, it's fine.

@MattGyverLee As of KMW, we now support chiral keyboards; you can actually test directly against RALT now in web keyboards and make that its own layer for desktop form factors.  One example would be https://keymanweb.com/#km,Keyboard_khmer_angkor - note how LALT is a different layer from RALT.

You'll probably still want the CAM key on touch, of course.

**Comment by DavidLRowe** [comment]
@MattGyverLee Hopefully #1145 will address (1) above. Is any action needed for (2)? If not, this issue can be closed when the fix for (1) is merged.

**Comment by MattGyverLee** [comment]
@jahorton Chirality already worked on OSK. I just discovered that I can change layers in OSK (even though it gunks up my code a bit), and this is brilliant! I'm rewriting my code and css now to make the OSK better mirror the mobile experience with appropriate layer changes. 
@DavidLRowe You can close https://github.com/keymanapp/keyboards/pull/1145, and I'll open new ones after I rewrite my code and increment the version for both KB's.
My new PR should close this issue.

**Comment by MattGyverLee** [comment]
Question mark closed in https://github.com/keymanapp/keyboards/pull/1394. I'll try to do the layer-switching in OSK on a later release. This issue can be closed.
