### ISSUE TITLE
grkpoly2: Greek Polytonic Unicode keyboard has incorrect example keys

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#116]
https://keymanweb.com/#grc,Keyboard_grkpoly2 shows incorrect example keystroke + text. The text appears to be related to another Greek keyboard.

**Comment by DavidLRowe** [comment]
@mcdurdin Is this still an issue? I'm having trouble finding the keyboard in question.

**Comment by mcdurdin** [comment]
Yes, it looks like this related to the old keyboard data on the Tavultesoft site. I don't think we need to worry about it for now. @LornaSIL not sure if you want to open a new issue on the Coptic default language problem.

**Comment by DavidLRowe** [comment]
@LornaSIL Should `grkpoly2.keyboard_info` be changed to list only `el`? or list it before `cop`?

**Comment by LornaSIL** [comment]
Well, I've realized that the Coptic language can be written with the Greek or the Coptic script. So, it's not out of line to list the keyboard as supporting the Coptic language. However, I would definitely think ```el``` would be the primary language it is intended to support.

**Comment by DavidLRowe** [comment]
So is it as simple as swapping "cop" and "el"? or do they need script tags added: "el-Grek" and "cop-Grek"?

**Comment by LornaSIL** [comment]
I would think el does not need a script tag, but cop does.
