### ISSUE TITLE
Add documentation on how to configure WINE for macOS into root README.md

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1188]
Documentation is here: https://help.keyman.com/knowledge-base/95

**Comment by DavidLRowe** [comment]
@mcdurdin Is someone on your team planning to do this? If I were to take it on, I'd need some more details. Is this to enable a macOS user to run Developer?

**Comment by mcdurdin** [comment]
This is to enable a macOS user to run Developer, yes.

**Comment by mcdurdin** [comment]
At this stage, I don't have the capacity to take this on -- perhaps @jahorton could but not sure he has the capacity at present either.

**Comment by jahorton** [comment]
Nor do I; also doesn't help that I'm extremely inexperienced with WINE.

**Comment by LornaSIL** [comment]
@ermshiperete @jahorton @mcdurdin Is there anybody on the team who can do this? Or has it been done and we can close this issue?

**Comment by mcdurdin** [comment]
There's a link to the KB article in the root README.md. Given we will be moving away from needing WINE before too long with @SabineSIL's [work on kmcompx](https://github.com/keymanapp/keyman/pull/6980) (although that's not the only thing we need to complete, it's the major component), let's just go ahead and close this.
