### ISSUE TITLE
Several keyboards don't show their html pages on Linux

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyboards#1237]
Several keyboards don't show their help pages, readme, options etc because they use a flavour of html that the browser component that is used on Linux doesn't support.

## How to fix

This can be fixed by changing the top of the html file to:

```html
<!DOCTYPE html>
<html lang="en">
```

or simply

``` html
<html>
```

and/or saving as UTF-8.

## Affected keyboards

The affected keyboards are:

  - [x] balochi_inpage (readme.htm)
  - [x] balochi_phonetic (readme.htm)
  - [x] balochi_scientific (readme.htm)
  - [x] balochi_urdu (readme.htm)
  - [x] ekwtamil99uni (readme.htm)
  - [x] embera_north (readme.htm, welcome.htm)
  - [ ] fv_denesuline_epsilon (fv_denesuline_epsilon_kmw_help.htm, welcome.htm)
  - [ ] fv_diitiidatx (fv_diitiidatx_kmw_help.htm, welcome.htm)
  - [ ] fv_gitsenimx (fv_gitsenimx_kmw_help.htm, welcome.htm)
  - [ ] fv_halqemeylem (fv_halqemeylem_kmw_help.htm, welcome.htm)
  - [ ] fv_dakelh (fv_dakelh_kmw_help.htm, welcome.htm)
  - [ ] fv_henqeminem (fv_henqeminem_kmw_help.htm, welcome.htm)
  - [ ] fv_kanienkeha_e (fv_kanienkeha_e_kmw_help.htm, welcome.htm)
  - [ ] fv_ktunaxa (welcome.htm)
  - [ ] fv_kwakwala (fv_kwakwala_kmw_help.htm, welcome.htm)
  - [x] fv_kwakwala_liqwala (fv_kwakwala_liqwala_kmw_help.htm, welcome.htm)
  - [ ] fv_migmaq (fv_migmaq_kmw_help.htm, welcome.htm)
  - [ ] fv_natwits (welcome.htm)
  - [ ] fv_nisgaa (fv_nisgaa_kmw_help.htm, welcome.htm)
  - [ ] fv_nlekepmxcin (fv_nlekepmxcin_kmw_help.htm, welcome.htm)
  - [ ] fv_nsilxcen (fv_nsilxcen_kmw_help.htm, welcome.htm)
  - [ ] fv_nuucaanul (fv_nuucaanul_kmw_help.htm, welcome.htm)
  - [ ] fv_secwepemctsin (fv_secwepemctsin_kmw_help.htm, welcome.htm)
  - [ ] fv_sencoten (fv_sencoten_kmw_help.htm, welcome.htm)
  - [ ] fv_shashishalhem (fv_shashishalhem_kmw_help.htm, welcome.htm)
  - [ ] fv_smalgyax (fv_smalgyax_kmw_help.htm, welcome.htm)
  - [ ] fv_statimcets (welcome.htm)
  - [ ] fv_stlatlimxec (fv_stlatlimxec_help.htm, welcome.htm)
  - [ ] fv_taltan (fv_taltan_help.htm, welcome.htm)
  - [ ] fv_tsekehne (fv_tsekehne_help.htm, welcome.htm)
  - [ ] fv_tsilhqotin (fv_tsilhqotin_help.htm, welcome.htm)
  - [x] fv_uwikala (fv_uwikala_help.htm, welcome.htm)
  - [x] fv_xaislakala (fv_xaislakala.htm, welcome.htm)
  - [x] gff_blin (welcome.htm)
  - [x] gff_amharic (welcome.htm)
  - [x] gff_geez (welcome.htm)
  - [x] gff_gurage (welcome.htm)
  - [x] gff_gurage_and_amharic (gff_amharic_welcome.htm, gff_gurage_welcome.htm)
  - [x] gff_tigrinya_eritrea (welcome.htm)
  - [x] gff_tigrinya_ethiopia (welcome.htm)
  - [x] ghana (readme.htm [utf-16le])
  - [x] jawa (readme.html, welcome2.htm [binary])
  - [x] jorai (readme.htm [utf-16le])
  - [x] landuma (readme.htm, welcome.htm)
  - [x] libtralo (readme.htm [utf-16le])
  - [x] mozhi_malayalam (readme.htm)
  - [x] nw_iranian_latin (readme.htm [utf-16le])
  - [x] osage_nation (readme.htm [utf-16le])
  - [x] persian_phonetic (readme.htm [utf-16le])
  - [x] rac_aer (readme.htm [utf-16le])
  - [x] rac_brahui_latin (readme.htm [utf-16le], welcome.htm [utf-16le])
  - [x] rac_dogri (readme.htm [utf-16le])
  - [x] rac_gawar_bati (readme.htm [utf-16le])
  - [x] rac_hazaragi (readme.htm [utf-16le], welcome.htm [utf-16le])
  - [x] rac_kalasha (readme.htm [utf-16le])
  - [x] rac_urdu (readme.htm [utf-16le])
  - [x] rohingya_arab (readme.htm [utf-16le])
  - [x] shan (welcome.htm)
  - [x] sil_areare (readme.htm [utf-16le])
  - [x] sil_busa (readme.htm [utf-16le])
  - [x] sil_cameroon_azerty (readme.htm, welcome.htm)
  - [x] sil_cameroon_qwerty (welcome.htm)
  - [x] sil_cherokee_nation (readme.htm [utf-16le])
  - [x] sil_cheyenne (welcome.htm)
  - [x] sil_cipher_music (options.htm)
  - [x] sil_ethiopic (welcome.htm)
  - [x] sil_ethiopic_power_g (welcome.htm)
  - [x] sil_euro_latin (options.htm, readme.htm, usage.htm, welcome.htm)
  - [x] sil_hebrew (readme.htm)
  - [x] sil_ipa (options.htm)
  - [x] sil_nubian (readme.htm [utf-16le])
  - [x] sil_tai_dam (welcome.htm)
  - [x] sil_tai_dam_lao (welcome.htm)
  - [x] sil_tai_dam_latin (welcome.htm)
  - [x] sil_torwali (readme.htm [utf-16le])
  - [x] sil_yupik_cyrillic (welcome.htm)
  - [x] tainua (welcome.htm)
  - [x] xinaliq (readme.htm [utf-16le])
  - [x] yidgha (readme.htm [utf-16le])

## Background

It seems that the WebKit2 component that `km-config` uses doesn't support XHTML nor UTF-16.

The list of affected keyboards can be generated with [this](https://github.com/ermshiperete/km-show-pages) tool.

**Comment by LornaSIL** [comment]
@ermshiperete Is this a major issue that needs fixing right away or can we just chip away at it?

**Comment by DavidLRowe** [comment]
And let's make sure that what we end up with works for Windows and Mac! It seems that we need some sort of UTF-8 declaration for Windows if the text contains non-ASCII characters (whereas I think UTF-8 is the default for Linux).

**Comment by DavidLRowe** [comment]
@ermshiperete I'm confused. The readme.htm file in release/x/xinaliq keyboard starts:
```
<!DOCTYPE html>
<html lang="en">
```
which is what you suggest using, yet it shows up in your list of keyboards with problems. 

And the welcome.htm file for that keyboard seems to have the same structure as the readme.htm, yet it is not in your list.

**Comment by ermshiperete** [comment]
> @ermshiperete Is this a major issue that needs fixing right away or can we just chip away at it?

I think chip away should be fine. The Linux users won't know that they are missing something unless they compare what they get on Windows with what they get on Linux (which is how I discovered this problem - I had assumed that the keyboards simply didn't have any help and so that's why it showed up as empty window).

**Comment by ermshiperete** [comment]
@DavidLRowe yes, it's strange. I'm confused as well. When turning on debugging I can see that loading `readme.htm` gives the error "Frame load interrupted". But why? I'll keep investigating...

**Comment by ermshiperete** [comment]
Found it. `readme.htm` is saved as UTF-16LE instead of UTF-8.

**Comment by DavidLRowe** [comment]
@ermshiperete So, is it sufficient just to save the file as UTF-8? Or is some change to the content of the file needed as well?

**Comment by LornaSIL** [comment]
I've discussed this with others and we should save the file as UTF-8...but without the BOM.

**Comment by dyacob** [comment]
So what you are suggesting @LornaSIL is that we:  "Drop the BOM!".  

...couldn't resist 😁

**Comment by ermshiperete** [comment]
I enhanced the list above so that it now shows the files that have a wrong encoding.

**Comment by DavidLRowe** [comment]
One further note: GitHub seems to flag non-UTF-8 files as "BIN", based on looking at release/x/xinaliq where readme.htm is not UTF-8 and welcome.htm is.
![image](https://user-images.githubusercontent.com/8562172/83695506-06ca4300-a5af-11ea-98d0-c22a49c9871c.png)

**Comment by LornaSIL** [comment]
@madebybridget I would like for us to fix these htm files before we forget what needs to happen. Would you mind if I go ahead and finish the `fv_` ones? This requires updating the htm files, but also requires a bump to the version number of the keyboard. I wouldn't try to make changes to the keyboards themselves.

Doing this will allow the documentation for the keyboards to be working on Linux.

**Comment by madebybridget** [comment]
Hi @LornaSIL, apologies for the delay in response, I just found out that GitHub messages were being shunned into my spam folder so I'm catching up on missed messages. Please do feel free to finish the fv_ ones, I would appreciate that. Please let me know if there's anything needed on our end!
