### ISSUE TITLE
[gff_amharic] Broken links to "Complete Typing Chart" pdf's.

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1239]
I noticed in the online help
https://help.keyman.com/keyboard/gff_amharic/1.9.1/gff_amharic

the links to the pdf are broken.

#### Keyboard Details
* Complete Typing Chart - English
* Complete Typing Chart - Amharic

I wonder if the pdf's need to be copied into the help/ folder so they get syncd to the help.keyman.com site.

**Comment by DavidLRowe** [comment]
fixed by #1241
