### ISSUE TITLE
Issue with Kᵂak̓ᵂala FV keyboard

### ISSUE THREAD

**Issue by madebybridget** [keymanapp/keyboards#1246]
Hi folks, the Kᵂak̓ᵂala FV keyboard has recently changed and no longer functions in the way that it should. A user shared her screenshots from two devices she has with the keyboard: one with the old layout and one with the new. The first screenshots attached below on the iPad are of the old, proper layout, versus the second set of screenshots on the iPhone are of the new, non-functional layout. It seems like all of the special characters got moved to the number keys, where when you hold down the numbers they type special characters but don't visibly show up as a long-press option.

Please let me know how we can revert these changes back to an older build of the keyboard with the appropriate layout. Thanks so much!

![image3](https://user-images.githubusercontent.com/58344928/83929520-7d4e7880-a748-11ea-9b82-31ad95271115.png)
![image2](https://user-images.githubusercontent.com/58344928/83929530-850e1d00-a748-11ea-8898-e555c7502bc1.png)
![image4](https://user-images.githubusercontent.com/58344928/83929538-8b9c9480-a748-11ea-9163-7d377ff060ef.png)
![image5](https://user-images.githubusercontent.com/58344928/83929542-8d665800-a748-11ea-9097-505dcae30c1f.png)

**Comment by DavidLRowe** [comment]
Are we talking about the release/fv/fv_kwakwala keyboard (in the GitHub repository at: https://github.com/keymanapp/keyboards/tree/master/release/fv/fv_kwakwala). The last change to this keyboard was 18 Oct 2018. At that point three legacy keyboards were deprecated: legacy/k/kwakiutl, legacy/k/kwakwala_u, legacy/u/uwikala_u</del>

Or is this the release/fv/fv_kwakwala_liqwala keyboard (in the GitHub repository at: https://github.com/keymanapp/keyboards/tree/master/release/fv/fv_kwakwala_liqwala). The last change to this keyboard was also 18 Oct 2018.

**Comment by LornaSIL** [comment]
https://github.com/keymanapp/keyboards/tree/master/release/fv/fv_kwakwala).
This one looks correct to me on an android.

https://github.com/keymanapp/keyboards/tree/master/release/fv/fv_kwakwala_liqwala
).
This one seems to have problems.

**Comment by LornaSIL** [comment]
Fixed by #1262 @madebybridget
