### ISSUE TITLE
GFF Eritrean-Tigrinya (gff-tir-er-powerpack-7) keyboard does not appear to support numbers correctly

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#126]
Via customer support (X77903).

Here is what I have discovered and I hope you will correct the problem. 

There are two (2) KEYBOARDS available for Eritrean Tigrigna(Tigrinya) typing on Keyman, both by Ge’ez Foundation. They are: 

1. GFF Eritrean-Tigrinya Language Keyboard +Font Power Pack (2.3 MB) (toggled by CNTR+ALT+T displaying a blue colored font) (ት) 

2. Tigrigna EZ (Eritrea) (101.8 KB) (toggled by CNTR+ALT+G displaying a green colored font) (ት) 
Package 2 works fine. Click (‘)1, one gets (፩). But package 1 will NOT do that! Package one is supposed to be the BETTER one by the developer’s own claim and I agree, EXCEPT it DOES NOT work with NUMBERS.

**Comment by dyacob** [comment]
I should be working on the Tigrinya keyboards this week, following the PR processing for Ge'ez and Blin, and will look into these issues.

**Comment by dyacob** [comment]
This issue is resolved with the recent updates to both Tigrinya keyboards where typing Ethiopic numerals is now done with # in place of apostrophe (e.g.  #1 and no longer '1).

**Comment by DavidLRowe** [comment]
fixed by #92
