### ISSUE TITLE
[n'ko] User requests touch layout keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1291]
One of the Keyman users corresponding on the Keyman [Facebook page](https://www.facebook.com/KeymanApp/) has asked for help in creating a lexical-model and touch layout keyboard for N'ko.

He's sent me a wordlist to create the lexical-model, and also asked 

> S'il vous plaît, si vous pouvez reorganiser le clavier N'ko au disposition de cette image, parce-que c'est ça le standard de nôtres clavier N'ko:

(Google Translate)
> Please, if you can rearrange the N'ko keyboard in the layout of this image, because that is the standard of our N'ko keyboard:

### Default layer
![default layer](https://user-images.githubusercontent.com/7358010/87627480-0b128000-c759-11ea-897e-25e3b22a654d.jpg)

### Shift layer
![shift layer](https://user-images.githubusercontent.com/7358010/87627498-14035180-c759-11ea-8de9-9ee8d4ee735c.jpg)

# Numeric layer
![number layer](https://user-images.githubusercontent.com/7358010/87627519-19f93280-c759-11ea-8cb8-50d9d064945a.jpg)

### Legacy keyboard
I see there's legacy/n/nko keyboard, but the keyboard package currently doesn't include the touch layout .js file.

**Comment by LornaSIL** [comment]
We do have the source for the N'ko keyboard in legacy and it was copyright for both Michael Everson and Tavultesoft so I think we can move the license to MIT. I'll shoot him an email to let him know we want to enhance the keyboard with touch.

The font distributed with the legacy keyboard is graphite only. We may want to ask the user if there's a more current font (Noto?) that we should package with the keyboard.

**Comment by LornaSIL** [comment]
Actually, I'd like clarification from @mcdurdin regarding the keyboard. In most of the source files it seems to indicate it was developed by Marc/Tavultesoft. Also, in the kmn and on the first screen when you double-click the kmp it includes Michael Everson's name. Should the copyright by "Michael Everson and SIL International" or is it just "SIL International"?

It looks like the keyboard was developed while N'Ko was in the Unicode pipeline.

**Comment by darcywong00** [comment]
The legacy/nko keyboard also has version 1.2 .js keyboard for Android (not in the kmp).
https://s.keyman.com/keyboard/nko/1.2/nko-1.2.js

**Comment by LornaSIL** [comment]
I've been told by several people that `nqo` isn't really a language, that it was mistakenly considered a language at the time the script was encoded. So, I looked at `nqo` on the Ethnologue and it says "No known L1 speakers in Guinea. Ethnic population: No ethnic community. Total users in all countries: none known." It goes on to say "Classification: Mixed language" and then "Other Comments: A standardized register of Eastern Maninkakan [emk]."

I wonder if you should double-check on the language code. See if the word list is really Eastern Maninkakan. If so, it is either `emk` or `man` (which would be the macro-language).

**Comment by mcdurdin** [comment]
> The legacy/nko keyboard also has version 1.2 .js keyboard for Android (not in the kmp).



> Should the copyright by "Michael Everson and SIL International" or is it just "SIL International"?

According to my email history (2012), "N’Ko is based on Michael Everson’s work, with a lot of work by us." So we need both. License is not particularly clearly defined (not surprising given the date).

> The legacy/nko keyboard also has version 1.2 .js keyboard for Android (not in the kmp).

This is not actually a mobile-optimized layout; it's a KeymanWeb for desktop devices layout that will load on an Android.

> We may want to ask the user if there's a more current font (Noto?) that we should package with the keyboard.

Yes; I expect modern Android devices include an N'Ko font.

**Comment by LornaSIL** [comment]
I've reviewed the keyboard in legacy (phonetic based) and the desktop bears no relation to this mobile layout. I found another desktop layout online that is a much closer match to the mobile layout. I think I'd rather create a whole new keyboard for your user.

**Comment by darcywong00** [comment]
> I think I'd rather create a whole new keyboard for your user.

Sounds good. I started a new touch layout as "sil_nko", but happy to pass it to you to finish.
https://github.com/darcywong00/keyboards/tree/sil_nko

I'll have to ask which font to use. The Google font [Noto Sans N'Ko](https://www.google.com/get/noto/#sans-nkoo) doesn't seem to include 3 of the  characters that were added in Unicode 11
U+07FD NKO_DANTAYALAN
U+07FE NKO_DOROME_SIGN
U+07FF NKO_TAMAN_SIGN
