### ISSUE TITLE
Broken internal links for keyboard help files

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1332]
CI is now checking broken internal links on https://github.com/keymanapp/help.keyman.com PRs.

The following keyboard help have missing files:
(if we fix, maybe only fix the most current versions ~and minor bump in versions?~)
```
galaxie_greek_positional/1.0/keyboardchart.htm
galaxie_greek_mnemonic/3.2.1/keyboardchart.htm
indic%20roman%20transliteration/1/welcome_files/filelist.xml
khowar/1.0/Khowar.ico
sxava/1.0/sxava_ekzerco_1.png
tibetan_direct_input/1.4/0f96.png
gff_tir_er_7/1.0/TigrignaErTyping-English.pdf
gff_tir_et_7/1.0/TigrignaEtTyping-English.pdf
thamizha_anjal_paangu/2.1/keyboardchart.htm

lingfilsemitica/3.6.0/welcome_files/filelist.xml:
lingfilsemitica/3.6.0/welcome_files/editdata.mso
lingfilsemitica/3.6.0/welcome_files/item0007.xml
lingfilsemitica/3.6.0/welcome_files/themedata.thmx
lingfilsemitica/3.6.0/welcome_files/colorschememapping.xml
```

gff_amharic needs a lot of AmharicTyping-X.pdf

These are missing keyrenderer.js and welcome.htm/welcome-X.htm:
```
thamizha%20bamini/2.0/keyboardchart.htm
thamizha%20typewriter/2.0/keyboardchart.htm
thamizha%20anjal/2.0/keyboardchart.htm
tamil%20-%20visual%20media/1.2/keyboardchart-modular.htm
tamil%20-%20visual%20media/1.2/keyboardchart-typewriter.htm
```

**Comment by darcywong00** [comment]
low priority

**Comment by LornaSIL** [comment]
If it's just a change in the help file folder of a keyboard we don't need to bump the version number of a keyboard, right? Or does it not get transferred to the help repo if we don't bump the version?

Some of these are now deprecated. Do we need to do anything with the deprecated ones?

**Comment by darcywong00** [comment]
Oh right, we can leave the version intact. Let's wait to see what @mcdurdin wants to do with the help for deprecated keyboards

**Comment by mcdurdin** [comment]
The broken links cause trouble for us -- if we can remove the broken links in the .php files, that's all we need to do.

**Comment by DavidLRowe** [comment]
@darcywong00 @mcdurdin See if Lorna's changes fix this issue. Thanks!

**Comment by darcywong00** [comment]
Thanks for being on the ball with this, @LornaSIL . Unfortunately, I wrote an incomplete list of the reported links. I can see which links remain in PR 224 above and list them in a separate issue.

**Comment by DavidLRowe** [comment]
Thanks, @darcywong00 . Please go ahead and open a new issue (or perhaps several if there are logical groupings?).

I'll go ahead and close this one.
