### ISSUE TITLE
[rawang] User request for touch-optimized layout

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1338]
A user is using rawang version 1.5 on Desktop. He's also currently able to install the "web" version of the keyboard in Keyman for Android 13.0.

But since a touch-optimized layout doesn't exist, he won't be able to search for the mobile keyboard when Keyman 14 gets released.
e.g. https://keyman-staging.com/keyboards?q=rawang&embed=android

Would it be possible for @sdysart or @MakaraSok to work with the user to add a touch layout?

**Comment by LornaSIL** [comment]
@darcywong00 I'm willing to work on this if you send me the user contact info.
