### ISSUE TITLE
FV keyboards that need version increment to force update

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyboards#1375]
The following keyboards have an issue in the touch layout that results in misaligned keys in certain circumstances.

```
fv_gwichin
fv_hlgaagilda_xaayda_kil
fv_kwakwala_liqwala
fv_southern_tutchone
fv_taltan
```

The problem is that the widths of some keys or blank spaces are specified as numbers (no quote marks) rather than strings (with quote marks), for example:
`"pad": 70`
rather than:
`"pad": "70"`

The compiled touch layout information is used by Android and Apple devices as well as web simulation of those devices. Some platforms may handle the bad value correctly but some do not.

The compiler has been changed to handle such invalid values, so any keyboard that gets released from now on will avoid the problem (without having to fix the bad values). The problem is that existing keyboards won't be recompiled unless the version number is incremented.

@madebybridget I'm willing to do the version number increment for these five keyboards if that fits with your plans. Otherwise you can do it at a later time or when making updates to these keyboards for other reasons.

Reference: See #1373 and #1374 for pull requests that do this for other keyboards.

**Comment by madebybridget** [comment]
Hi @DavidLRowe, my sincerest apologies for the wait! I just learned that my email client was filtering all GitHub emails into Junk, so I'm catching up on missed messages here. I would very much appreciate it if you could do the version number increment as offered -- please let me know if there's something needed on my end. I'm grateful for your support!

**Comment by DavidLRowe** [comment]
PR 1469 addresses this issue for fv_gwichin and fv_southern_tutchone
PR 1470 addresses this issue for fv_taltan and fv_kwakwala_liqwala (by making changes for other reasons)
PR 1471 addresses this issue for for fv_hlgaagilda_xaayda_kil (by making changes for other reasons)
