### ISSUE TITLE
Requesting Changes on SIL Shan Keyboard

### ISSUE THREAD

**Issue by SZTSIIT** [keymanapp/keyboards#1377]
Requesting   " ံ" - 1036 on Shan Keyboard

Currently Shift+H is " 1037 ့ MYANMAR SIGN DOT BELOW= aukmyit• a tone mark" which is not in use in Shan Language. See the image below.
![image](https://user-images.githubusercontent.com/69423986/97769154-ecb17400-1afe-11eb-9bbd-99e5b09f2fb8.png)

Instead of 1037 can you replace 1036 ? 

We do use in Shan language when writing old format. Below are the samples.
![image](https://user-images.githubusercontent.com/69423986/97769123-a825d880-1afe-11eb-97d9-4c15e9220e56.png)

Source: https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_shan
Tested on : https://keyman.com/keyboards/sil_shan

**Comment by LornaSIL** [comment]
I would be a bit nervous about changing the keyboard at this point. The documentation is somewhat sparse.

You can access the dot below (U+1036) by typing `J` (output: U+1086), `H` (output U+1037), plus RALT `h`. The rule inserts U+1036 in front of U+1086 U+1037.
Also `J` plus RALT `h` gives U+1036 followed by U+1086.

I hope that gives you enough information to get the output you need. I see that we should enhance the documentation.
