### ISSUE TITLE
EuroLatin update

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1382]
From the community site:
https://community.software.sil.org/t/character-addition-request-in-eurolatin-keyboard/4055

I see that the EuroLatin keyboard is currently the one listed for Zapotec languages. In some of the Zapotec languages in the southern Sierra region of Mexico (including ethnologue ztg) a couple characters are used that are not included in this keyboard, namely an underlined x and an underlined digraph ch. We would love to see these be added to that keyboard to make this keyboard functional for another group of Zapotecs. Can this happen?

**Comment by LornaSIL** [comment]
Codepoints:
- x with "underline" is U+0078 U+0331
- ch with "underline": U+0063 U+0332 U+0068 U+0332 (and, of course, consider casing - is CH ever needed?)

**Comment by LornaSIL** [comment]
@mcdurdin Do you have the source files for creating the EuroLatin graphics? This update will require updating the graphics.

**Comment by mcdurdin** [comment]
I believe the source for those images is usage.htm in the same folder (note that Keyman 14 for Windows will not support usage.htm 😢 because of security restrictions on displaying web pages in the On Screen Keyboard).
