### ISSUE TITLE
[fv_hlgaagilda_xaayda_kil] Touch layout looks like US

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1384]
A user of the FV app provided the following feedback on the Play Store page:
> the haida keyboard seems to just be a regular english keyboard.

I (Darcy) investigated more and found:
In Keyman, when I search for "haida"

![haida search](https://user-images.githubusercontent.com/7358010/98629184-e4e99f00-234a-11eb-8481-c6b528ad059e.jpg)

and install fv_hlgaagilda_xaayda_kil, the touch layout 
![haida layout](https://user-images.githubusercontent.com/7358010/98629203-f0d56100-234a-11eb-808d-42004a26b706.jpg)

doesn't contain longpress keys as the help doc says
https://help.keyman.com/keyboard/fv_hlgaagilda_xaayda_kil/9.1/fv_hlgaagilda_xaayda_kil

I would expect longpresses on the vowels, and <kbd>g</kbd>, <kbd>k</kbd>, <kbd>x</kbd>

Looking at the source from #490, I see the touch layout rules in `.kmn`, but the [T_] keys don't seem to appear in the `.keyman-touch-layout` file

**Comment by DavidLRowe** [comment]
@madebybridget Hi, Bridget, hope all is well with you.

It seems that when this keyboard was migrated from legacy to release, the touch layout was replaced by a generic English one. 

Would you like us to look into this and restore the original touch layout if we can? Please let us know. Thanks!

**Comment by madebybridget** [comment]
Hi @DavidLRowe -- yes, that would be great. Thank you very much! Please let me know if you aren't able to restore the original touch layout.
