### ISSUE TITLE
[sil_cameroon_qwerty, sil_cameroon_azerty] Key formatting bug

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#1396]
I almost didn't realize this one, and it admittedly _is_ a pretty small, easy-to-miss detail.  Take a look at the `abc` key from the symbol layer, as seen below:

<img width="308" alt="Screen Shot 2020-11-25 at 4 01 20 PM" src="https://user-images.githubusercontent.com/25213402/100205348-971e8a80-2f37-11eb-9970-891c6a8ab4cf.png">

In case it helps, a cropped version:

<img width="250" alt="Screen Shot 2020-11-25 at 4 01 29 PM" src="https://user-images.githubusercontent.com/25213402/100205383-a1d91f80-2f37-11eb-9e4e-9019e8eb9a0c.png">

Note how the `abc` key has the same formatting as keys that produce output text, despite being a layer-change key.  The key's color should match that of the backspace and globe keys.  This is the one spot in the keyboard where I see the `abc` use output-key formatting; everywhere else it uses special-key formatting.  Pretty sure this specific case (for symbol layer) is unintended.

The same issue occurs for the same layer (the 'symbol' layer) for `sil_cameroon_azerty` as well:

<img width="244" alt="Screen Shot 2020-11-25 at 4 06 10 PM" src="https://user-images.githubusercontent.com/25213402/100205805-29269300-2f38-11eb-9035-ee774628bf45.png">

**Comment by MattGyverLee** [comment]
Interesting. So things listed as 'Special (Active)' are showing up as key grey on iOS.

This works for Android... `.android .kmw-key-special-on{color:#88f;background-color:#ccf;}`, though the developer doesn't suggest this specific selector in autocomplete.

On iOS...i'm having a hard time overriding the default KMWOSK.css.

**Comment by MattGyverLee** [comment]
@jahorton With https://github.com/keymanapp/keyboards/pull/1394, my keyboards now has a CSS workaround for what I believe to be a Keyman bug. This can be closed for Cameroon Azerty and Qwerty, but I want to make sure you have logged the changes needed in keyman/kmea/kmwosk.css before it gets closed here and lost.

**Comment by DavidLRowe** [comment]
Does this need to be moved to a keymanapp/keyman issue?

**Comment by MattGyverLee** [comment]
I guess that depends on whether your team thinks it is a bug to investigate/fix globally

I think that any keyboard using Special (active) on a dark Android will see the same bug, and I've pointed out the target CSS.

**Comment by MattGyverLee** [comment]
So, I've fixed this in my keyboard (https://github.com/keymanapp/keyboards/pull/1394), created the bug report on keymanapp/keyman (https://github.com/keymanapp/keyman/issues/4153), and made a pull request (https://github.com/keymanapp/keyman/pull/4154) to fix this globally in `kmwosk.css`. 

This issue can be closed.
