### ISSUE TITLE
26 legacy keyboards have malformed .kmp files

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1398]
The following 26 keyboards have .kmp files that do not contain .js files, but the .keyboard_info states they have mobile support. Each of them has a .js in the folder.

armenian
dene_a
dene_c
dlia25bas: DEPRECATED
dzongkha: DEPRECATED
georgian: DEPRECATED
grkpoly2
isis_bangla
isis_devanagari
isis_gujarati
isis_gurmukhi
isis_kannada
isis_malayalam
isis_oriya
isis_tamil
isis_telugu
khmer10: DEPRECATED
kbdurdu: DEPRECATED
lushootseed
mbsindhi
nuer13: DEPRECATED
orviet10
orvietviqr10
phoneticmalayalam
venetian: DEPRECATED
yidish2k: DEPRECATED

Some of these are deprecated but we should still clean up, either by removing the platform support entry or by fixing the kmp (preferable). It may be possible to do this with a script.

**Comment by mcdurdin** [comment]
Changes required for each keyboard are:

1. Construct and add a kmp.json (if not present)
2. Add the keyboard.js.
3. Bump the version number in the .keyboard_info and the kmp.inf/kmp.json so that they deploy to downloads.keyman.com.

**Comment by LornaSIL** [comment]
For Armenian I get this error:
```armenian.kps: Error: Keyboard with ID 'armenian' is included with two differing versions: '', '1.0'. The keyboard versions must be consistent.
```
I think the .kmx has a version and the .js does not.

**Comment by LornaSIL** [comment]
Also, since `armenian.js` file is now in the .kmp, can I delete `armenian.js` from the source folder?

**Comment by LornaSIL** [comment]
@mcdurdin I think after your response I'll just commit the armenian one and ask you to review it. If I do that one correctly then the others will be fairly easy. I'm just trying to get my head around this.

**Comment by mcdurdin** [comment]
> So, if I construct the `kmp.json` file I can just add that and the `armenian.js` file into the existing `armenian.kmp` the same way I would add to a .zip. Is that correct? And if I do that, will the differing versions be a problem?

The differing versions should not be a bit problem in this instance, I think. Alternatively, it is not that hard to patch a version number into a .js file (but `1.0` is default if it is missing, anyway).

**Comment by mcdurdin** [comment]
> Also, since `armenian.js` file is now in the .kmp, can I delete `armenian.js` from the source folder?

No, we need to keep the standalone .js for use with KeymanWeb.

**Comment by LornaSIL** [comment]
Not considering the deprecated keyboards, these seem to have problematical .js files:
```
armenian
isis_bangla
isis_devanagari
isis_gujarati
isis_gurmukhi
mbsindhi
```
Unless someone else wants to figure out how to edit .js files, I'm inclined to just removed it from keyboard_info file.

**Comment by DavidLRowe** [comment]
Summary:
#1405 
dene_a
dene_c
grkpoly2
lushootseed
orviet10
orvietviqr10
phoneticmalayalam

#1406 
isis_kannada
isis_malayalam
isis_oriya
isis_tamil
isis_telugu

#1408 -- change .keyboard_info to remove mobile 
dlia25bas: DEPRECATED
dzongkha: DEPRECATED
georgian: DEPRECATED
khmer10: DEPRECATED
kbdurdu: DEPRECATED
nuer13: DEPRECATED
venetian: DEPRECATED
yidish2k: DEPRECATED

Remaining keyboards, which have issues with .js files:
armenian -- PR #1402 
isis_bangla
isis_devanagari
isis_gujarati
isis_gurmukhi
mbsindhi

**Comment by mcdurdin** [comment]
> Remaining keyboards, which have issues with .js files:
> armenian -- PR #1402
> isis_bangla
> isis_devanagari
> isis_gujarati
> isis_gurmukhi
> mbsindhi

For these keyboards, I suggest we mark them as desktop-only -- i.e., in .keyboard_info, we use the following platforms:

```json
    "platformSupport": {
        "windows": "full",
        "desktopWeb": "full",
        "macos": "full",
        "linux": "full"
    },
```
