### ISSUE TITLE
[SIL_Cameroon_QWERTY] [SIL_Cameroon_AZERTY] Letters running off the bottom of keys with large font sizes

### ISSUE THREAD

**Issue by MattGyverLee** [keymanapp/keyboards#1399]
I recently saw this on a user's phone (the user had the font set to XL in android phone settings on his Chinese-made phone), and this screenshot is from Android Studio Emulation on a Pixel 4 (system font size XL):

![image](https://user-images.githubusercontent.com/986339/100336363-604b8180-2fd6-11eb-954d-27525eebf51d.png)

This is "Large" (which is better, but the q touches the bottom):

![image](https://user-images.githubusercontent.com/986339/100338502-f54f7a00-2fd8-11eb-88c2-5319d4b4ac29.png)

I realize that it may not always be possible to support all text sizes or stacked diacritics, but the space is there to display these if vertically centered properly.

I'm using Andika (Africa Subset), and I know that most SIL fonts have large [ginormous] line spacing to allow for a stack of diacritics. 

I'm trying to create Andika Africa Compact with a more reasonable spacing that might help this. While in this process, Victor from WSTech said this: 

```
Your problem, however, seems more like a Keyman bug. Keyman should not be basing positioning 
on vertical ascender values. In a keyboard display context there should be no difference at all 
between normal and 'compact' versions. This could bite other projects, too, including ones 
where there is no option for a 'compact' font variant.

Please file a bug report with the Keyman team.
```
Notice that the dot seems to moves letter down, as the `m` sits on a higher baseline, but other letters with longpresses seem to be pushed down. It should be a simple CSS change, and I'm looking into it.

In a related issue, I had to reinstall the app/keyboard after setting android settings to get the font-size to change (I didn't try rebooting). Keyman might need another refresh hook for system font size changes.

I don't think any of my CSS currently deals with general letter size or placement.

**Comment by MattGyverLee** [comment]
Adding
`.kmw-key span { line-height: 1;}` 
solves my problem immediately without typetuning the font.

**Comment by MattGyverLee** [comment]
I'm Closing this issue, as I have a custom CSS solution for my keyboards, but I believe there is still needed follow-up by the Keyman team in https://github.com/keymanapp/keyman/issues/4026 in able to support most SIL fonts (that have extra headroom) and visually-challenged users (using large system fonts).

**Comment by jahorton** [comment]
> @jahorton , is this a more reasonable default for kmwosk?

I'll have to properly investigate to be sure, but this sounds like a good lead.  Thanks for making us aware of the issue!  I've opened an issue for this on the main keyman repo.
