### ISSUE TITLE
N'Ko Phonetic Keyboard - not optimize for mobile devices

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1426]
Reported on Google Play: 

> This keyboard is usable for nko (ߒߞߏ), but some parts of its is hidden, please download nko and see its. This keyboard is usable for nko (ߒߞߏ), but some parts of its is hidden, please download nko and see its.

**Comment by LornaSIL** [comment]
This report does not give us enough information. The keyboard is a tablet layout which may be what they are complaining about. Accessing the shift layer is set appropriately.

**Comment by MakaraSok** [comment]
That is true. The feedback was given on the review section of [Google Play Store](https://play.google.com/console/u/0/developer/6504570275588761950/app/4972763830494387739/user-feedback/review-details?reviewId=gp%3AAOqpTOHmG01DilU_LB05isT2r4Tosy84BFP2CRzRpRTXyPIZyjBOtIWUIQvwd8VONtu5eWo3CgAWwxQTk_lQFNk&corpus=PUBLIC_REVIEWS). We can not reach out to the user for more info from there.

However, I just found that we have another N'ko keyboard in place already with a better mobile layout. https://help.keyman.com/keyboard/sil_nko/1.0/sil_nko compared with . I'll close this issue now.
