### ISSUE TITLE
Keyboards with -layout.js instead of .keyman-keyboard-layout

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1433]
These keyboards (in `release`) still have -layout.js instead of the new name of keyman-keyboard-layout. I would like to see them fixed so they are all consistent. I wonder if we can do this without bumping the keyboard version since there would be no change to the keyboard, just file naming. The files would need to be renamed and the reference in the .kmn would need updating.
```
tem_kdh-layout.js
rac_palula-layout.js
rac_khowar-layout.js
rac_brahui-layout.js
rac_balti-layout.js
galaxie_greek_positional-layout.js
el_pasifika-layout.js
inuktitut_pirurvik-layout.js  (Delete. There is already a keyman-keyboard-layout file being used.)
```

**Comment by DavidLRowe** [comment]
Would you change the HISTORY.md file?

**Comment by LornaSIL** [comment]
I'm happy to do whatever needs to be done...but is it necessary to add to HISTORY.md file? It's just a renaming issue.

**Comment by LornaSIL** [comment]
Kmhmu 2008.kvk (delete since there is a properly named kmhmu_2008.kvks)
rac_brahui.kvk (rename)
tem_kdh.kvk (rename)

**Comment by DavidLRowe** [comment]
I guess the details of the changes would be in the git repository, so probably not needed in HISTORY.md.

Perhaps @mcdurdin can comment next week when he's back.

**Comment by mcdurdin** [comment]
I don't think updates to HISTORY.md are needed for this maintenance change.
