### ISSUE TITLE
bug(mozhi_malayalam): default layer key-text has excess whitespace

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#1445]
Note the difference between the 'default' and 'shift' layers of the `mozhi-malayalam` keyboard:

<img width="444" alt="Screen Shot 2021-01-22 at 9 33 21 AM" src="https://user-images.githubusercontent.com/25213402/105438123-f7f6e480-5c94-11eb-8ff1-6b07c84f6bc3.png">

<img width="443" alt="Screen Shot 2021-01-22 at 9 33 30 AM" src="https://user-images.githubusercontent.com/25213402/105438136-fc230200-5c94-11eb-828a-0bf3940183dc.png">

The cause?  Note how the 'Q' key is defined on the 'default' layer:

<img width="514" alt="Screen Shot 2021-01-22 at 9 34 44 AM" src="https://user-images.githubusercontent.com/25213402/105438194-1361ef80-5c95-11eb-80bb-7e03f2cdb29c.png">

Or, from keyboard source: https://github.com/keymanapp/keyboards/blob/daca62fc2482e32a723658e3079f52539fd45550/release/m/mozhi_malayalam/source/mozhi_malayalam.kvks#L11-L16

Compare vs the shift layer:

https://github.com/keymanapp/keyboards/blob/daca62fc2482e32a723658e3079f52539fd45550/release/m/mozhi_malayalam/source/mozhi_malayalam.kvks#L70-L73

When it comes to KeymanWeb, HTML being HTML, the excess whitespace seen within the 'span' doesn't directly affect the key's appearance and alignment.  The problem, though - it _does_ affect our automatic font-scaling calculations, which causes the 'default' layer's keys to have unnecessarily small text.

_Based on comment by @jahorton in https://github.com/keymanapp/keyman/issues/4270#issuecomment-765074279_

As the 'default' layer's whitespace doesn't appear to be intended as a keyboard-layout design decision (based on comparison to the 'shift' layer) I'd recommend trimming the whitespace from the text of the default layer's keys.

**Comment by jahorton** [comment]
As a secondary note, this keyboard could also make use of this 14.0 feature (which has back-compat measures for earlier versions): https://github.com/keymanapp/keyman/pull/3878#issuecomment-729551776

We now support some default zero-width non-joiner symbols.  Granted, this keyboard would probably prefer to have extra symbols for some of its other variants, but I figured it'd be worth noting anyway.

**Comment by beniza** [comment]
PR #1814 fix this issue
