### ISSUE TITLE
galaxie_greek_hebrew_mnemonic should not support iOS/Android

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1451]
This is not determined automatically correctly, so we should write the targets into the .keyboard_info file.

**Comment by jahorton** [comment]
Also, the "positional" version.

**Comment by mcdurdin** [comment]
We should also remove 'web' from the list of supported platforms for galaxie_greek_mnemonic, galaxie_hebrew_mnemonic, and galaxie_greek_hebrew_mnemonic, as web does not currently really support mnemonic (nor do Linux/macOS for that matter)

**Comment by jahorton** [comment]
Note:  the base, single-version packages do _not_ support iOS/Android.  It's (mostly) just the combo packages that do:

When using iOS's keyboard search:
![Screen Shot 2021-02-03 at 1 34 47 PM](https://user-images.githubusercontent.com/25213402/106708242-1c53a900-6625-11eb-9ed7-e02a760c7f95.png)

![Screen Shot 2021-02-03 at 1 33 13 PM](https://user-images.githubusercontent.com/25213402/106708258-21185d00-6625-11eb-8542-bb4911488402.png)

**Comment by mcdurdin** [comment]
> Also, the "positional" version.

I think the positional version does support iOS/Android.

**Comment by DavidLRowe** [comment]
There are four "galaxie" keyboards. Which ones are affected and what changes are needed? Thanks!

**Comment by mcdurdin** [comment]
After all that noise above, the following changes are required, I think:

1. galaxie_greek_hebrew_mnemonic needs to note support only for Windows in the .keyboard_info, to reduce the platform support from the default.
2. We should remove 'web', 'macosx', and 'linux' from the list of supported platforms for galaxie_greek_mnemonic and galaxie_hebrew_mnemonic, as these platforms do not yet support mnemonic properly -- and we have a positional layout that does work.

**Comment by DavidLRowe** [comment]
To change the platform support in the .keyman_info file, is it sufficient to change the &TARGETS field in the .kmn file? Or does something need to be explicitly changed in the .keyboard_info file?

**Comment by mcdurdin** [comment]
In this case, we need to specify the platform directly in the .keyboard_info, because there are two .kmx files in the package. Something like:

```
"platformSupport": {
  "windows": "full"
},
```

**Comment by DavidLRowe** [comment]
I see now that there are two "galaxie" items under release/packages (in addition to the four I found earlier). 

So, IIUC the changes needed are:
- galaxie_greek_hebrew_mnemonic: change .keyboard_info file
- galaxie_greek_mnemonic: remove web, macosx, linux from supported platforms (.kmn, README.md)
- galaxie_hebrew_mnemonic: remove web, macosx, linux from supported platforms (.kmn, README.md)

**Comment by mcdurdin** [comment]
Yes, that sounds correct.

**Comment by DavidLRowe** [comment]
And presumably changes to version number (and copyright date) in all affected files.

I'm not familiar with packages.
- How does the galaxie_greek_hebrew_mnemonic find the components it needs? Is that through the .kpj file?
- Do the changes to the base keyboards need to be made first in a separate PR before changing the package?

Also, how urgent is this change? As you likely know, Lorna is away at the moment.

**Comment by jahorton** [comment]
The packages don't exactly have the highest download counts.

![Screen Shot 2021-02-03 at 1 33 13 PM](https://user-images.githubusercontent.com/25213402/106708258-21185d00-6625-11eb-8542-bb4911488402.png)

At 157 monthly downloads for the `mnemonic` variant and single-digits for the others... it's probably a low, whenever-you-get-around-to-it priority.

**Comment by mcdurdin** [comment]
> At 157 monthly downloads

I'm going to disagree here on priority. We haven't used the download counts to make these decisions in the past (or we'd can the iOS app altogether!) I'd say that's a non-trivial number of new installs. Many of our packages cater to very small communities but that doesn't change the importance of the package to that community.

It's not critical priority but should be sorted out.

> * How does the galaxie_greek_hebrew_mnemonic find the components it needs? Is that through the .kpj file?

* The .kps file lists the .kmx files it needs. It's an XML file so you can easily see the files listed in it by viewing the source (or opening in the Package Editor in TIKE).
* The .kpj lists the source .kmn keyboards that the .kps file depends on, so they'll be (re)built before the .kmp file is built from the .kps. They'll be built into the /build folder relative to the .kpj folder (so there will be a copy of the .kmx in both /release/g/galaxie_greek_mnemonic/build and also in /release/packages/galaxie_greek_hebrew_mnemonic/build).
* This allows you to build either the single-keyboard package or the multi-keyboard package at any time without reference to the other package.

> * Do the changes to the base keyboards need to be made first in a separate PR before changing the package?

You should be able to make the changes to all three keyboards/packages in the same PR.
