### ISSUE TITLE
[sil_cameroon_qwerty] Size of welcome.htm file causes an issue on some devices

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1475]
See keymanapp/keyman#4511

On some Android devices, the WebView for viewing the welcome.htm file becomes unresponsive. This can occur in either the Keyman for Android internal WebView, or with the `ACTION_VIEW` intent of viewing the file in Chrome 88.0 browser

Per @mcdurdin , maybe the 780kb file (before assets) needs to be split somehow.

Also applies to sil_cameroon_azerty

(low priority)

**Comment by MattGyverLee** [comment]
I'm just seeing this (I didn't get tagged).

I've done everything I can to compress without removing content. I like having the key combination tables I generated in the documentation, but it's likely that no one ever uses them. Hmm...

**Comment by mcdurdin** [comment]
I'd recommend splitting the key combination tables into a separate .htm file and linking to it in welcome.htm. So long as you include it in the package, it will work. See for example https://github.com/keymanapp/keyboards/blob/ffa4658542dfeff715e8d9a18c6713b9893200c1/release/e/ekwtamil99uni/source/welcome/keyboardchart.htm with ekwtamil99uni.

**Comment by mcdurdin** [comment]
Oh, and tagging you now! Sorry you didn't get tagged earlier :grin:
