### ISSUE TITLE
SIL Hebrew keyboard: the Left Option Key (MacOS) not working as the Right Option Key

### ISSUE THREAD

**Issue by martinmts** [keymanapp/keyboards#1476]
Hi,
The on-screen keyboard shows exactly the same mapping for the SIL Hebrew keyboard, but it does not output the characters as shown on the on-screen keyboard.

For instance, 
"Right Option + A" outputs: `ׇ` (qamets hatuph).
I expect "Left Option + A" to output the same sign, as the on-screen keyboard shows. But it outputs `å`.

"Right Option + Shift + A" outputs: `ֲ` (hateph pathach).
I expect "Left Option + Shift + A" to output the same sign, as the on-screen keyboard shows. But it outputs `Å`.

Is it by design?

**Comment by LornaSIL** [comment]
We felt we needed to use RALT (not just ALT) because of issues on Windows. However, I do see that the documentation needs enhancing as we still say "ALT" in multiple locations rather than RALT. We will try to update that in the future.

**Comment by martinmts** [comment]
Thanks, @LornaSIL.
For those who would like to use the Left Option key, I use Karabiner-Elements to set the Left Option key to the Right Option key. (Note that if you need the "Left Option" key for other apps, this method may not be the best for you.)

![image](https://user-images.githubusercontent.com/32575091/110044656-7f655800-7d17-11eb-932c-64c5cd90f3b1.png)

**Comment by LornaSIL** [comment]
I just double-checked and the documentation always says Right-Alt or RALT, so I don't think this is still an issue.
