### ISSUE TITLE
[khmer_angkor] Invalid link on Welcome page

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyboards#1482]
`welcome.htm` contains a link to "Khmer Fonts by the Khmer Software Initiative", but the target of the link doesn't exist.

![Screenshot from 2021-03-15 15-53-43](https://user-images.githubusercontent.com/181336/111173124-b143ad80-85a6-11eb-96f1-924e05d20d64.png)

**Comment by darcywong00** [comment]
When khmer_angkor gets an update, can you also include an example in .keyboard_info?
Maybe: <kbd>X</kbd> <kbd>J</kbd> <kbd>Shift</kbd>+<kbd>E</kbd> <kbd>R</kbd> for `ខ្មែរ`

I always forget the "correct" sequence.
