### ISSUE TITLE
[bu_phonetic] bu_phonetic does not comply with MIT license

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1483]
The bukeys.doc license stipulations (quoted below) are incompatible with the MIT license with which we require keyboards in Keyman Cloud to be shared. The keyboard license should either be updated to conform with the MIT license or be removed from Keyman Cloud.

>1.2	Terms of use
> Although the BU Phonetic keyboard and its documentation are copyrighted, they may be freely distributed and modified. I only require three things:
> •	The keyboard and its documentation may not be sold or their use restricted in any way, either in their original or modified versions. (I specifically give permission for a person to charge a reasonable consultant fee for making modifications at the request of a single user or a group of users. I do not give permission to make a modified version and then sell it afterward to people other than those for whom it was originally created, or to license or in any other way restrict the distribution of a modified version beyond the restrictions listed here for the original.)
> •	Any modified version should be clearly marked as to the fact that it is modified, as well as acknowledging the original source. 
> •	The terms of use may not be modified and should always be distributed along with the keyboard and documentation, whether the original or a modified version. They apply to modified versions of the keyboard and documentation as well as to the original.

**Comment by LornaSIL** [comment]
I did get permission to move the keyboard to MIT so I'll need to look into
this and figure out if it's just a matter of updating the documentation.
I'll double-check my communication with the author.

**Comment by LornaSIL** [comment]
Wrote author to clarify license.
