### ISSUE TITLE
[sil_myanmar_my3] request for touch version

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1497]
See https://community.software.sil.org/t/keyboard-package-error/4552/2

(also possibly the other keyboard in that screenshot?)

**Comment by darcywong00** [comment]
@sdysart is working on this
https://github.com/sdysart/keyboards/tree/myanmar3touch

**Comment by darcywong00** [comment]
Fixed by #1500 in version 1.7
