### ISSUE TITLE
[sil_nko] Additional fixes

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1498]
This was reported via user's email (and run through Google Translate)

> Hello, we have received your email regarding version 14 of keyma, we have seen a lot of improvement on the N'ko keyman keyboard.
we have 3 suggestions: 
1- the sign (u + u07f8) is not available in the N'ko keyman keyboard layout, look at this capture: what is circled in red.

![u07f8](https://user-images.githubusercontent.com/7358010/112738410-63ab4580-8f95-11eb-8368-8e7e7c5e186c.jpg)

> 2- there are 3 signs that are not displayed in the N'KO keyman layout, look at this capture: 
![3 signs](https://user-images.githubusercontent.com/7358010/112738421-7f165080-8f95-11eb-9509-4eed249453bb.jpg)
![3 signs - 2](https://user-images.githubusercontent.com/7358010/112738424-83426e00-8f95-11eb-8319-441ced649ff1.jpg)

> 3- the display of N'ko figures for the N'ko keyman keyboard for Windows on the physical buttons does not correspond to Latin figures, we would emerge that the N'ko figures are identical with the Latin figures on the physical buttons for the N'ko keyman keyboard for Windows.
here are the codes of the 3 signs not displayed in the N'ko keyman layout: look at this image: 

![latin figures](https://user-images.githubusercontent.com/7358010/112738433-95bca780-8f95-11eb-9365-65c01d4d13ca.jpg)

---------

Darcy's notes:
2. The noto sans nko font is still missing some of the characters (See the original PR #1294
3. I wonder if that's a screenshot from Keyman Developer character map

**Comment by LornaSIL** [comment]
U+07F8 is available on both the Desktop and the mobile layout.

**Comment by darcywong00** [comment]
This looks to have been resolved by #1501.

Screenshot of 15.0 in PIxel 2 emulator (Android API 21)
![Screenshot_1638515359](https://user-images.githubusercontent.com/7358010/144560530-b53d8d1d-8c26-445a-af45-06d1f5d66021.png)
