### ISSUE TITLE
Old Hungarian layout required, there are implementations for linuxes in xkeyboard-config project

### ISSUE THREAD

**Issue by tamasbartos** [keymanapp/keyboards#1530]
The iPhones already have Old Hungarian font. Noto-fonts project have two kind of Old Hungarian font under the development: ligatured, and ligatureless.
May I ask to develop "Old Hungarian" layout for desktops based on xkeyboard-config's "Old Hungarian (for ligatures)" keyboard layout? (Project page:  https://gitlab.freedesktop.org )

**Comment by LornaSIL** [comment]
Can you give us a direct link to screenshots or something?

Also, you are welcome to develop your own Old Hungarian keyboard and submit it to the repo.

**Comment by tamasbartos** [comment]
> Can you give us a direct link to screenshots or something?
> 
> Also, you are welcome to develop your own Old Hungarian keyboard and submit it to the repo.

Yes of course! I will make screenshots on the next week!

**Comment by tamasbartos** [comment]
@LornaSIL Here are the Old Hungarian layout plan, last version from XkeyboardConfig:
 
![Old Hungarian layout for desktops, basis](https://user-images.githubusercontent.com/75836867/117542908-d7bc1d00-b01a-11eb-8f6a-80a5a6ec5a3f.jpg)

![Old Hungarian layout for desktop, AltGr](https://user-images.githubusercontent.com/75836867/117542993-279ae400-b01b-11eb-9200-f851f8fd4f60.jpg)

Be careful! Caps lock must be work with each keys in each level (basis and AltGr-ed). On numpad it's not a req.

Here is a vignette plan for both Old Hungarian and Latin based Hungarian, in same vignette: 
![Latin based and Old Hungarian in same vignette](https://user-images.githubusercontent.com/75836867/117543127-c45d8180-b01b-11eb-9f1b-9c8907fa5cea.jpg)

I wrote the characters-code below where wasn't clear.

Download here a font for testing:
https://oldhungarian.eu/index_en.html

On the next week I will make a plan for phone devices. It will be working on Apple devices. They already developed their font.

**Comment by tamasbartos** [comment]
@LornaSIL Please wrote me, if somebody isn't clear for you. If you want, I upload keymap plan with borders. I worked fast, and I forget to do it.

**Comment by tamasbartos** [comment]
> Can you give us a direct link to screenshots or something?
> 
> Also, you are welcome to develop your own Old Hungarian keyboard and submit it to the repo.

I correct myself: here are the Old Hungarian base layouts:
![Old Hungarian base layouts](https://user-images.githubusercontent.com/75836867/117547902-5bcdcf00-b032-11eb-85c8-d2b6a28d5ea6.jpg)

Here are the Old Hungarian AltGr-ed layouts and numpad with AltGr:
![Old Hungarian layouts with AltGr](https://user-images.githubusercontent.com/75836867/117547951-98012f80-b032-11eb-967b-8b97d5969c36.jpg)

There is a must to work Caps Lock with every key and level, except with numpad.

Here is a vignette plan for both Old Hungarian and Latin based Hungarian alphabet, in same vignette:

![Vignette plan](https://user-images.githubusercontent.com/75836867/117548037-0b0aa600-b033-11eb-9f5e-d6c4c3f4849b.jpg)

Here is a font for check back the appereance:
https://oldhungarian.eu/index_en.html

Here is the Unicode Old Hungarian chart:

https://unicode.org/charts/PDF/U10C80.pdf#page=2

**Comment by tamasbartos** [comment]
@LornaSIL 
Here is an another font from Noto-fonts project
https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf

**Comment by tamasbartos** [comment]
@LornaSIL How I need to draw floating buttons for phone devices?

**Comment by tamasbartos** [comment]
@LornaSIL We discuss now how must appear and how will work the phone layout version.

**Comment by LornaSIL** [comment]
@tamasbartos I'll try to start with what you've given me for the desktop and then think about the phone layout. I'm not sure when I can do it given my schedule.

**Comment by LornaSIL** [comment]
@tamasbartos 

Here's a start on the layout. I have a personal preference NOT to use the 102nd key (to the left of "z") because most US keyboards don't include that key. If we do use it, we need to make sure those characters are accessible on another key. Thus, I duplicated the character from the 102nd key also on the far right, bottom row key. That means I had to put the characters you had there elsewhere.

I also noticed you want the LRM (U+200E) on the number pad, but you don't have it on the desktop. Should it be put somewhere on the RALT layer?

How does this look?
![Layoutall](https://user-images.githubusercontent.com/7071907/117883849-89ed2200-b271-11eb-8594-b7810d6331cf.png)

**Comment by tamasbartos** [comment]
> @tamasbartos
> 
> Here's a start on the layout. I have a personal preference NOT to use the 102nd key (to the left of "z") because most US keyboards don't include that key. If we do use it, we need to make sure those characters are accessible on another key. Thus, I duplicated the character from the 102nd key also on the far right, bottom row key. That means I had to put the characters you had there elsewhere.
> 
> I also noticed you want the LRM (U+200E) on the number pad, but you don't have it on the desktop. Should it be put somewhere on the RALT layer?
> 

It has got some mistake. You are right about LRM sign. I choose one position for it.
![Old Hungarian desktop layout](https://user-images.githubusercontent.com/75836867/117935605-30820300-b304-11eb-84a1-20857a61a3dd.png)
I have got a mistake: in the AltGr +Q must be produce \ char.

We already planned phone's layout, only the character codes required to push into the plan.
As I know, the bottom-left key on the Windows is OEM key.

Windows produce AltGr key as Ralt+RCtrl. I dont know, it's important or not for planning the keyboard layout. Keyboards in the Hungarian market  uses AltGr instead of Ralt.

**Comment by tamasbartos** [comment]
> @tamasbartos
> 
> Here's a start on the layout. I have a personal preference NOT to use the 102nd key (to the left of "z") because most US keyboards don't include that key. If we do use it, we need to make sure those characters are accessible on another key. Thus, I duplicated the character from the 102nd key also on the far right, bottom row key. That means I had to put the characters you had there elsewhere.
> 
> I also noticed you want the LRM (U+200E) on the number pad, but you don't have it on the desktop. Should it be put somewhere on the RALT layer?
> 
> How does this look?

@LornaSIL I can see now, what was the problem with 101-key layout. The problem had given in Latin-based Hungarian layout, too. Resolving: Old Hungarian II and Old Hungarian ii (known as Í and í) positioned Ralt and Ralt + Shift I-named button:
![oldhungariandesktop2](https://user-images.githubusercontent.com/75836867/118001657-3b11bc00-b347-11eb-8770-d55a170e3e6a.png)

@LornaSIL What do you think, AltGr and Ralt could be the same in source code, or not? AltGr on Windows = Alt+Ctrl.

**Comment by tamasbartos** [comment]
@LornaSIL The Phone version I can upload at the weekend, or later. Old Hungarian script is a Right-to-left script. Requires the phone layout  RLM and LRM key, too? I think about using decimal numbers, punctuation marks.

**Comment by tamasbartos** [comment]
@LornaSIL The AltGr problem isn't given.
The final desktop plan extended with Ralt + "q" key as \ character is the following: 
![desktop Old Hungarian](https://user-images.githubusercontent.com/75836867/118111222-af9a3880-b3e3-11eb-9ed1-171f2059b9d5.png)

**Comment by tamasbartos** [comment]
@LornaSIL There is a must to add to copyright information original developers, I think.
 ©2014, András Tisza and ©2020 Viktor Kovács

**Comment by tamasbartos** [comment]
@LornaSIL 
Here is the phone layouts screenshots:
![Old Hungarian layouts for Phone devices 1st and 2nd level](https://user-images.githubusercontent.com/75836867/118363298-f9298580-b593-11eb-8bc2-bf09830ae0ea.jpg)

![Old Hungarian layouts for Phone devices 3rd level and all spaced line](https://user-images.githubusercontent.com/75836867/118363335-26763380-b594-11eb-9fb2-99a8e0213046.jpg)

**Comment by tamasbartos** [comment]
Phone version: ©2021, András Tisza for absolutely free use.

**Comment by viktorkiwikovacs** [comment]
@LornaSIL Before it would be copyright problem, I can ask András Tisza for sign phoned version. The desktop version is agreed by him and me in xkeyboard-config project.

**Comment by viktorkiwikovacs** [comment]
https://github.com/keymanapp/keyboards/issues/1530#issuecomment-841676513 Do I?

**Comment by tamasbartos** [comment]
@keyman-server working somebody on it:
https://github.com/keymanapp/keyboards/issues/1530#issuecomment-840458784 ?

**Comment by viktorkiwikovacs** [comment]
@LornaSIL Here is the phone layout plan signed by András Tisza, that I asked according to https://github.com/keymanapp/keyboards/issues/1530#issuecomment-841676513

[telefon billentyűzet_20210516_0001.pdf](https://github.com/keymanapp/keyboards/files/6489103/telefon.billentyuzet_20210516_0001.pdf)

**Comment by tamasbartos** [comment]
> @tamasbartos
> 
> Here's a start on the layout. I have a personal preference NOT to use the 102nd key (to the left of "z") because most US keyboards don't include that key. If we do use it, we need to make sure those characters are accessible on another key. Thus, I duplicated the character from the 102nd key also on the far right, bottom row key. That means I had to put the characters you had there elsewhere.
> 
> I also noticed you want the LRM (U+200E) on the number pad, but you don't have it on the desktop. Should it be put somewhere on the RALT layer?
> 
>

Here is the final plan of Old Hungarian desktop:
[Old_Hungarian_desktop.pdf](https://github.com/keymanapp/keyboards/files/6491920/Old_Hungarian_desktop.pdf)
The left-bottom key is an OEM key. 
The "Old Hungarian ii " (u+10cd1) and "Old Hungarian II" (u+10c91) can be typed on the 101 key layouts positioned with RALT key with the key named "i" .
The u+200e key have already a position with Ralt key.
The "Old Hungarian ii" and Old Hungarian II" positioned to the right-bottom key is the worst thing, that we could to do.
Here is the Unicode Old Hungarian chart:
[Unicode Old Hungarian chart](https://unicode.org/charts/PDF/U10C80.pdf#page=2)

**Comment by tamasbartos** [comment]
@LornaSIL 
The comment https://github.com/keymanapp/keyboards/issues/1530#issuecomment-842095424 is answer for you.

**Comment by LornaSIL** [comment]
Thanks. I will work on it, in my spare time. It may be slower than you wish. Thanks for working on the agreements.

**Comment by LornaSIL** [comment]
@tamasbartos Try this out. Hope it's close to what you are wanting. If it looks okay, I'll upload it to the Keyman repository.
https://drive.google.com/file/d/14ouoUvUX0mZ0WBfd053fbLiWWLERkZ4K/view?usp=sharing

**Comment by tamasbartos** [comment]
> @tamasbartos Try this out. Hope it's close to what you are wanting. If it looks okay, I'll upload it to the Keyman repository.
> https://drive.google.com/file/d/14ouoUvUX0mZ0WBfd053fbLiWWLERkZ4K/view?usp=sharing

@LornaSIL  I found several mistakes with Ralt version. I think, copyleft symbol might to be removed, because too few fonts implements it.

Ralt version:
![LayoutU_RA](https://user-images.githubusercontent.com/75836867/118990398-235bb880-b983-11eb-88c1-5b90e925b724.png)

Ralt + Shift:
![LayoutU_SRA](https://user-images.githubusercontent.com/75836867/118990495-3bcbd300-b983-11eb-80e8-5ff068576920.png)


Please implements phone version this kind of view:

[telefon billentyűzet_20210516_0001.pdf](https://github.com/keymanapp/keyboards/files/6516547/telefon.billentyuzet_20210516_0001.pdf)

**Comment by LornaSIL** [comment]
We like to keep the phone and the desktop keyboards "in sync". Thus, if you want ampersand, tilde, etc on the phone version, then I have to find a spot for it on the desktop. If you don't like where I put it, then do suggest another position. If it's not needed, then I can also remove it from the phone version.

**Comment by tamasbartos** [comment]
> We like to keep the phone and the desktop keyboards "in sync" (the keyboard produces the same set of characters). Thus, if you want ampersand, tilde, etc on the phone version, then I have to find a spot for it on the desktop. If you don't like where I put it, then do suggest another position. If it's not needed, then I can also remove it from the phone version.

I don't think, I understand exactly, what does "in sync" mean. On android devices the Hungarian layout differs from the desktop's one. Which key on the desktop is which key on the phones?

**Comment by LornaSIL** [comment]
If the phone keyboard supports the ampersand (&), then we want the desktop keyboard to also support the ampersand. The same with tilde (~), Euro, $.

**Comment by tamasbartos** [comment]
> If the phone keyboard supports the ampersand (&), then we want the desktop keyboard to also support the ampersand. The same with tilde (~), Euro, $.

I see. But there is an another problem: phone devices don't require ZWJ, ZWNJ, RLM and LRM keys.

**Comment by LornaSIL** [comment]
> I see. But there is an another problem: phone devices don't require ZWJ, ZWNJ, RLM and LRM keys.
I have included them on the phone layout. We want the keyboards on desktop and phone to include the same set of characters.

**Comment by tamasbartos** [comment]
> > I see. But there is an another problem: phone devices don't require ZWJ, ZWNJ, RLM and LRM keys.
> > I have included them on the phone layout. We want the keyboards on desktop and phone to include the same set of characters.

Could it be divided two projects, instead. One "Old Hungarian for desktops", one "Old Hungarian for phones" ? Phones don't require ZWJ, ZWNJ, RLM, LRM keys, and for the phones aren't relevants "Historic Symbols", which are not used in the basic communications.

**Comment by LornaSIL** [comment]
There is no need or desire to split the project. Including characters that someone does not want to use does not require them to use the characters. It truly is not a problem to include them.

**Comment by tamasbartos** [comment]
> There is no need or desire to split the project. Including characters that someone does not want to use does not require them to use the characters. It truly is not a problem to include them.

All right, we discussed with each other. There is a small problem, which we still cannot resolve: on phone devices pointless to use ZWJ, ZWNJ, RLM and LRM keys.

**Comment by tamasbartos** [comment]
@LornaSIL 
There is a must to be all characters in the same level in phone and desktop version? 
There is a must to be have ZWJ, ZWNJ, RLM, LRM  keys phone version, too?

If answer of both question is no, we try to replan the layouts.

**Comment by LornaSIL** [comment]
No, the keys do not need to be in the same level or position. I did put them all on the keyboard I sent you. Some of them are on longpress keys so they are not as obvious, but if someone needs them, they are available. You can test it and suggest modifications.

Please remember that a mobile version is not just used for texting or emailing. People use mobile layouts for typing text in web pages, Google docs, even Word docs, so it is not that there is no need for everything.

**Comment by tamasbartos** [comment]
> No, the keys do not need to be in the same level or position. I did put them all on the keyboard I sent you. Some of them are on longpress keys so they are not as obvious, but if someone needs them, they are available. You can test it and suggest modifications.
> 
> Please remember that a mobile version is not just used for texting or emailing. People use mobile layouts for typing text in web pages, Google docs, even Word docs, so it is not that there is no need for everything.

I see. Then we will replan the phone version, add $,&~ and euro sign into desktop version. ZWJ and ZWNJ key will not implemented. These keys are used in secondary version layout of xkeyboard-config. Secondary layout made for those for whom the Unicode standard Old Hungarian script isn't enough. As I know, iPhone doesn't operate with this capability.

**Comment by LornaSIL** [comment]
Sounds good.

**Comment by tamasbartos** [comment]
@LornaSIL Here you are, the Old Hungarian Phone layout:
![Old_Hungarian_Phone_Layout](https://user-images.githubusercontent.com/75836867/119262046-1b498600-bbda-11eb-8116-803e886de86b.png)

Here is the Old Hungarian base and Shift/Caps-lock version:
![Old_Hungarian_desktop_layout_base](https://user-images.githubusercontent.com/75836867/119262117-61064e80-bbda-11eb-996a-cda5013a3d36.png)

Here is the Old Hungarian Ralt (AltGr) and Ralt+Shift/Caps-lock version:
![Old_Hungarian_desktop_layout_Ralt](https://user-images.githubusercontent.com/75836867/119262203-a7f44400-bbda-11eb-89d7-2081b26b9787.png)

Please, implements the desktop layout on that method, that for all levels (base and Ralt) work for all keys with Caps-lock!
It very useful. (xkeyboard-config works with this method, too)

I hope the phone and desktop version have compatible character sets. If not, please sign me back!

**Comment by LornaSIL** [comment]
Ok, thanks! I think I've got it now. They seem to contain a consistent inventory of characters.

**Comment by LornaSIL** [comment]
You can test this version if you want: https://drive.google.com/file/d/1Ac684nBPLQDritmo-rNw8ZSP0GzCe-as/view?usp=sharing
If it looks pretty good, I'll submit a PR for it to be added to the Keyman repo.

**Comment by tamasbartos** [comment]
> You can test this version if you want: https://drive.google.com/file/d/1Ac684nBPLQDritmo-rNw8ZSP0GzCe-as/view?usp=sharing
> If it looks pretty good, I'll submit a PR for it to be added to the Keyman repo.

@LornaSIL Thank you, I'll test it, but not again.

**Comment by tamasbartos** [comment]
@LornaSIL Could you explain me, how can I test layouts?
I have  a Linux distro and Windows 10.
My friend's doughter have an iPhone.

**Comment by LornaSIL** [comment]
You can download the .kmp (package) from the link above. This link should tell you how to install on mobile:
https://help.keyman.com/developer/10.0/guides/distribute/packages
I think if you have Keyman for Linux installed you can then tell it to install this package.

However, I didn't make any changes to the last layout you gave me, so I'm happy to push this keyboard to the repo if you don't want to test it.

**Comment by tamasbartos** [comment]
> You can test this version if you want: https://drive.google.com/file/d/1Ac684nBPLQDritmo-rNw8ZSP0GzCe-as/view?usp=sharing
> If it looks pretty good, I'll submit a PR for it to be added to the Keyman repo.

@LornaSIL 
The caps-lock doesn't work with all keys on all level, only for letter-like symbols.

**Comment by tamasbartos** [comment]
> You can test this version if you want: https://drive.google.com/file/d/1Ac684nBPLQDritmo-rNw8ZSP0GzCe-as/view?usp=sharing
> If it looks pretty good, I'll submit a PR for it to be added to the Keyman repo.

@LornaSIL Somewhere, where I did not specify, what kind of letter or symbol must to be appeared, appear Latin letters, for example Ralt+L-key. In these cases must not appear any letters or symbols.

**Comment by LornaSIL** [comment]
I am not sure I understand what your comment or request is.  RALT+L does not produce anything. Is it supposed to?

**Comment by tamasbartos** [comment]
> I am not sure I understand what your comment or request is. RALT+L does not produce anything. Is it supposed to?

It might to be a conflict with Ubuntu 20.04 xkbd-data package, or driver conflicts.
The problem is not given on Windows 10.

**Comment by LornaSIL** [comment]
Ok. I will go ahead and submit the keyboard to the Keyman repository. Then, if there are still a few bugs they can be dealt with in a subsequent release. Thanks for your help in getting this keyboard into Keyman for multiple users.
