### ISSUE TITLE
[sil_ethiopic] the help page is not well aligned

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1544]
Boxes are shown inline. It does not look like they are intended.

Link: https://help.keyman.com/keyboard/sil_ethiopic/2.0.3/sil_ethiopic

![image](https://user-images.githubusercontent.com/28331388/117949122-fcc2cf80-b33b-11eb-9877-7e823287cfbd.png)

**Comment by LornaSIL** [comment]
This is still not correct. Sigh.

**Comment by DavidLRowe** [comment]
Looking at https://help.keyman.com/keyboard/sil_ethiopic/2.0.3/sil_ethiopic, I'm not seeing any issues, but you know that script far better than I do!

**Comment by LornaSIL** [comment]
It is improved, not perfect.
