### ISSUE TITLE
[sil_euro_latin] missing info about long press on touch layouts

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1559]
> But it also seems that many (most?) characters are available via long-press. Would it be helpful/possible to include that on the info page?

Original feedback: https://community.software.sil.org/t/suggestion-for-the-sil-eurolatin-keyboard-info-page/4845

**Comment by LornaSIL** [comment]
Add left-hook n to the `n` longpress. Currently it is on `i` which matches the desktop keyboard. We could leave it on `i` and just add it to `n` or remove it from `i`.

https://community.software.sil.org/t/possible-bug-in-eurolatin-keyboard/4951
