### ISSUE TITLE
Lazuri keyboard should be tagged with Latn script

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#156]
Because this keyboard is designed for Latin transcription of the Lazuri language, the language tag should probably include `-Latn`

**Comment by mcdurdin** [comment]
Adding a rider. In the documentation, the links to PDFs should not be prefixed with `file:`

**Comment by darcywong00** [comment]
@mcdurdin can this be closed?

**Comment by DavidLRowe** [comment]
@darcywong00 Yes.
