### ISSUE TITLE
[sil_nubian] Should ⲟ̅ⲩ̅ <2C9F 0305 2CA9 0305> be ⲟ͞ⲩ <2C9F 035E 2CA9>? 

### ISSUE THREAD

**Issue by moyogo** [keymanapp/keyboards#1569]
The "Nubian (SIL)" [sil_nubian] layout produces ⲟ̅ⲩ̅ <2C9F 0305 2CA9 0305> with U+0305 COMBINING OVERLINE over each letter but uses U+0304 COMBINING MACRON on other sequences like, ⲁ̄ <2C81 0304>. While the two U+0305 COMBINING OVERLINE are supposed to connect over both letters, they are typically higher or of different thickness to U+0304 COMBINING MACRON.

Should U+035E COMBINING DOUBLE MACRON be used instead?
It typically covers the previous and the following letter and has the same height and thickness as U+0304 COMBINIG MACRON.

Compare:
ⲟ̅ⲩ̅ <2C9F 0305 2CA9 0305>
ⲟ͞ⲩ <2C9F 035E 2CA9>

**Comment by LornaSIL** [comment]
This is a case where we followed the wishes of the user community. I
believe the codepoints follow what is in the font that goes with the
keyboard.

**Comment by LornaSIL** [comment]
We will stick with the community wishes for now.
