### ISSUE TITLE
balochi_scientific keyboard kmn lists more languages than in the keyboard_info

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#157]
The .kmn lists a number of languages that are not present in the .keyboard_info; these two lists should be consolidated.

**Comment by mcdurdin** [comment]
Adding a rider: in the documentation, the word 'characters' is misspelled. The link to balochi_scientific.pdf should not have the prefix `file:`.

**Comment by DavidLRowe** [comment]
@rmlockwood I need to update the .keyboard_info file (which has `bal`) to match .kmn (which has `bal bgp bcc bgn`). In addition, there's the question of whether these should have `-Latn` added, which would be the case if the language is normally written with Arabic script. Can you comment on the correctness of changing both files to use: `bal-Latn bgp-Latn bcc-Latn bgn-Latn`? Thanks.
