### ISSUE TITLE
Old Hungarian layout for phones too difficult

### ISSUE THREAD

**Issue by tamasbartos** [keymanapp/keyboards#1571]
The Old Hungarian layout for phones 1st and 2nd level too difficult. Sorry, it is our mistake.
@LornaSIL May I replan?

**Comment by LornaSIL** [comment]
You could, of course, take the source files and modify them yourself. Then, you could commit them in a Pull Request to the repo. If you don't feel you can commit them to the repo you could upload them for me to commit.

The other option is to do as you've done before and upload graphics which have the changes needed. However, if you do that, I would ask that you make it VERY clear what is being changed...circled in red or highlighted or something. The last time I had to completely recheck everything because it wasn't clear what had to be modified. Even marking what codepoints are being changed would be helpful to me since I don't use the script.

**Comment by tamasbartos** [comment]
> You could, of course, take the source files and modify them yourself. Then, you could commit them in a Pull Request to the repo. If you don't feel you can commit them to the repo you could upload them for me to commit.
> 
> The other option is to do as you've done before and upload graphics which have the changes needed. However, if you do that, I would ask that you make it VERY clear what is being changed...circled in red or highlighted or something. The last time I had to completely recheck everything because it wasn't clear what had to be modified. Even marking what codepoints are being changed would be helpful to me since I don't use the script.

@LornaSIL 
I'll upload changes the layout for phone devices in graphic file, as soon as possible. I can't understand the source code of keymanapp/keyboards.
The problem was that, in the first plan of layout for phone devices we tried to mix "QWERTZ" style layout with alphabetic order style.
The new plan for phone devices will based only alphabetic order style in 1st and 2nd level. 3rd and 4th level will not changed.

**Comment by tamasbartos** [comment]
@LornaSIL I'm very sorry about huge modifications. I know, You worked hardly. We will not replan the layout in the future, except small corrections, if I wrote wrong Unicode charactercode.
I uploaded the Old Hungarian keyboard plan for phone devices.

Red text and code: replaceable from.
Green text and code:  required letter and its code.
Black text and code: not required to be changed.

Please choose the following font for Old Hungarian layouts:
https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf 
and https://github.com/googlefonts/noto-fonts/tree/main/unhinted/ttf/NotoSans fonts to display letters on keys.
The previously used OldHungarian font from https://oldhungarian.eu have several non-standard letterforms.
![Old Hungarian base layout for phone devices](https://user-images.githubusercontent.com/75836867/122789744-ebb09b00-d2b7-11eb-99f6-c4189c976a43.png)
![Old Hungarian Shifted layout for phone devices](https://user-images.githubusercontent.com/75836867/122789866-0aaf2d00-d2b8-11eb-9c06-91dc43002cd3.png)
![Old Hungarian AltGr-ed layout for phone devices](https://user-images.githubusercontent.com/75836867/122789893-113da480-d2b8-11eb-80b5-c6fdf3ddfa58.png)
![Old Hungarian AltGr+Shift-ed layout for phone devices](https://user-images.githubusercontent.com/75836867/122792423-74303b00-d2ba-11eb-8873-b85c86f34b07.png)
![Old Hungarian layout's spaced line for all level for phone devices](https://user-images.githubusercontent.com/75836867/122792582-9629bd80-d2ba-11eb-8ac6-28cb30f2ce7f.png)

The Desktop layout is work perfectly.

**Comment by LornaSIL** [comment]
At least for this version of the keyboard I'm going to have to stick with the **OldHungarian** font.
The Noto font has two issues that [I've reported](https://github.com/googlefonts/noto-fonts/issues/2102). One is that it has an inconsistent font name (some apps see **Noto Sans OldHung** and some see **Noto Sans Old Hungarian**) and the other is that the Unicode rangebit is not set properly for the supplemental plane (where Old Hungarian is located). This makes it unworkable for Keyman on a touch screen. I'm just seeing tofu (square boxes) with the Noto Sans Old Hungarian font.

**Comment by LornaSIL** [comment]
I don't know what the left pointing arrow and right pointing arrow represent for the last row of the touch layout.

**Comment by tamasbartos** [comment]
> I don't know what the left pointing arrow and right pointing arrow represent for the last row of the touch layout.

The one of the first developer thought, it would be useful built in cursor keys on the spaced line. Forget those, if it not implementable add cursor keys into keyboard for phone devices.

**Comment by tamasbartos** [comment]
@LornaSIL Please upload the test package when it is done.
Arrow keys are cursor keys. If those aren't implementable, forget those!

**Comment by LornaSIL** [comment]
Here's a package you can test: 
https://drive.google.com/file/d/1yAmmEzYFfWVX1wQcg-xyGW1NOMAeJtz6/view?usp=sharing

**Comment by tamasbartos** [comment]
@LornaSIL Thank you for the test version! On the Android and Linux work perfectly. On Windows I did not test yet.

**Comment by LornaSIL** [comment]
I didn't update the desktop keyboard at all, just mobile. So, I've gone and ahead and submitted a PR with the mobile layout changes.
