### ISSUE TITLE
Missing AltGr level keys and deadkeys from Hungarian basic layout 

### ISSUE THREAD

**Issue by tamasbartos** [keymanapp/keyboards#1576]
Missing several keydefinitions and dead keys from Hungarian basic layout, which are in the AltGr level basicly. See the built in layouts on Windows or Linux distributions. On Windows version missing  two dead combination:ľ and ę.

**Comment by LornaSIL** [comment]
Are you talking about this keyboard: https://keyman.com/keyboards/basic_kbdhu ?

The e with ogonek is available by typing `RALT %` plus `e`. I see that it is not documented so we should add that.

U+013E is not in the keyboard as you observed. We imported the keyboard from Windows' keyboard (with permission) so we are following the layout as by Windows. I also just double-checked to see if the keyboard was updated to include that, and it does not include U+013E. Is it possible you are referring to another character? I don't see U+013E used in the CLDR Hungarian exemplar list either.

**Comment by tamasbartos** [comment]
> Are you talking about this keyboard: https://keyman.com/keyboards/basic_kbdhu ?

Yes.

> 
> The e with ogonek is available by typing `RALT %` plus `e`. I see that it is not documented so we should add that.
> 
> U+013E is not in the keyboard as you observed. We imported the keyboard from Windows' keyboard (with permission) so we are following the layout as by Windows. I also just double-checked to see if the keyboard was updated to include that, and it does not include U+013E. Is it possible you are referring to another character? I don't see U+013E used in the CLDR Hungarian exemplar list either.

I tested it in an Android device.
The original Hungarian layout was planned on PC-s with capabilities of Middle Eastern Europe scripting, unfortunately MS forgot Slovak ľ (soft l) and Polish ę. Keyman's implementation has not AltGr capabilities at all on Android, for example I can't tipe $ symbol or ß letter, as Windows' implementation and Linuxes' implementations work.

**Comment by tamasbartos** [comment]
I close it.
