### ISSUE TITLE
gff_tigrinya_eritrea should use ti-ER for its BCP 47 tag

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#158]
Because this keyboard is distinct from gff_tigrinya_ethiopia, it should have the region in the keyboard BCP 47 tag

**Comment by DavidLRowe** [comment]
@mcdurdin So, if I understand correctly, `ti` should change to `ti-ER` in .keyboard_info, and there should be an addition to the .kps file to add `ti-ER` as well.

**Comment by mcdurdin** [comment]
@DavidLRowe, yes that is correct, although the change to the .kps is not strictly necessary until we start deployment of .kmp files to Android/iOS (soon).

**Comment by DavidLRowe** [comment]
closed via #176

**Comment by mcdurdin** [comment]
Small note: in terms of workflow, it's better to close an issue when the PR is merged. You can do this automatically by using certain keywords in a PR comment, for example "fixes #158"

**Comment by mcdurdin** [comment]
I've updated the PR to show this -- you can hover over the word 'fixes' to see the action that will occur when the PR is merged :)
