### ISSUE TITLE
Request for new Mingrelian keyboard

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1581]
Apparently there are two orthographies, so we need separate keyboards for Mingrelian in TR and GE. We may need to adjust the [existing one](https://keyman.com/keyboards/lazuri) (discuss with author HERdilDER Derneği) to make it clear it is for use in Turkey and add a new keyboard for use in Georgia. Since the main language use is in TR the langtag probably remains `lzz-Latn` and the one for GE would be `lzz-Latn-GE`.

https://community.software.sil.org/t/mingrelian-keyboard/4128/17

**Comment by LornaSIL** [comment]
I think the colchis_latin keyboard met this need. The existing `lazuri` one is fine since it supports the Turkey orthography.

**Comment by MakaraSok** [comment]
Technically yes, but there seem to be a bug in the keyboard where the right most keys should not be bigger than others of the same key type.

https://community.software.sil.org/t/mingrelian-keyboard/4128/28

**Comment by LornaSIL** [comment]
Issue #1626 addresses this issue, so this should be closed please.

**Comment by LornaSIL** [comment]
Closed as both keyboards have been created.
