### ISSUE TITLE
Update nrc_makah to use new Andika

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1584]
@eddieantonio I think we could/should update nrc_makah to use the new version of Andika.

* Update the .kps file to include the 3 new typefaces: Italic, Bold, Bold-Italic. They will be in the andika folder once PR #1583 is accepted.
* Bump the version so the package will rebuild.

I'm assuming you will want to do it, but if you prefer me to, I would be happy to do so.

**Comment by eddieantonio** [comment]
@LornaSIL thanks for the update. I would very much appreciate it if you could do this update. Thank you!
