### ISSUE TITLE
[sil_euro_latin] KeymanWeb_KeyHoverColor not defined

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#1591]
In reference to the following blocks from the keyboard's embedded JS:

https://github.com/keymanapp/keyboards/blob/018058f9ef826e1ce0cba76286ea0dddc1cf370a/release/sil/sil_euro_latin/source/sil_euro_latin_js.txt#L80-L86

`KeymanWeb_KeyHoverColor`, so far as I can tell, has _never_ been provided by KeymanWeb.  The last reference to it that I can find in the codebase was in the legacy section of version _2.0_, and even then... it was to a _site-developer supplied_ global that would be used as part of KMW's initialization process.  No default value was given or specified.

As a result, when used on a desktop form-factor within KMW, there's no visual feedback provided to the user when hovering over a possible... "key".  I use "key" loosely there, admittedly.  Users may click the second and third rows of each table in the screenshot below to output the text directly; hovering over those is what triggers related errors.

<img width="1440" alt="Screen Shot 2021-07-06 at 9 55 24 AM" src="https://user-images.githubusercontent.com/25213402/124539250-4b29b180-de47-11eb-91bf-f6ddb7e99dcf.png">

**Comment by mcdurdin** [comment]
Fixed by #1692
