### ISSUE TITLE
font: [aksarabali_panlex] Considerations to use the sans-serif font for the Balinese keyboard

### ISSUE THREAD

**Issue by yogamardia** [keymanapp/keyboards#1603]
Is there any considerations to change the current Vimala font to the new Noto Sans Balinese for the default font for the Balinese Keyboard?

**Comment by LornaSIL** [comment]
Prior discussion was at #1545. We await @kamholz to update the keyboard when he is ready.

**Comment by LornaSIL** [comment]
We await @kamholz since it's his keyboard. If he wants me to update it, I will but not without his agreement.

**Comment by DavidLRowe** [comment]
If @kamholz wishes to change the font, he can reopen this issue (or submit a pull request).
