### ISSUE TITLE
[basic_kbdrum] Fix "c" "C" logic to match source

### ISSUE THREAD

**Issue by hugoncosta** [keymanapp/keyboards#1610]
Hello,

("c" = U+0421. Mapped to s S).

Regarding the Russian Mnemonic keyboard uploaded via #858, the logic with the "c" is not exactly as in Windows 10. I've looked at the code but not entirely sure how to fix it, hope you can help me.

Context:
- When I click on the key for the "c", both keyboards use it as a deadkey which awaits further input. This is a feature of many of the keyboards which have more characters than the latin alphabet.

Logic present on both systems:
- If the next pressed key is one of the pre-configured ones, the first touch is not registered and the second provides the actual character (e.g. s S + c C = щ Щ)

Logic present on Windows 10:
- If the next pressed key is NOT one of the pre-configured ones, the first touch is not registered and the second provides "c" and the other character (e.g. s S + d D = сд СД)

Logic present on the basic_kbdrum
- If the next pressed key is NOT one of the pre-configured ones, the first touch is not registered and the second provides "c" and the other character (e.g. s S + d D = д Д)

Best,

Hugo

**Comment by LornaSIL** [comment]
Thanks for this report. I've just looked at it, and it does seem that the original Windows code was changed from what it should be. I'll see what we can do.
