### ISSUE TITLE
[sundanese] Minor font update

### ISSUE THREAD

**Issue by Ilhamkang** [keymanapp/keyboards#1630]
Dear @LornaSIL, I've made a minor update to the font on the Sundanese keyboard. Please check it.

**Comment by LornaSIL** [comment]
Where is the font?

**Comment by Ilhamkang** [comment]
The font is already included here: https://github.com/Ilhamkang/keyboards/tree/master/release/s/sundanese
Should I create a Pull Request? 

I made this issue in order to make an update because I remembered your comment on the keyboard submission for the Buhid script. It's my bad if misunderstood.

**Comment by DavidLRowe** [comment]
Raising an issue is not wrong. That alerts everyone to a needed change. But it is not necessary if you are planning to submit a pull request.

You'll need to update the version number and copyright date in several files. (We have begun recommending that people include the copyright statement only in the LICENSE.md file and the .kmn file. Similarly the version number is only needed in the HISTORY.md file and the .kmn file. This reduces the number of files that need to be changed when the keyboard is updated.)

Files to check: README.md, HISTORY.md, LICENSE.md and the .kmn file.

Thanks!

**Comment by Ilhamkang** [comment]
Thank you @DavidLRowe! It's clear to me now. 
I will recheck the files.

**Comment by DavidLRowe** [comment]
closed by #1634
