### ISSUE TITLE
rac_khowar keyboard_info description changes

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#164]
Note that the word "Pakistani" should be capitalized. Also, I think the word "linguistic" is supposed to say "linguist".

**Comment by rachitralli** [comment]
@mcdurdin you are right sir

**Comment by rachitralli** [comment]
@mcdurdin sir, please add this message in khowar language in https://keymanweb.com/#khw,Keyboard_rac_khowar 

Example: To enter کھوار (Name of language), 
type        khwar

**Comment by mcdurdin** [comment]
@rachitralli the example text can be added to the .keyboard_info file, in the `example` section for the language, e.g.:
```
"example" : {
        "keys" : "khwar",
        "text" : "کھوار",
        "note" : "Name of language"
      }
```

**Comment by rachitralli** [comment]
@mcdurdin sir, I am unable to find the .keyboard_info file, would you please add the link? so that i can add the relevant information as desired please

**Comment by mcdurdin** [comment]
It should be in your keyboards repository, under `release/r/rac_khowar/rac_khowar.keyboard_info`. Note, you should make sure you update your repository to the latest changes before editing, following the steps below:
```
git checkout master
git fetch upstream
git merge upstream/master
```
