### ISSUE TITLE
Greek Polytonic Unicode Keyboard Issues

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1647]
1. "Ctrl + Alt" doesn't output the expected character. 
![Screen Shot 2021-08-24 at 8 56 56 AM](https://user-images.githubusercontent.com/28331388/130544037-24d459cf-2d03-4d5d-8265-5e4038cd5348.png)

2. "Alt" and "Shift + Alt" don't output the expected character.
![Screen Shot 2021-08-24 at 9 00 58 AM](https://user-images.githubusercontent.com/28331388/130544080-9152a253-5f52-4f8c-852d-8ef5ded555ea.png)

**Comment by LornaSIL** [comment]
If you are talking about this keyboard: https://keyman.com/keyboards/grkpoly2 we do not have permission to update it. It is one of the keyboards in our legacy system and the author does not wish it to be released under MIT.

**Comment by DavidLRowe** [comment]
@LornaSIL Did we ever do this?

**Comment by LornaSIL** [comment]
I finally got around to testing this. If you turn on "Simulate AltGr with Ctrl+Alt" in Configuration then the documentation works as expected. I could either update the help file or the `keyboard_info` file or both. I can't update the Keyman keyboard.
