### ISSUE TITLE
English Keyboard Issues and Feature Requests

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1648]
User's requests:

> Is it possible to have a Keyman keyboard for English that follows these commonly used rules?
> 1. no space before punctuation
> 2. capitalize the next letter after punctuation
> 3. by default <Shift> turns off after one letter. Press twice for all caps.
> I notice that neither the EuroLatin (SIL) or the US Basic keyboards follow these rules. Some people are reluctant to use Keyman for English because of this.

**Comment by tbequette** [comment]
Thanks for posting this.
Point #3 refers to Shift key functionality.

**Comment by mcdurdin** [comment]
Points 2 and 3 are done for sil_euro_latin; point 1 is tracked as a more complex feature in Keyman at keymanapp/keyman#7163. So yes, we can go ahead and close this.
