### ISSUE TITLE
sil_el_ethiopian_latin keyboard_info description notes

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#165]
Via @tombogle: Note that in keyboard_info, the word "Latin" is not capitalized. Also, note the different wording in my DRAFT announcement vs. the wording in the keyboard_info. I was thinking my wording is correct and clearer, but I'm not sure.

From said DRAFT announcement:

"We have published an updated version of the “SIL EL - Ethiopian Latin” keyboard, intended to support keying many Ethiopian languages using Latin-based scripts"

**Comment by DavidLRowe** [comment]
@mcdurdin If I understand this issue, the `description` field in the .keyboard_info file needs to be changed. 

Current:
```
"The \u201cSIL EL - Ethiopian Latin\u201d keyboard is intended to support keying many Ethiopian latin-based scripts."
```

Needed revision:
```
"The \u201cSIL EL - Ethiopian Latin\u201d keyboard is intended to support keying many Ethiopian languages using Latin-based scripts."
```

or perhaps (change "many" to "a number of"):
```
"The \u201cSIL EL - Ethiopian Latin\u201d keyboard is intended to support keying a number of Ethiopian languages using Latin-based scripts."
```

**Comment by mcdurdin** [comment]
@DavidLRowe Yes, that's correct. I like your final suggestion.
