### ISSUE TITLE
Shan (Sil) Keyboard Can't install on IOS

### ISSUE THREAD

**Issue by SZTSIIT** [keymanapp/keyboards#1653]
https://keyman.com/keyboards/sil_shan?bcp47=shn-mymr

After Shan Sil updated can't install on iOS. It doesn't show up when searching for it in the Keyman app. I believe it doesn't work on android as well. 

It said it doesn't support this device. Please see the screenshot here. 

![A86D0134-6B1A-47E1-916B-A6E13AD6B41E](https://user-images.githubusercontent.com/69423986/131280395-28e1d5e5-ee11-4703-a68f-7363f368ebe8.jpeg)

**Comment by LornaSIL** [comment]
`sil_shan` has never had support for mobile devices. I think when you submitted the first issue you were talking about both `shan` and `sil_shan` and we ended up focusing on `sil_shan`. See if the `shan` mobile layout would work for you. 

If you do need `sil_shan` to have a mobile layout, is the desktop layout sufficient or would you like to give us an idea of what the layout should look like?
One strategy I've used is to take the main Burmese characters (circled in red) and put them on the default and shift layers, and then take the digits and punctuation and put them on a 3rd `numeric` layer. That way the keys on a smart phone don't end up too small. 

However, if you want something right away it would maybe need to be a tablet layout that looks exactly like the desktop layout.

![sil_shanD](https://user-images.githubusercontent.com/7071907/131352107-d2930c50-798a-4629-a4ce-97cfcf5c6863.jpg)

**Comment by LornaSIL** [comment]
There's now a tablet layout available here: https://keyman.com/keyboards/sil_shan

**Comment by SZTSIIT** [comment]
@LornaSIL  Thank You, It is the same as what I was about to give you.

**Comment by SZTSIIT** [comment]
@LornaSIL If it is easy to restack I think this is more user-friendly. If not no worry.
![Uploading 27B02578-0C76-4791-886E-68734A4350B2.png…]()

**Comment by SZTSIIT** [comment]
![E990AD64-2018-453E-885E-F870C4B48154](https://user-images.githubusercontent.com/69423986/134079878-2ef4d145-3cfa-4592-b7da-9d05bb3c2f0d.png)
![D3E96237-9F33-411A-8E93-07659C597EEC](https://user-images.githubusercontent.com/69423986/134079879-fd010fae-4bf2-4e11-b830-edd18072507b.png)

**Comment by LornaSIL** [comment]
I'm sorry, but at this point I plan to leave it. I just wanted to make it available. If you wish to update it, you are welcome to!

**Comment by SZTSIIT** [comment]
@LornaSIL Oh, it is ok just leave it then. 😀
