### ISSUE TITLE
It could be happened in near of the future, Unicode Old Hungarian standard would changed

### ISSUE THREAD

**Issue by viktorkiwikovacs** [keymanapp/keyboards#1690]
@LornaSIL This Issue a forecast only. In april, year of 2021 new submission posted to the Unicode, with several additional letters.
I talk about "Old (?) Hungarian" "q", "w", "y", "x", "dz"  "dzs",  "long(?) Rudimenta ue" and number "500".
We’re not happy about it at all, a lot of program lines need to be rewritten.
Now I upload the draft.
[21115-old-hungarian.pdf](https://github.com/keymanapp/keyboards/files/7546236/21115-old-hungarian.pdf)

**Comment by LornaSIL** [comment]
We would only make changes to the keyboard if Unicode approves your request.

**Comment by viktorkiwikovacs** [comment]
@LornaSIL That is not our request. There is a new organization, called "Magyarságkutató intézet" - its name cannot be translated into English. It founded in the year of 2019. More intelligent people know about them, as it is a infamous organization. We hope, the organization will be dissolved at all.

**Comment by LornaSIL** [comment]
Then what is your request for the Keyman repository? This is the Keyman repository, not Unicode.

**Comment by viktorkiwikovacs** [comment]
@LornaSIL I'm sorry!
I were nervous when I first read the Unicode document. 
This problem isn't keyman's case, of course.
I close it!

**Comment by LornaSIL** [comment]
It's okay. I do work with Unicode too and I wondered if you were wanting me to see it (unrelated to Keyman).
