### ISSUE TITLE
Update documentation for itrans_devanagari_hindi

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1691]
Community request: https://community.software.sil.org/t/regarding-long-vowel-r-in-devanagari-phonetic/5576/2

U+0960 is not documented in the welcome.htm file.
The keystrokes to get U+0960 is `RR^`.

**Comment by DavidLRowe** [comment]
@LornaSIL Are there additional undocumented characters? Is this a matter of merely adding a line about typing `RR^` to get U+0960? Or should this character (and perhaps others) be added to the existing table?

**Comment by DavidLRowe** [comment]
Fixed by #2493
