### ISSUE TITLE
[xinaliq] Is there supposed to be S-cedilla on touch layout?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1696]
While investigating keymanapp/keyman#5920 to verify rota keys on the touch layout, I was confused by the rota for <kbd>s</kbd>.

Per help documentation https://help.keyman.com/keyboard/xinaliq/1.1.2/xinaliq#toc-so-we-can-summarize-as-follows-
> “s” 1x = s ; “s” ; 2x = ss ; “s” 3x = ŝ ; “s” 4x = ş ; “s” 5x = s

The 4th "s" should yield `ş`

But in Keyman for Android and Keyman for iPad 14.0, the 4th "s" is yielding
` ̂ ss`. (I manually inserted a space to show the circumflex renders first)

The kmn says
```
's' + 's' > 'ss'            c doubled 's'
'ss' + 's' > 'ŝ'            c circumflex
'ŝ' + 's' > '̂ss'            c circumflex 's' and 's'
'̂ss' + 's' > 's'            c reverts to base character 's'
```

Tagging @KenK-3-21

**Comment by darcywong00** [comment]
```
'ŝ' + 's' > '̂ss'            c circumflex 's' and 's'
```

Turns out the stray circumflex is because the source file is outputting the order:

770     0302     ̂     COMBINING CIRCUMFLEX ACCENT
115     0073     s     LATIN SMALL LETTER S
115     0073     s     LATIN SMALL LETTER S

**Comment by KenK-3-21** [comment]
Hi Darcy,
Yes, you have uncovered an inconsistency in this keyboard. Yes, there
should be an additional rule for s with cedilla. Both are correct. There
happens to be a spelling anomaly - this is the way people have chosen to
spelling ̂ssi the word "brother". I think my oversight was due to the fact
that s with cedilla is part of the keyboard assignments for Azerbaijani
Latin.
Thanks for pointing that out. I guess I need to make the change in Github.
I don't often do that, because I don't submit keyboards on a regular basis.
Blessings, Ken

**Comment by darcywong00** [comment]
> this is the way people have chosen to spelling ̂ssi the word "brother"

1. Is "brother" spelled with "circumflex accent U+005E" instead of "**composing** circumflex accent U+0302"? We could also add an additional rule to "auto-correct" either spelling to the correct one.

2. Where in the `s` rota would you want the cedilla?
```
's' + 's' > 'ss'            c doubled 's'
'ss' + 's' > 'ŝ'            c circumflex
'ŝ' + 's' > '̂ss'            c circumflex 's' and 's'
'̂ss' + 's' > 's'            c reverts to base character 's'
```

We'll want to update the capital-S too.

**Comment by KenK-3-21** [comment]
1.

   Where in the s rota would you want the cedilla?


's' + 's' > 'ss' c doubled 's' 'ss' + 's' > 'ŝ' c circumflex 'ŝ' + 's' >
'̂ss' c circumflex 's' and 's'

here:

'̂ss' + 's' > 'Ş'

's' + 'ş' > s c reverts to base character 's'

Blessings, Ken

**Comment by darcywong00** [comment]
Got it.

> Is "brother" spelled with "circumflex accent U+005E" instead of "composing circumflex accent U+0302"?

Can you clarify the spelling for "brother"? It seems the composing circumflex accent would be confusingly applied to the previous character...
