### ISSUE TITLE
Is there a Remington Gail keyboard layout available for Hindi input?

### ISSUE THREAD

**Issue by kaanchan** [keymanapp/keyboards#1697]
Hi,

Our non-profit has two transcribers who have been inputting Hindi using the [Remington Gail keyboard layout](https://indiatyping.com/index.php/typing-tips/mangal-font-remington-keyboard) for 15+ years. The IMEs we had installed are no longer working/reliable with new OS updates. I searched through the releases folder but couldn't find one. Do you know if the layout exists for Keyman?

Thanks

**Comment by mcdurdin** [comment]
Hi @kaanchan, I have had a look and not found a compatible layout in our collection of Hindi layouts. It seems to be a relatively straightforward layout from what I could [see online](https://typingsansar.com/keyboard/remington-gail-keyboard-layout), so it should be pretty straightforward for you to create one yourself with [Keyman Developer (Windows)](https://keyman.com/developer). It would be awesome then if you are able to [contribute](https://help.keyman.com/developer/keyboards) the finished keyboard to this repository.

**Comment by kaanchan** [comment]
Hi @mcdurdin. Thanks for the reply and confirmation. I'm going to take this on. 

Who or where do you recommend I direct questions if facing challenges customizing the keyboard layout? I'm technically-capable, but I know how much time and frustration can be saved if there are one or more contact points for getting through blocks.

**Comment by kaanchan** [comment]
[MS-Remington.xlsx](https://github.com/keymanapp/keyboards/files/7978496/MS-Remington.xlsx)

The attached spreadsheet documents a basic Remington layout. It should not be considered complete but rather a starting point and completion map.

**Comment by DavidLRowe** [comment]
@kaanchan If you have questions, you can post on this issue (and tag me). If I can't answer your question, I'll direct you to someone else on the team.

**Comment by kaanchan** [comment]
> I did a bit of work on this during a meeting last week. Do you want to start with what I've done and then update it?

@LornaSIL Sure! Is that okay with you? I also have a lot of other projects going on. If you have momentum started and interest in continuing, I'm happy to be QA/feedback. Let me know.

**Comment by LornaSIL** [comment]
Can you email me? My address is lorna underscore evans @ sil dot org
(As soon as you email me I'll delete this comment.)

**Comment by kaanchan** [comment]
References for existing keyboard IME with Remington Gail:
- https://www.microsoft.com/en-in/bhashaindia/downloads.aspx
  - User Guide: https://www.microsoft.com/en-in/images/downloads/Hindi%20Indic%20Input%203-User%20Guide.pdf
    - Hindi Remington (GAIL): section 4.2, pg 5 
  - https://www.microsoft.com/en-in/images/downloads/Hindi%20Indic%20Input%203%2064-Bit.zip
  - https://www.microsoft.com/en-in/images/downloads/Hindi%20Indic%20Input%203%2032-Bit.zip
