### ISSUE TITLE
Add mobile layout for Hieroglyphic

### ISSUE THREAD

**Issue by trosel** [keymanapp/keyboards#1711]
https://github.com/keymanapp/keyboards/tree/master/release/h/hieroglyphic

https://keyman.com/keyboards/hieroglyphic?bcp47=egy-egyp

For some reason this keyboard will not show up as an option in the iOS keyman app :/ 

Any idea why? @LornaSIL

**Comment by LornaSIL** [comment]
It looks like there is not yet a mobile layout for this keyboard. At least
until we can add one. Your only option would be to use the web version.
