### ISSUE TITLE
rac_khowar: Adding English numerals

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#172]
Per comment on #153 by @rachitralli:

@mcdurdin @MakaraSok @LornaSIL thank you very much for uploading my RAC_Khowar Keyboard, please check this link https://keymanweb.com/#khw,Keyboard_rac_khowar

The english numerals i.e. 1234567890 are missing, how can we use english numberals? please help me. thanks

**Comment by rachitralli** [comment]
@MakaraSok sir, you are right that the Arabic numeral has already been added to the Touch Layout, but not on the desktop and web yet. Like Gawar-Bati keyboard I would like to have both the Arabic and english numeral on Keyman Desktop and Keyman Web.

In khowar language we are using both the arabic and english numerals. The english numeral are necessary for counting and texting mobile numbers etc.

**Comment by LornaSIL** [comment]
@rachitralli Where do you want the "English" digits (1234567890) on the desktop keyboard? The default and shift layers are full. Since there is no longpress on the desktop we need to make another kind of rule.

Do you want to type ```##1``` to get "1", ```##2``` to get "2"?

**Comment by rachitralli** [comment]
@LornaSIL I want english digits (1234567890) on the desktop keyboard and online keyboard  https://keymanweb.com/#khw,Keyboard_rac_khowar You are right that the default and shift layers are full. 

I want to type  ##1 to get "1", ##2 to get "2"

In the link  https://keymanweb.com/#khw,Keyboard_rac_khowar please click on Ctrl button and insert 1234567890 the Ctrl is blank and available for working

**Comment by LornaSIL** [comment]
Maybe we should follow how you've done Gawar Bati and Kalasha and put the English digits on the Shift digit keys and move what's on those keys to Ctrl+Alt.

**Comment by DavidLRowe** [comment]
Addressed by #280

**Comment by DavidLRowe** [comment]
(testing automation on project board)
