### ISSUE TITLE
[basic_kbdhebl3] Request to update OSK for AltGr layer

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#1731]
From https://community.software.sil.org/t/hebrew-standard-basic-keyboard/5829

> The keyboard help page correctly describes the symbols available on Desktop for this keyboard:
https://help.keyman.com/keyboard/basic_kbdhebl3/1.0/basic_kbdhebl3
>
>Unfortunately, the onscreen Keyboard for Desktop does not include all the symbols on the AltGr (Right Alt) layer. (The touch layout seems to be missing some symbols, but I haven’t looked into it closely.)
>
>Can the onscreen Keyboard for Desktop be updated?

**Comment by darcywong00** [comment]
Hmm, some of the key caps on the OSK are really tiny!

![image](https://user-images.githubusercontent.com/7358010/151738248-54a294f1-77a9-4e20-8399-f572befb5aa6.png)

**Comment by mcdurdin** [comment]
This is again a font issue. The ideal would be to have a custom font where the marks are enlarged so they are easier to tell apart -- and where they are made into non-spacing, non-shaping marks for rendering on the OSK. I wonder if this is something that WSTech would be willing to look at preparing? It would work in a similar way to the custom KhmerBusraKbd font for khmer_angkor (see #1710) -- putting these non-spacing marks into the PUA to avoid shaping behaviours. Possibly add a dotted circle? @LornaSIL what do you think?

Ref: https://marc.durdin.net/2015/01/how-to-rendering-combining-marks-consistently-across-platforms-a-long-story/

**Comment by LornaSIL** [comment]
Maybe it would just need a better font associated with the keyboard? Currently no font is specified. I'm quite sure we don't have the capacity to create a new Hebrew font. We already do *not* plan to update Ezra SIL, but we could possible use the **Ezra SIL** or **SBL Hebrew** font with this package.

**Comment by DavidLRowe** [comment]
For the hausa_ajami_qwerty keyboard, @LornaSIL used bitmap files for ZWJ, etc. 

Would it be possible to use create images of the keycaps you want for the various Hebrew diacritic marks and include them in the OSK as bitmaps?

**Comment by mcdurdin** [comment]
It's possible specifying an existing font would help, but the differences in rendering across platforms tends to cause grief.

The idea of a custom OSK font is that we copy the glyphs from an existing font. No OpenType data is required. So it's a pretty straightforward process -- the most time consuming part is deciding which codepoints to put the glyphs at. We were able to do it with Lao in about an hour or two.

All that said, it's something I want to become more familiar with, so perhaps I will take a look at the process when I have a spare moment.

**Comment by mcdurdin** [comment]
> Would it be possible to use create images of the keycaps you want for the various Hebrew diacritic marks and include them in the OSK as bitmaps?

I'd prefer not to use bitmaps -- they don't work cross-platform, only on Windows.

**Comment by LornaSIL** [comment]
Fixed by #1732
