### ISSUE TITLE
[sil_mali_qwerty] - Searching for `c:china` brings "Clavier du Mali (Qwerty) keyboard" as result

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyboards#1749]
Why? I wouldn't expect a keyboard of Mali to  be used in a language in China.

**Comment by darcywong00** [comment]
The keyboard_info file includes a "Bu-Nao Bunu" language that is in China.

https://keyman.com/keyboards/sil_mali_qwerty?bcp47=bwx-latn#expand-languages

Should it be removed?

**Comment by LornaSIL** [comment]
Yes, it should be fixed. The list for sil_mali_qwerty is longer than the list for sil_mali_azerty or sil_mali_qwertz (these last two match which languages are supported).

These are in the qwerty keyboard, but not in azerty or qwertz:
bbo (BF is hub)
bwx (CN - definitely delete)
djm (ML)
dtk (ML)
emk (GN is hub)
fuh (NE is hub, does not even list ML)
mlq (SN is hub)
seb (CI is hub)
tmh (ML)
