### ISSUE TITLE
Remove Mingrelian from listed language in sil_euro_latin

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1798]
https://community.software.sil.org/t/mingrelian-keyboard/4128/40
lzz and xmf

**Comment by DavidLRowe** [comment]
Is this a matter of removing xmf (Mingrelian) from the .keyboard_info and .kps files?

Not sure what the reference to lzz is. I'm not seeing that in either file.

Should the "-Latn" be removed from the tags (at least for languages where Latn script is the default)?

Any other changes needed for sil_euro_latin?

**Comment by DavidLRowe** [comment]
I don't think any lexical models will be affected. It seems the only overlap is "en"!

I think these tags need to keep -Latn: 
bgx-Latn, crh-Latn, fub-Latn, fuh-Latn, rmy-Latn, zqe-Latn
I propose removing -Latn from all the rest that have it.

.kps and .keyboard_info have:
"zyg-Nshu" Yang Zhuang
"zyn-Hani" Yongnan Zhuang

langtags has:
zyg = zyg-Hani Yang Zhuang
zyn = zyn-Hani Yongnan Zhuang

Is zyg-Nshu correct? 
Is zyn-Hani correct? Is it typed with Latin characters even though it's not a Latin script?

Is it worth putting all the codes in alphabetical order?

**Comment by LornaSIL** [comment]
There's something wrong with those. I thought we removed them.

**Comment by DavidLRowe** [comment]
Are you suggesting we remove zyg-Nshu and zyn-Hani?

What about putting the codes in alphabetical order? That would generate a lot of changes, but it might make long term maintenance easier.
