### ISSUE TITLE
Hard to use alphabet order like Old Hungarian layout for phones

### ISSUE THREAD

**Issue by soosistvangithub** [keymanapp/keyboards#1810]
@LornaSIL I need to use Old Hungarian layout on phone devices, and it hard to me use alphabet order like layout. Itt would be better, if  as in Latin based Hungarian layout is a QWERTZ layout, Old Hungarian layou would be "GyZsERTZ" layout, extended with several floating buttons with more letters. 
I would plan it. May I? 
The Old Hungarian layout for  desktop is "GyZsERTZ" like, too.  On the desktop is easy to use.

**Comment by LornaSIL** [comment]
So, are you wanting to replace the current mobile layout with a new one? I think that's okay. 

If you want to come up with a new layout, I can update it at some point. For the next month or so I probably cannot actually do the work, but design it and I'll update it when I can.

**Comment by rovasiras** [comment]
@LornaSIL @soosistvangithub 
When the plan is ready, I will look at it and describe my opinion.

**Comment by soosistvangithub** [comment]
@LornaSIL @rovasiras Here you are:
![Old_Hungarian_Phone](https://user-images.githubusercontent.com/104506190/166635388-adbd374b-ead3-4446-926b-9639d43ce601.jpg)

**Comment by soosistvangithub** [comment]
@LornaSIL @rovasiras I'm sorry, I had some mistakes. It's the correct one:
![Old_Hungarian_Phone](https://user-images.githubusercontent.com/104506190/166637915-4374e824-27fc-4e7e-a94f-5e6aea287100.jpg)

**Comment by rovasiras** [comment]
@LornaSIL @soosistvangithub It's a good job, I think. It could be happen, in the 4th layer need modifications. I would be wrote about hidden mistakes, when this layout developed.
I recommend the kende-font font on github: kende-font / kende-font repo.

**Comment by rovasiras** [comment]
@LornaSIL @soosistvangithub I resolved several problem in Kende-font project, and moved it to https://gitlab.freedesktop.org/rovasiras/kende-font

**Comment by rovasiras** [comment]
@LornaSIL The plan OK, but missing U+200E (Left-to-Right mark) called "BJ" (balról jobbra). It should be placed the AltGr+Shift page, to 4th line. The base and shift layers 1st line are the long vowels and special Hungarian vowels in alphabet like order, the other letters follow the "GyZsERTZ" logic. This is tricky, no one confuses the role of the letter "Nikolsburg UE" with the role of the letter "Rudimenta UE" .

**Comment by rovasiras** [comment]
@LornaSIL What's the rule of "K_ " symbols? As you can see, we need 5 lines+ space line. I can to do this by hand, if somewhere is written the  rule of "K_" symbols.
.

**Comment by LornaSIL** [comment]
@soosistvangithub and @rovasiras I'll let you check to see if I got the right characters in place.

**Default**
![image](https://user-images.githubusercontent.com/7071907/167717027-6c051293-d928-4496-a4f9-ee7a37772f9f.png)

**SHIFT**
![image](https://user-images.githubusercontent.com/7071907/167717108-b5a152d9-3ec4-40a6-a79a-1ea72ba0d587.png)

**RALT**
![image](https://user-images.githubusercontent.com/7071907/167717213-62f884a3-4b64-4546-8518-f29c2aeb44fe.png)

**SHIFT RALT**
![image](https://user-images.githubusercontent.com/7071907/167717321-a8478a29-034c-44b6-b696-104e32434c9a.png)

**Comment by rovasiras** [comment]
> @soosistvangithub and @rovasiras I'll let you check to see if I got the right characters in place.
> 
> **Default** ![image](https://user-images.githubusercontent.com/7071907/167717027-6c051293-d928-4496-a4f9-ee7a37772f9f.png)
> 
> **SHIFT** ![image](https://user-images.githubusercontent.com/7071907/167717108-b5a152d9-3ec4-40a6-a79a-1ea72ba0d587.png)
> 
> **RALT** ![image](https://user-images.githubusercontent.com/7071907/167717213-62f884a3-4b64-4546-8518-f29c2aeb44fe.png)
> 
> **SHIFT RALT** ![image](https://user-images.githubusercontent.com/7071907/167717321-a8478a29-034c-44b6-b696-104e32434c9a.png)

@LornaSIL 
Wait please! The Ralt page has a small problem. I'll prepare it, but not immediately!

**Comment by rovasiras** [comment]
@

> @LornaSIL Here is the prepared layout: ![old_hungarian_phone_layout](https://user-images.githubusercontent.com/104506190/167792445-a7b56483-ceec-44e4-8e08-a46f927994f3.jpg)

@soosistvangithub , you forget merge the in spacebutton's atea
@LornaSIL 
I think, it would be better.

**Comment by LornaSIL** [comment]
OK, here is ALT
![image](https://user-images.githubusercontent.com/7071907/167934612-25b1ebee-c12f-44a9-902f-5bbe0190f434.png)

and SHIFT ALT
![image](https://user-images.githubusercontent.com/7071907/167934216-67bfd512-0065-43c8-996a-0eac4a5cf05e.png)

Does that look correct now?

**Comment by soosistvangithub** [comment]
@LornaSIL I'm sorry. I got a mistake: in the underlined position please in **Alt level** replace **201F** code to **204F "⁏"** **(reversed semicolon)** , and in **Alt+shift** level replace **201F** to **2E2E** **(reversed question mark)**
Alt
![OHU](https://user-images.githubusercontent.com/104506190/168004701-3a69e2df-86f0-4167-9c73-8502f430a565.png)
Shift+Alt
![ohushiftalt](https://user-images.githubusercontent.com/104506190/168004727-919082c1-6992-416d-92a5-d346e92b7d6a.png)

Why need Alt button in Shift+Alt level?

**Comment by rovasiras** [comment]
@LornaSIL It will be correct with modifications by @soosistvangithub in https://github.com/keymanapp/keyboards/issues/1810#issuecomment-1124584124 on alt and shift+alt level.

**Comment by LornaSIL** [comment]
The ALT takes you back to the ALT level (not shift-alt). You don't want that?

**Comment by soosistvangithub** [comment]
> The ALT takes you back to the ALT level (not shift-alt). You don't want that?

I understand now. It's a good feature. Did you replace u201F codes in ralt levels to u204F and u2E2E, what I asked? If you did, it can be merged.

**Comment by LornaSIL** [comment]
>Did you replace u201F codes in ralt levels to u204F and u2E2E, what I asked?

Yes, I did that.

**Comment by DavidLRowe** [comment]
Not sure why this didn't close automatically when #1850  was merged.
