### ISSUE TITLE
Deprecated version of Mozhi Malayalam listed

### ISSUE THREAD

**Issue by beniza** [keymanapp/keyboards#1859]
A deprecated version of the Mozhi Malayalam Keyboard is listed on the site
![image](https://user-images.githubusercontent.com/4908971/168747713-ff709860-82b9-41d4-ad0e-6a94763439e9.png)
If it is mandatory to have it there, could you please specify the old one as a deprecated version?

**Comment by DavidLRowe** [comment]
@LornaSIL or @mcdurdin will need to help me out. 
release/m/mozhi_malayalam/mozhi_malayalam.keyboard_info has:
```
"mozhi": { "deprecates": true },
"mozhi_1_1_0": { "deprecates": true },
"mozhi_5_1": { "deprecates": true },
"mozhi51": { "deprecates": true }
```
and each of those legacy mozhi* keyboards has a DEPRECATED.md file, yet the second "Mozhi Malayalam" link in the image points to mozhi_1_1_0. 

How can we avoid listing this deprecated keyboard?

**Comment by mcdurdin** [comment]
Sadly, it's not trivial to remove deprecated keyboard help from the keyboard help index page. Currently, that help page does not reference the keyboard database. It is built from the list of folders on the site, and deprecated keyboards are not identified in the help site data.

This could be opened as an issue at https://github.com/keymanapp/help.keyman.com if you feel it is important enough.

One way to fix this: we'd need to query api.keyman.com on the /keyboards/ page for the list of current keyboards and filter the folder list against it. (It would slow that page even further -- it's already slow to load -- so we may need to look at alternative ways to build the list statically when the keyboard site is updated.)

**Comment by DavidLRowe** [comment]
@mcdurdin Update: currently I'm seeing the deprecated keyboard listed as the first of the two "Mozhi Malayalam" keyboards. Is there a way we can change the display name of the `mozhi_1_1_0` keyboard to be "Mozhi Malayalam (deprecated)"?

**Comment by mcdurdin** [comment]
> Is there a way we can change the display name of the `mozhi_1_1_0` keyboard to be "Mozhi Malayalam (deprecated)"?

Yes, you can edit the file legacy/m/mozhi_1_1_0/source/help/mozhi_1_1_0.php you could change its `$pagename` and `$pagetitle` to do this. That should then be deployed to the help site. That's a good stop-gap for this.

But, as a separate project, it might be good to have the keyboard help deployment add a `DEPRECATED.md` to keyboard help folders that are deprecated (and also to any keyboard help folders it finds that don't have a corresponding currently-published keyboard), and then update help.keyman.com/keyboard/index.php to skip those for the default help index, and list them only in a separate 'deprecated keyboards' index.

**Comment by LornaSIL** [comment]
@mcdurdin I feel like `$pagename` and `$pagetitle` are not what is used for the text on the [help page](https://help.keyman.com/keyboard/). For example this is in the `mozhi_1_1_0`  help file:
```
  $pagename = 'Mozhi Malayalam Keyboard Help';
  $pagetitle = 'Mozhi Malayalam Keyboard Help';
```
But the help page displays **[Mozhi Malayalam](https://help.keyman.com/keyboard/mozhi_1_1_0)**

Is that title picked up from somewhere else?

**Comment by mcdurdin** [comment]
The index page deliberately removes "Keyboard Help" from the title :grin:

```
    if(preg_match('/^(.*)\s+Keyboard\s+Help/i', $title, $sub)) {
      $title = stripslashes($sub[1]);
    }
```

**Comment by LornaSIL** [comment]
@mcdurdin I think we've tidied up ALL of the help files that are in the `keyboards` repo.

However, there are help files for the `fv_*_kmw` files that do appear in the index, but they are only on the help site, eg:

https://help.keyman.com/keyboard/fv_neeaaneegn_kmw

Is it okay for us to add "(deprecated)" to those `*_kmw` php pages? I guess they are in this repo?
`help.keyman.com\keyboard\fv_neeaaneegn_kmw\9.0`

I haven't done in PRs on that repo before.

**Comment by mcdurdin** [comment]
Thank you!!

> Is it okay for us to add "(deprecated)" to those `*_kmw` php pages? I guess they are in this repo?
> `help.keyman.com\keyboard\fv_neeaaneegn_kmw\9.0`

Yes, that's fine. The process is largely the same as with the keyboards repo. If you have write access to the repo, you'll need to create a branch and work on that, otherwise work off a fork.

**Comment by beniza** [comment]
Marc, Lorna, David

It's been a long discussion and I'm not too sure if I understand all the
things that you are discussing here. However if there is something that
requires my attention, kindly let me know by tagging me on your message.

**Comment by LornaSIL** [comment]
@beniza we fixed the issue with the help index page showing two versions of "Mozhi Malayalam". One is now listed as deprecated so it's easy to see which help file is up-to-date.

The other conversion is regarding all the other keyboards that are listed twice so you can ignore this thread now.

**Comment by LornaSIL** [comment]
We believe all the work has been completed to mark deprecated keyboard help files as "(deprecated)". https://help.keyman.com/keyboard/
