### ISSUE TITLE
Request to add + and = to sil_sgaw_karen

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1864]
https://community.software.sil.org/t/can-you-add-sgaw-karen-keyboard/3807/24

We may not want to change functionality, but we could add + and = to the RALT layer perhaps.

**Comment by LornaSIL** [comment]
@MakaraSok can you make this change at the same time as #1866 ?

**Comment by MakaraSok** [comment]
It looks like " and ' are also being requested. Should these four be added or just two above?

**Comment by LornaSIL** [comment]
>It looks like " and ' are also being requested. Should these four be added or just two above?

Yes, that makes sense and I see you did add them.

**Comment by LornaSIL** [comment]
Fixed in #1957
