### ISSUE TITLE
Request to add ' & " and remove extra ဒ on ' and extra ၢၤ on " into Sgaw Karen keyboard Keyman.

### ISSUE THREAD

**Issue by Hexa-Decane** [keymanapp/keyboards#1866]
https://community.software.sil.org/t/can-you-add-sgaw-karen-keyboard/3807/27

I would like to request one thing that make a little bit more difficult using Sgaw Karen Keyboard. We need " & ’ where there is ၢၤ and ဒ in Sgaw karen keyboard because there is ဒ in shift K and for ၢၤ we can just type separately because they put this ၢၤ and ဒ for the convenience purposes only and it was duplicated. Besides, we really need ' & " when typing. Hence, I would like to request to remove extra ဒ and ၢၤ which is beside enter/return in Sgaw Karen Keyman keyboard, and to replace with ' & ". Thank you very much. I really appreciate it.

**Comment by mcdurdin** [comment]
@MakaraSok can you work with Scott Dysart on updating this keyboard per this request?

**Comment by LornaSIL** [comment]
Fixed in #1956
