### ISSUE TITLE
AltGr key is missing from Hungarian Basic layout on touch screens

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1870]
@LornaSIL AltGr (or RALT) key is missing from touch version of "Hungarian Basic" layout, ergo: deadkeys don't work.

**Comment by LornaSIL** [comment]
I think if you do a longpress on the *shift* key you can select the ALT layer. That's not very intuitive, is it. We could perhaps add a RALT key so it's more visible.

**Comment by rovasiras** [comment]
@

> I think if you do a longpress on the _shift_ key you can select the ALT layer. That's not very intuitive, is it. We could perhaps add a RALT key so it's more visible.

Thanks! For beginner keyman users it would be better to add visible RALT key.

**Comment by mcdurdin** [comment]
Just to chime in on this discussion: the basic_kbdxxx keyboards are not optimised for mobile devices, so fixing the unintuitive modifier key is probably not the right answer. There are numerous other problems with using them on mobile devices -- in particular deadkeys, and showing too many keys on each layer (need to sharpen your finger to touch the right key!).

The right answer is to build optimised touch layouts for each keyboard, which sadly is a lot of work! But I am not that keen on piecemeal fixes like adding a RAlt key -- it's the wrong solution.

There's also a question in my mind if it is appropriate to add optimised touch layouts for the basic_kbd series of keyboards, which are designed as 100% compatible clones of the corresponding Windows keyboards. Adding touch layouts causes them to diverge from that. This may be fine but is worth thinking through.
