### ISSUE TITLE
Shift works as Caps Lock on touch layouts.

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1871]
Shift key works as caps-lock in EuroLatin, Hungarian basic and Old Hungarian layouts. I didn't check other layouts.
It would be better, if single click would work as Shift key, double click would work as Caps-lock, as other keyboard project do.

**Comment by rovasiras** [comment]
I close it, because this feature is under the development.

**Comment by mcdurdin** [comment]
Yes, see https://help.keyman.com/developer/language/guide/casing-support
