### ISSUE TITLE
Latvian 	release/basic/basic_kbdlvst layout looks ugly on iphone (using times new roman or smthg) can it be updated? other layouts or ENG looks good

### ISSUE THREAD

**Issue by aintnogeek** [keymanapp/keyboards#1877]

**Comment by LornaSIL** [comment]
Would you be able to give us a screenshot of the ugly and the good keyboard so we know what you are referring to? Is it the font or the layout?

**Comment by aintnogeek** [comment]
![30DF7B13-3EE5-4EF8-A8BB-6FC87A49CAF6](https://user-images.githubusercontent.com/32330904/173739524-07656fb5-7569-4380-87c3-2e2acf9d0cf8.png)

its font that loks from 1998

**Comment by LornaSIL** [comment]
We are not distributing a font with the keyboard so I'm not sure we have control over that. (@mcdurdin ? There's no font setting in `keyboard_info`. Tahoma is selected in `keyman-touch-layout` but this is not Tahoma either.)

**Comment by aintnogeek** [comment]
Is there something that you can change or make fork with other font?

**Comment by LornaSIL** [comment]
The recommendation is to try to remove the reference to the Tahoma font in the `.keyman-touch-layout`. Before deploying we will need to test in both Android and iOS devices to see if this fixes the issue. It would hopefully default to the default font on the device.

We will try to do this, but we cannot commit to a certain time-frame.

**Comment by LornaSIL** [comment]
I removed the reference to the Tahoma font in the `.keyman-touch-layout` and a coworker installed the .kmp on his IPad. This is a screenshot from that test:

![IMG_0387](https://user-images.githubusercontent.com/7071907/178006254-1e66dfa3-0f32-40b2-af40-ce850cdd3832.PNG)

@aintnogeek I don't think the font has changed to what is desired, correct?

**Comment by mcdurdin** [comment]
We are seeing the default font coming through when no font is specified, which is actually a Times New Roman style font on web (the keyboard is a web component). The quickest fix right now may to be include DejaVu Sans with the package and specify it in the keyboard font info in the package metadata. The default font issue for the OSK is a little bigger than we can solve right here. I tested adding DejaVu Sans and installing on an iPhone and that resolved the issue for me.

**Comment by aintnogeek** [comment]
> I removed the reference to the Tahoma font in the `.keyman-touch-layout` and a coworker installed the .kmp on his IPad. This is a screenshot from that test:
> 
> ![IMG_0387](https://user-images.githubusercontent.com/7071907/178006254-1e66dfa3-0f32-40b2-af40-ce850cdd3832.PNG)
> 
> @aintnogeek I don't think the font has changed to what is desired, correct?

I have to check on someones Iphone, because I switched back to Android, and it looks better on Android right now-today.

**Comment by mcdurdin** [comment]
> Will this apply globally on reinstall or on every new install?

If we update the keyboard to include DejaVu Sans, it should fix the issue permanently for this keyboard.

**Comment by aintnogeek** [comment]
> > Will this apply globally on reinstall or on every new install?
> 
> If we update the keyboard to include DejaVu Sans, it should fix the issue permanently for this keyboard.

Than can you please do this? or put at least in long to do list?

**Comment by mcdurdin** [comment]
Done; see #1921. The update will be available in a few hours.

**Comment by DavidLRowe** [comment]
@mcdurdin Do we need to do anything about the other 115 keyboards specifying Tahoma?

**Comment by mcdurdin** [comment]
> @mcdurdin Do we need to do anything about the other 115 keyboards specifying Tahoma?

I think we should address this at a platform level. I'm inclined to leave it until version 17 of Keyman, when we are addressing theming across all platforms (we hope!)

**Comment by DavidLRowe** [comment]
@mcdurdin Will this automatically fall out of the changes you're planning in version 17? Or do we need to open a new issue to track the fact that using Tahoma causes issues on iOS?

**Comment by mcdurdin** [comment]
I think creating a new issue helps us to track that with 17.0.
