### ISSUE TITLE
Custom mobile keyboard layout

### ISSUE THREAD

**Issue by beniza** [keymanapp/keyboards#1902]
I'd like to create a custom keyboard layout for the mobile version of Keyman. Is it possible to do so?

To give an idea, below is the layout we would like to provide for our users
![image](https://user-images.githubusercontent.com/4908971/176632786-a2ec5151-2302-40b2-8885-66e6ef21f462.png)

**Comment by LornaSIL** [comment]
Two comments:
- Certainly you can create a keyboard layout for the mobile version of Keyman. Our preference is that you also include a desktop keyboard because I think we've had issues when we just created a mobile layout. 
- The layout you've included above would be fine, EXCEPT to make sure you still include the `K_LOPT` (world) key on the keyboard as that key is what allows people to change keyboards.

**Comment by beniza** [comment]
Good to know that the creating the custom keyboard layout is possible. On further reading, I found the following articles on Keyman Developer support

  1. https://help.keyman.com/developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic
  2. https://help.keyman.com/developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty

Are they the right place to look for this information?

> What were you expecting the options key to do?

At this point the the [OPTIONS] key is intended for changing keyboards only.

**Comment by mcdurdin** [comment]
> Are they the right place to look for this information?

Apologies for not responding earlier -- I missed the notification on this conversation. Yes, those are good places to start on creating touch layouts. You may also find https://help.keyman.com/developer/15.0/guides/develop/touch-keyboard-tutorial/ useful. Also of course please feel free to ask here or on the [SIL Keyman Community site](https://community.software.sil.org/c/keyman) if you have any implementation questions.

**Comment by DavidLRowe** [comment]
@beniza Feel free to reopen this issue or use the Community site link above if you have further questions.
