### ISSUE TITLE
some vedic accents not visible on downloaded keyman-keyboard

### ISSUE THREAD

**Issue by RumaDewan** [keymanapp/keyboards#1903]
tried various fonts including siddhanta variants.

![image](https://user-images.githubusercontent.com/107683995/176671818-9bdf5519-e726-493b-8647-f090e2211467.png)
![image](https://user-images.githubusercontent.com/107683995/176672033-17c4fcab-3eac-454c-866f-45975f534918.png)

**Comment by LornaSIL** [comment]
The readme file indicates that you need to install the Siddhanta font which is available for download here:
http://svayambhava.blogspot.com/p/siddhanta-devanagariunicode-open-type.html

I checked a few of the characters and they do seem to be in Siddhanta. Also, I found them in Nirmala which is a Windows font.

Hope this helps.

**Comment by mcdurdin** [comment]
It looks like the package could be updated to include the Siddhanta font? Siddhanta font is published under [Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License](http://creativecommons.org/licenses/by-nc-nd/3.0/).

**Comment by LornaSIL** [comment]
Yes, the OSK is requesting **FreeSerif** which doesn't support those characters. We would need to update the font for the OSK.
