### ISSUE TITLE
Keyman Keyboard Sanskrit Vedic Phonetic 1.2.2 - boxes

### ISSUE THREAD

**Issue by RumaDewan** [keymanapp/keyboards#1909]
Ref: https://github.com/keymanapp/keyboards/issues/1903

1.2.2 resolves a lot (over 1.2.1)

there are 5 keys that still show boxes [3 with Rt Alt and 2 with Rt Ctrl]

It seems that these fonts are covered (better with) Nirmala UI.

=======================
screenshots of offline keyboard 1.2.2
![Screenshot 2022-07-06 135317](https://user-images.githubusercontent.com/107683995/177511678-a4a47b58-8f2c-4b91-8b99-149ebfe1f38b.png)

![Screenshot 2022-07-06 135420](https://user-images.githubusercontent.com/107683995/177511716-d87868e6-64c0-43a7-9229-43a60baa3c65.png)
=====================
screenshots of fonts: Nirmala UI vs Siddhanta

![Screenshot 2022-07-06 133929](https://user-images.githubusercontent.com/107683995/177511750-b93fa0be-6342-4861-842a-3bbaa693a23a.png)

![Screenshot 2022-07-06 134224](https://user-images.githubusercontent.com/107683995/177511780-05c57feb-7dfe-4792-a46a-fc418f89823f.png)
===================
screenshot from keyman keyboard help:

![image](https://user-images.githubusercontent.com/107683995/177511928-e099f0e4-fd07-4ebd-aac7-c7e615f2c3ab.png)
![image](https://user-images.githubusercontent.com/107683995/177511948-38c7675f-0ea1-429f-bb7a-beade67286bb.png)
===================
there's only 1 mismatch bw Siddhanta and Nirmala UI and it is with the svastika symbol

![Screenshot 2022-07-06 134052](https://user-images.githubusercontent.com/107683995/177511835-8ae5f24f-d8f9-44ac-9f76-75d64067841f.png)

**Comment by LornaSIL** [comment]
@mcdurdin v1.2.2 of the https://keyman.com/keyboards/itrans_devanagari_sanskrit_vedic keyboard is not available online. The keyboard was revised and rebuilt July 1. Does the build for s.keyman.com need to be kicked off or something?

**Comment by mcdurdin** [comment]
> Does the build for s.keyman.com need to be kicked off or something?

Yes. The deployment does not seem to reliably run at present. Another thing on my list to investigate...

**Comment by mcdurdin** [comment]
OK, it should now be live: https://keymanweb.com/#sa,Keyboard_itrans_devanagari_sanskrit_vedic
