### ISSUE TITLE
font: [itrans_devanagari_sanskrit_vedic] Change font in package

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1910]
#1904 Apparently Siddhanta does NOT have all the characters required for this keyboard.
We cannot distribute Nirmala nor Adishila

Consider including Noto Sans Devanagari instead of Siddhanta:
https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari/about

**Comment by LornaSIL** [comment]
@Shreeshrii I think this is your keyboard. Do you want to use Noto Sans Devanagari instead of Siddhanta since it supports more of the keyboard characters?

**Comment by DavidLRowe** [comment]
@LornaSIL Any action needed on our part?

**Comment by LornaSIL** [comment]
@Shreeshrii I think I'll go ahead and change the font to Noto Sans Devanagari unless I hear differently from you in the next day or two.

**Comment by LornaSIL** [comment]
I checked again. Siddhanta has 0FD5 which isn't in many fonts. It doesn't have a few vedic characters, but Noto Sans Devanagari doesn't have 0FD5 so neither font is perfect. I'll just close this.
