### ISSUE TITLE
Old Hungarian layout's shift key work as capslock

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1934]
@LornaSIL Is it possible, that double click of shift key means Caps-lock, single click works as shift-key?

**Comment by mcdurdin** [comment]
Yes, this is available in Keyman 15. See https://help.keyman.com/developer/language/guide/casing-support for full details on how to enable this in your keyboard layout. 😀

**Comment by rovasiras** [comment]
@mcdurdin Sorry, keyboard on Android doesn't work this feature and I don't know how could be prepare the problem. I do not understand the source code. @LornaSIL helped us before.

**Comment by mcdurdin** [comment]
I understand. I see you've opened up a separate issue at #1935 so let's track this there.
