### ISSUE TITLE
Old Hungarian layout's for Android shift key works as Capslock only.

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1935]
@DavidLRowe In Old Hungarian layout for Android shift key works as caps-lock key. This issue is not about the shift keys globally. It is only layout for Android.

**Comment by mcdurdin** [comment]
Yes, looks like we need to update the keyboard to follow  https://help.keyman.com/developer/language/guide/casing-support now that we actually *have* casing support!

**Comment by LornaSIL** [comment]
I'm not quite sure what you are asking for here. Are you wanting a CAPS layer that stays in the CAPS mode until you click on the default layer key... and then a SHIFT layer that immediately reverts to the unshifted layer after you type the shifted key?

**Comment by rovasiras** [comment]
@LornaSIL I would like that on android works the Old Hungarian layout shift key the following rules:
one click: shift
quick double click: caps-lock
