### ISSUE TITLE
feat(sil_greek_polytonic): more control over sigma and smooth breathing

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1936]
This is a report from Anna via private email to me.

- Sometimes the wrong sigma occurs and can't be fixed without some gymnastics. Could have a forced final-sigma and forced middle-sigma key.

- Putting rough breathing on is very intuitive in Keyman, but I think it's actually easier to type a key each time you want smooth breathing rather than having it automatically added when you don't want it.  Maybe repeat the vowel? eg "aa" -> ἀ.

**Comment by LornaSIL** [comment]
@mcdurdin I don't mind adding a final-sigma (`@s` ?) and middle-sigma (`@S` ?) key. 
However, I don't think we should modify the rough breathing behavior. This keyboard has been around 20 years and that kind of change would be problematical for an unknown number of people.

**Comment by mcdurdin** [comment]
Yes, modifying an existing keyboard is a recipe for trouble. I noted these as issues or features. If we wanted to control rough breathing behaviour, we'd need to have it as an option in the keyboard rather than changing existing behaviour. Not sure if that's a sensible thing to do at this time.

**Comment by DavidLRowe** [comment]
@mcdurdin @LornaSIL Any action needed?

**Comment by mcdurdin** [comment]
I think we should consider creating a new keyboard if this is a real issue, or adding it as a keyboard option in a future keyboard update. I should ask the OP if they still consider this to be a problem.

**Comment by mcdurdin** [comment]
Okay, I've asked the OP

**Comment by mcdurdin** [comment]
Feedback from Anna:

## Sigmas
The reason I suggested a forced σ and forced ς is for editing.  These problems occur:
* If I write ἐστιν (for example), then delete the τ, the σ turns into a ς
* If I go to add a σ into the middle of the word, it adds a ς instead. 

I make mistakes often enough for this to be annoying!

If those behaviours could be fixed, it would be great; otherwise I'd want to use the forced sigmas routinely.

## Breathing:

Problems occur when writing lecture notes and I want to write a vowel in isolation, or write a suffix in isolation (etc), and it automatically puts on a breathing mark.  If there was a way to force a no-breathing vowel, that may be good enough.
