### ISSUE TITLE
[sil_ipa] Make sure "modifier" letters can also be output somehow

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1946]
Currently the "=" is a modifier letter and cannot be output as a single character. You have to type `= ` (equal+space) or two equals and then backspace. We should be able to access "=" and any other modifiers with some sequence like "==" outputting "="

This is a request from a DIU student.

**Comment by DavidLRowe** [comment]
@LornaSIL Is this something we want to do? Does it apply to `<` and `>` also?

**Comment by LornaSIL** [comment]
I never heard back from the student and when I tried to implement it, it got too confusing because we have the "options" setting which makes the keyboard so complicated. I am closing the issue.

**Comment by mcdurdin** [comment]
Sounds good to me.
