### ISSUE TITLE
Old Hungarian layout's webtest makes tofus

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1962]
@LornaSIL 
When I try the Old Hungarian layout for web on Android, it makes tofus. Missing webformat fonts? I upload fontpackage.
[Kende-fonts-web.zip](https://github.com/keymanapp/keyboards/files/9355978/Kende-fonts-web.zip)

@LornaSIL Is it possible to refress fonts later? 
Kende-font under the development. It will have useful syllable-like ligatures.

**Comment by LornaSIL** [comment]
In the future could you change the **filename** from **kende-font.ttf** to **Kende-Regular.ttf**? That would follow industry practice.

**Comment by rovasiras** [comment]
> In the future could you change the **filename** from **kende-font.ttf** to **Kende-Regular.ttf**? That would follow industry practice.

I'm sorry about it. I lost kende-font username's contact e-mail. I'll resolve the problem.

**Comment by rovasiras** [comment]
@LornaSIL  I rebuild the kende-font/kende-font project. The https://github.com/rovasiras/kende-font repo has the Kende.zip, which is a webfont-package.

**Comment by rovasiras** [comment]
@LornaSIL  The kende-font/kende-font is freezed.
The rovasiras/kende-font is the successor of this kende-font/kende-font.

**Comment by rovasiras** [comment]
@LornaSIL Is that all right?

**Comment by rovasiras** [comment]
@LornaSIL I must to prepare the licese text of my kende-font repo. I do it on the next day.
