### ISSUE TITLE
chore: update source files from windows-1252 to utf-8

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1970]
The following .kmn files are stored in windows-1252 code page instead of utf-8. While the compiler does detect this and handles it (it emits a hint), for consistency we should be storing all keyboard sources in utf-8.

- syriac_arabic	
- sil_hebr_grek_trans
- sil_pan_africa_mnemonic
- sil_pan_africa_positional
- sil_yoruba8

**Comment by LornaSIL** [comment]
@mcdurdin we should be able to do this without a version bump...correct?

**Comment by mcdurdin** [comment]
Yes, no version bump required, because it isn't a functional change.

We actually picked this up when testing some work on making the compiler available on Linux and macOS, so it was valuable that these files were not in utf-8 for that reason, but from a repository point-of-view, it's definitely better to be consistent!
