### ISSUE TITLE
[sil_euro_latin] feat: having common punctuation only under a long-press is annoying

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1975]
From a team review of the Keyman for Android UX (keymanapp/keyman#7161)

A number of punctuation characters are available only under a long-press of the <kbd>.</kbd> key. While this is handy in some scenarios, we should consider if they should really also be available in the numeric/punctuation layer, and rarer punctuation characters moved to another layer or onto long-presses themselves.

**Comment by darcywong00** [comment]
fwiw, the same long-press punctuations on the <kbd>.</kbd> are on the default, shift, and numeric layers. (Just not on the currency layer)

**Comment by mcdurdin** [comment]
The issue is more about having to long-press for common punctuation. A layer switch is often faster, particularly as we move more towards start-of-sentence detection, automatic layer switching, and chorded inputs (shift+key together).

**Comment by LornaSIL** [comment]
I don't know how to do this. There are already so many layers it is confusing. Someone would need to give advice.

**Comment by mcdurdin** [comment]
Let's put this together with #1976 as a future development for sil_euro_latin. I would like to tackle it but I am buried very deep...

**Comment by mcdurdin** [comment]
This is addressed by #2520.

**Comment by MakaraSok** [comment]
@Nnyny @Meng-Heng Let's discuss and propose a change to this. We may want to do the same for all other keyboards where applicable. This is a usability issue and we have to try and fix it ASAP.

@bharanidharanj we may need your input on this as well.
