### ISSUE TITLE
[sil_greek_polytonic] Ability to input macron and breve vowel diacritics

### ISSUE THREAD

**Issue by DJ975** [keymanapp/keyboards#1983]
Sometimes I use the Polytonic keyboard to make Ancient Greek notes, and it is important to be able to mark the length of the vowels a, i, u. I cannot find any mention of these two standard vowel diacritics. Long pressing keys don't seem to do anything either.

Is the function currently missing? If so, any plan to add it soon?

**Comment by LornaSIL** [comment]
Sorry for not answering your question! I was out of the office and then haven't managed to catch up.

The _perispomoni_ can be accessed with any of the following (typed after the vowel): SHIFT 6 (`^`), `~`,  `=`. It is font dependent whether it looks like a breve or tilde. Our Galatia SIL font looks like a breve and Gentium Plus looks like a tilde.

It doesn't look like the keyboard has support for the macron. We had not planned to add it. We could add it to SHIFT+3 if that would be helpful. I don't want to change any of the existing keystrokes as the current layout has been used for so many years.

**Comment by DavidLRowe** [comment]
Any action planned on this issue?
