### ISSUE TITLE
bug: khmer_angkor.keyboard_info has font instead of oskFont

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#1996]
Compare the results of https://api.keyman.com/cloud/4.0/keyboards?jsonp=keyman.register&languageidtype=bcp47&version=16.0&keyboardid=sil_jarai&timerid=11 with the corresponding keyboard's .kps definitions:

From the KMW Cloud 4.0 API:
```javascript
/// ...
"font":{"family":"Khmer Busra Kbd","source":["khmer_busra_kbd.ttf"]} // no "oskFont" entry
/// ...
```

https://github.com/keymanapp/keyboards/blob/0fcd24373b35acd6ee8386b351512403407a305e/release/k/khmer_angkor/source/khmer_angkor.kps#L137-L146

```xml
<Keyboard>
  <Name>Khmer Angkor</Name>
  <ID>khmer_angkor</ID>
  <Version>1.3</Version>
  <OSKFont>..\..\..\shared\fonts\khmer\busrakbd\khmer_busra_kbd.ttf</OSKFont>
  <DisplayFont>..\..\..\shared\fonts\khmer\mondulkiri\Mondulkiri-R.ttf</DisplayFont>
  <Languages>
    <Language ID="km">Central Khmer (Khmer, Cambodia)</Language>
  </Languages>
</Keyboard>
```

This is affecting how KMW renders text for corresponding keyboards:

![image](https://user-images.githubusercontent.com/25213402/189812562-755cee96-99f6-424f-901b-8b7b7dfbf877.png)

(Typed via US keys 'sjruk' in order.)

For comparison, everything renders fine on my iPhone while using `khmer_angkor`.  It's KMW that's affected.

**Comment by mcdurdin** [comment]
```
		"oskFont": {
				"family": "Khmer Busra Kbd",
				"source": [
					"khmer_busra_kbd.ttf"
				]
			},
		"font": {
				"family": "Khmer Mondulkiri",
				"source": [
					"Mondulkiri-R.ttf"
				]
			},
```

I think. Note the capital F in `oskFont`!
