### ISSUE TITLE
[sil_euro_latin] Add acute deadkey + j to get j́ for Dutch íj́ 

### ISSUE THREAD

**Issue by moyogo** [keymanapp/keyboards#2002]
The sil_euro_latin and basic_kbdne layouts should allow using the acute deadkey + j to get í for Dutch íj́.

Dutch spelling rules use the acute accent to mark stress on the vowel letter or the first two letters of vowels spelled with more letters.
The vowel digraph ij can be spelled íj when íj́ is not technically possible.
See [Woordenlijst 5.1 Klemtoonteken](https://woordenlijst.org/leidraad/5/1).

The j́ has already been implemented on Android, iOS and macOS Dutch layouts.

**Comment by LornaSIL** [comment]
Thanks @moyogo Do you mean "acute deadkey + j to get j́" (not í)? I think we could (and should) do that for the sil_euro_latin keyboard. 

However, the "basic" keyboards were an import from the Microsoft keyboards (with permission) and we do not plan to enhance them beyond Microsoft's implementation. You would be welcome to submit a new keyboard based on `basic_kbdne`, with this enhancement if you wished. It would need a different filename/keyboard name.

An example of this is the `russian_mnemonic_r` (Russian Mnemonic R) which I believe was based on the Windows `basic_kbdrum` (Russian - Mnemonic Basic).

**Comment by moyogo** [comment]
Thanks @LornaSIL. I changed the title of the issue.
