### ISSUE TITLE
[sil_yi] suppress unsupported Yi languages in language choice menu

### ISSUE THREAD

**Issue by waltersde** [keymanapp/keyboards#2029]
The  SIL Yi keyboard and the Nuosu SIL font, only support the Northern Yi dialect family ii-Yiii, variously called Nuosu Yi, Nosu Yi, Sichuan Yi, Liangshan Yi, Standard Yi. 

When setting up the SIL Yi keyboard, a dropdown menu asks the user to choose their language, and prominently offers a list of languages that use some form of Yi script, with an unsupported variety as the default choice. The default language choice should be ii-Yiii. It could also make sense to allow an "Other" or "Undetermined " language in the list. However, the unsupported languages in the existing list are not relevant and should not be offered as such prominent choices.
![YiScriptLgList](https://user-images.githubusercontent.com/10723437/194904647-c287cd55-bc0f-4c18-8edf-fd74c2e4a0df.PNG)

**Comment by LornaSIL** [comment]
We do list `ii` first so maybe Keyman re-alphabetizes it. Which ones do you want removed?
```
        <Language ID="ii">Sichuan Yi, Nuosu</Language>
        <Language ID="nos">Eastern Nisu</Language>
        <Language ID="nty">Mantsi</Language>
        <Language ID="yig">Wusa Nasu</Language>
        <Language ID="ysn">Sani</Language>
        <Language ID="smh">Samei</Language>
        <Language ID="ywq-Yiii">Wuding-Luquan Yi (Yi)</Language>
        <Language ID="nsd">Southern Nisu</Language>
        <Language ID="nsv">Southwestern Nisu</Language>
        <Language ID="ysd">Samatao</Language>
```
If the keyboard supports a language I would prefer that we keep it listed. If we know it isn't supported then yes we should remove it.

**Comment by waltersde** [comment]
None of the other languages are supported by this keyboard. All should be removed, except for
<Language ID="ii">Sichuan Yi, Nuosu</Language>

Writing system ii-Yiii has adapted a very specific subset of 1,165 Yi script symbols, defined their standard shapes and uses, and assigned them phonemic syllable values that only work for Sichuan/Nuosu Yi. The other Yi language varieties in the list may each use some variant of Yi script, but not this standard one. The phonemics and other writing system conventions of Sichuan Yi will not work for them. The script label "Yiii" should be understood to include a number of overlapping variants of traditional Yi writing in addition to the standardized form used for Sichuan (Nuosu) Yi. The full scope of the Yi script includes many thousands of glyphs and, depending on the region and language variety, they may be written LTR, vertically, or RTL, and glyphs may be rotated or reversed. Hope this clarifies. Thanks.
