### ISSUE TITLE
[gff_amharic] bug: amharic letters in filenames are blocking checkout on macOS

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2058]
The files in release/gff/gff_amharic/source/css-layers/ with Amharic letters are blocking checkout on macOS with the error "error: unable to create file release/gff/gff_amharic/source/css-layers/gff_amharic-layer-popup-𞟠-extra.css: Illegal byte sequence"

Generally, we try to keep all filenames ascii only in the repo to avoid these kinds of problems, as sad as that is.

Can we rename these files?

Tagging @dyacob

**Comment by dyacob** [comment]
Oh... the files within the `css-layers` folder with the Ethiopic letters in the names can be entirely deleted, they are created by the Perl script (`.pl`) in the same directory (coincidently created on a Mac).  Keep the three all ASCII `.css` files in the folder:

```
gff_amharic-layer-popup-default.css
gff_amharic-layer-popup-non-amharic.css
gff_amharic-modifier-keys.css
```

Earlier, I had tried to @import the files into the `gff_amharic.css` style sheet but that wasn't supported.  All of the CSS files in the folder are concatenated together to form the `gff_amharic.css` file instead.  The Ethiopic ones can be simply regenerated so no real need to store them.

FWIW, the file that caused a problem had a Unicode 14 character in it that is in the SMP (U+1E7E0) which I guess some systems are not ready for.  All of the other files are simpler 3-byte UTF-8.  Anyway, feel free to delete them and I'll remember to use ASCII file names in the future if the need arrises.

**Comment by dyacob** [comment]
@mcdurdin would you like me to delete the files and create another PR?  I'm happy to do so, but I'd like to keep the keyboard version number the same if that's ok.

**Comment by mcdurdin** [comment]
Yes thanks that'd be great! It's a repo maintenance PR so no version bump needed
