### ISSUE TITLE
Numpad produce mixed decimal and oldhungarian numbers

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2096]
@LornaSIL Using the Old Hungarian desktop keyboard layout's numpad produce decimal digits mixed with Old Hungarian numbers. I tested on Windows only.
The correct way would be to display decimal numbers at the default level of numpad.

**Comment by LornaSIL** [comment]
Ok. I think it's better not to adjust the numpad with Keyman. You had asked me to add rules for the number pad and maybe we are getting inconsistent results. I'll try to fix that soon.
