### ISSUE TITLE
docs(ekwtamil99uni): "Page not found message" appears after clicking on any Tamil Keyboard Layouts

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyboards#2117]
### Describe the bug

I noticed that in a Tamil keyboard (ekwtamil99uni) after clicking any Keyboard layout link button leads to show an error page. ie., Page not found. 

### Reproduce the bug

1. Install Keyman 15.0.274 from Google Play Store. 
2. Open Keman App. 
3. Click Settings / Install Keyboard or Dictionary option. 
4. Click Install from keyman.com option. 
5. Install Thamizha Tamil99 (ekwtamil99uni) Keyboard. 
6. Verify that the Tamil Keyboard has been installed successfully. 
7. Click Settings / Installed Languages.
8. Click  Tamil Settings. 
9. Open the Help link page. 
10. In the Tamil Welcome page, Click "Further Resources" link button. 
11. Under 'Other Keyboard Layouts for the Tamil language' heading, Click any one of the Tamil keyboard link. 
Here, we noticed that it is opening a page with 'Page not found' error message .

   <img width="300" src="https://user-images.githubusercontent.com/19683143/210383789-0cdee3a3-d75b-4fb7-8220-e252684678a7.jpg">

### Expected behavior

It should open the corresponding help page with details. 

### Related issues
bug(android): Blue Support tab is missing at the bottom of the (Tamil) Help Page. keymanapp/keyman#7973

_No response_

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.274

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro

### Target application

Keyman App

### Keyboard name

Tamil99

### Keyboard version

2.0.3

### Language name

Tamil

**Comment by darcywong00** [comment]
> Hence, they're not available when viewing from an Android device.

Welp, it turns out they don't work on Windows either.
e.g. http://help.keymandesktop.com/go?language=tam&keyboard=Keyboard_ekwunitamil
Maybe a web.config / .htaccess issue?

**Comment by DavidLRowe** [comment]
It seems that the links in the welcome.htm file are wrong / outdated.

For example, the last one is:
`http://help.keymandesktop.com/go?language=tam&keyboard=Keyboard_visual_media_tamil_typewriter`
and perhaps it should be:
`https://help.keyman.com/go?language=ta&keyboard=Keyboard_vm_tamil_typewriter`
 
The site, language tag (`tam` to `ta`) and keyboard name all changed.

And a prior question should probably be should that information be in the welcome.htm file? Or point to the Tamil keyboards home page (https://keyman.com/keyboards/h/tamil) instead?

**Comment by mcdurdin** [comment]
> And a prior question should probably be should that information be in the welcome.htm file? Or point to the Tamil keyboards home page (https://keyman.com/keyboards/h/tamil) instead?

I think pointing directly to keyman.com/tamil is probably best (that redirects to the keyboards/h/tamil page). Other links, particularly to keyboards, will probably change over time, as new keyboards are developed etc.

**Comment by LornaSIL** [comment]
2009 monthly downloads. It's probably important to fix this.

**Comment by LornaSIL** [comment]
@mcdurdin where is the source for this page? https://keyman.com/keyboards/h/tamil/

**Comment by LornaSIL** [comment]
I guess the main `tamil` page is up-to-date, so I think PR#2134 should fix this issue.

**Comment by LornaSIL** [comment]
Fixed by #2134
