### ISSUE TITLE
Discuss mobile keyboard names.

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#213]
Right now when we submit a mobile keyboard, the keyboard name changes to the language name (perhaps from an Ethnologue list?).

For example, the "SIL Nubian" keyboard shows up as "Nobiin" which I believe is one of the languages it is associated with.

The "Jorai" keyboard shows up as "Jarai" which is not actually the preferred name by the people I've been working with on the keyboard.

Is there any way we could change this, either by editing the language list Keyman is using, or by putting it in the keyboard_info file to overwrite the default language name?

**Comment by mcdurdin** [comment]
Right, this is a little difficult to solve at this time. I agree it is not ideal. The language names come from the Keyman API at https://api.keyman.com/cloud/4.0/languages (which themselves are drawn from ISO 639-3, Ethnologue, and BCP 47) and there are often multiple keyboards per language, which makes it hard to know which language name to pick. I think longer term we will move more to a search-based interface like we see at https://keyman.com/keyboards/ which should mitigate the issue. 

For example, see the results we get for https://keyman.com/keyboards?q=jarai . Ideally, localised language names would also be brought in here.

Alternatively, we can start showing all language names including alternates in the list, but it's already a very, very long list!

**Comment by DavidLRowe** [comment]
This issue moved to keymanapp/keyman issues https://github.com/keymanapp/keyman/issues/1000
