### ISSUE TITLE
Urdu Phonetic - ending

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#2130]
A user reports that the [Urdu Phonetic](https://github.com/keymanapp/keyboards/tree/master/release/u/urdu_phonetic) keyboard doesn't work as expected.

> your urdu phonetic keyboard does not make the right texture when written. the ending of the word with حوالہ is ending with the arabic way of writing a text. the urdu way is different

**Comment by LornaSIL** [comment]
The "h" key outputs U+06BE, but the "o" key outputs U+06C1 which is what the user needs to use to get the right key. If there is an issue with the display, then that is a font issue.

I don't consider this a bug in the keyboard.

**Comment by LornaSIL** [comment]
@MakaraSok can this be closed?

**Comment by MakaraSok** [comment]
Let's wait and hear from the user who experiences the issue.
@blackstorm90@gmail.com

**Comment by LornaSIL** [comment]
@MakaraSok can we close this issue?

**Comment by MakaraSok** [comment]
I've just pinged the user again. If we don't hear anything from him in two weeks, let's close it.

**Comment by LornaSIL** [comment]
I think the keyboard is as per design. Closing since we haven't heard back.
