### ISSUE TITLE
chore(fv_all): update fv_all/build.sh to read version metadata from .kmn instead of .kps

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2143]
Problem here is that we use `<FollowKeyboardVersion/>` so Keyman Developer will remove the version number on save from the .kps. So a manual patch here is not going to work long-term. We may need to fixup fv_all/build.sh to read from the .kmp files.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyboards/pull/2141#discussion_r1091329741_

**Comment by darcywong00** [comment]
> We may need to fixup fv_all/build.sh to read from the .kmp files.

Alternatively, could build.sh parse the compiled .keyboard_info files for each fv keyboard to extract the version number?
