### ISSUE TITLE
Old Hungarian layout on desktop works as English layout

### ISSUE THREAD

**Issue by soosistvangithub** [keymanapp/keyboards#2150]
@LornaSIL Old Hungarian layout produce English layout's letter on Windows.

**Comment by rovasiras** [comment]
@LornaSIL More Hungarian users have reported back.

**Comment by LornaSIL** [comment]
We would need more information than this in order to resolve your issue (about the software used, etc). I can type just fine on Windows 11 here (see below) and in Notepad on Windows 11. I'm using Keyman for Windows Version 15.0.274. Do your users have multiple keyboards installed? 
𐲰𐳉 𐳰𐳛𐳪𐳖𐳇 𐳙𐳉𐳉𐳇 .

**Comment by rovasiras** [comment]
@LornaSIL I use Windows 10, and use Windows' buit in latin based Hungarian layout. I'll ask some Hungarians, which keyman version use.

**Comment by mcdurdin** [comment]
I have just tested Old Hungarian on my Win10 computer on latest version of Keyman 16.0.138 and not experiencing any problems. This sounds like a configuration issue. Is it happening to multiple users? Can we get a diagnostic report from a user following the steps at https://help.keyman.com/kb/40?

**Comment by rovasiras** [comment]
@LornaSIL @mcdurdin Now it is working. I don't know why.  I'll ask the other users.

**Comment by rovasiras** [comment]
@LornaSIL @mcdurdin I ran the keyman diagnostics on my Windows. What is the turnaround time for processing?

**Comment by mcdurdin** [comment]
> What is the turnaround time for processing?

We're all volunteers supporting free software here -- there's no support contract or service level! We don't have a turnaround time -- it's just when someone has the capacity to respond.

**Comment by rovasiras** [comment]
@mcdurdin I am sorry, I believed You got the diagnostic report. Technical supporter answered, that "everything al right" and then explained, that I know, how the layout could be choosen.
We installed the Old Hungarian layouts with the Old Hungarian layout's standalone installer.

**Comment by rovasiras** [comment]
@mcdurdin @LornaSIL It seems, this Issue is not the keyboards project problem.

**Comment by soosistvangithub** [comment]
@mcdurdin @LornaSIL @rovasiras I close it.
