### ISSUE TITLE
To Old Hungarian layout need to add capslock option for some keys.

### ISSUE THREAD

**Issue by soosistvangithub** [keymanapp/keyboards#2155]
Need to add for several key the capslock feature in the upper line of the desktop layout, for base level and altgr level, too. The keys are: position of original 1, 2, 3, 4, 5, 6, 7, 8, 9 and the key in the Old Hungarian layout ZWJ.
The decimal numbers shown with altgr+shift keycombination. It would be used easier with capslock+altgr. The xkeyboard-config's Old Hungarian layouts work on this way.

**Comment by LornaSIL** [comment]
@soosistvangithub it would be great if the Old Hungarian community could find someone to learn Keyman and update this keyboard. I'm not able to work on it as often you might wish as I have many responsibilities. Originally I had offered to help with the keyboard, but I didn't know it would be so time consuming to make updates. Someone who knows and uses the script would be most ideal.

**Comment by rovasiras** [comment]
@LornaSIL I'll try it, but not again.

**Comment by rovasiras** [comment]
@LornaSIL I can't to do it.

**Comment by LornaSIL** [comment]
OK, I'll take a look at it, but it may not be until next week as I've got a lot of other things to deal with.

**Comment by LornaSIL** [comment]
Are you wanting me to do this, or are you able to?

**Comment by rovasiras** [comment]
> Are you wanting me to do this, or are you able to?

@LornaSIL Sorry, that I didn't answer yet. I don,t know how works the structure of desktop layout. Please prepare it. I think  @soosistvangithub can't to do this,too. Thanks!

**Comment by LornaSIL** [comment]
I've submitted a new Pull Request that should address the specific keys you mentioned. You might want to look at the changes I made in that PR #2215 so that you can learn how to update the keyboard in the future. 
FYI: There are six stores and then 4 rules to handle what you asked for. If you need to add another character you would add it to all six stores and you wouldn't have to modify the rules.
