### ISSUE TITLE
Change PhonyRus' Layout Type to Mnemonic

### ISSUE THREAD

**Issue by JapanYoshi** [keymanapp/keyboards#2159]
PhonyRus is a mnemonic Russian keyboard layout, but its Layout Type is set to Fixed (Positional), which makes it inconvenient for me, a Dvorak typist.

**Comment by LornaSIL** [comment]
This keyboard was created when we allowed "freeware" as a license. We have not been able to either reach the author or convince him to convert it to the MIT license. Thus, we do not plan to update the keyboard. You would be welcome to submit a new keyboard (with a new id) that meets your needs.
