### ISSUE TITLE
[runeboard] OSK font for ctrl-alt layer?

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2166]
@Runeboard - I was attempting to reproduce the sticky keys issue in keymanapp/keyman#7510 with version 1.1 of [runeboard.kmp](https://downloads.keyman.com/keyboards/runeboard/1.1/runeboard.kmp)

On my Android 13 device, I noticed some of the keys on the "ctrl-alt layer" don't render, even though the output text renders in the Keyman for Android app. (2nd row of K_Q ...)

![runeboard ctrl-alt](https://user-images.githubusercontent.com/7358010/224597765-510f4cf1-ddf2-41e7-b216-cfa92216be0f.jpg)

From the .kps source, I notice the OSK is using Quivira.ttf while the output text is using BabelStoneRunicBeorhtnoth.ttf.
Perhaps Quivira doesn't contain all the characters used on the ctrl-alt layer?

https://github.com/keymanapp/keyboards/blob/ef84d452123278b98f49f20edd95ac688a247d32/experimental/r/runeboard/source/runeboard.kps#L144-L150

**Comment by darcywong00** [comment]
also, the "TM" button on the ctrl-alt layer doesn't output

**Comment by Runeboard** [comment]
Thanks for working on these issues. In particular, thank you for improving the images in the Help section.

I'm intending to update the tablet layout in Version 2 quite substantially so as to remove non-functional keys. Is there a file I should download first to ensure I build upon what you've already done without removing any of your improvements?

Sorry for not being around a lot either. As you may have guessed, I've not a lot of time to spend on here.

**Comment by DavidLRowe** [comment]
[runeboard.zip](https://github.com/keymanapp/keyboards/files/11710699/runeboard.zip)
has the current files from https://github.com/keymanapp/keyboards/tree/master/experimental/r/runeboard
but without the "fonts" folder (omitted from the .zip file because of size). That may help you get your files up-to-date.

**Comment by LornaSIL** [comment]
One other thing that might be good to be aware of, the online help file (https://help.keyman.com/keyboard/runeboard/1.3/runeboard) uses autogenerated keyboard layouts based on your keyboard.

**Comment by Runeboard** [comment]
Thank you both very much.
