### ISSUE TITLE
Old Hungarian fod mobile and tablet on shift level need ZWJ key (Lig)

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2168]
@LornaSIL Old Hungarian layout for mobile devices on shift level needs replace right-to-left key (JB) to ZWJ key ( Lig). It is required for capital ligatures. Right-to-Left key already defined in Alt level, but this is an important key, at the basic and shift level, it should be to the right of the space bar.

**Comment by LornaSIL** [comment]
Hi! Have you started looking for someone who can learn Keyman and keep the keyboard updated? This is simple enough that I can do in a couple of weeks, but ideally you would get someone who can maintain it as you need updates.

**Comment by rovasiras** [comment]
@LornaSIL I think, I can to do it. Now I work on my font called "Roga".

**Comment by rovasiras** [comment]
@LornaSIL Which source file do I need to modify to change the keyboard on tablet and mobile devices?

**Comment by LornaSIL** [comment]
You'll likely need to update all the files in this folder: https://github.com/keymanapp/keyboards/tree/master/release/o/old_hungarian

**Comment by rovasiras** [comment]
> You'll likely need to update all the files in this folder: https://github.com/keymanapp/keyboards/tree/master/release/o/old_hungarian

I'm almost done with the tablet/mobile version. I will do a pull request on Tuesday.

**Comment by rovasiras** [comment]
@LornaSIL The Old Hungarian tablet/mobile version has 10 buttons on each row. It is necessary to reduce one row to 9 buttons in three layers. I adjusted the left padding and the width of the keys, but the last key still appears wider on my tablet. How to adjust the right pading?

**Comment by rovasiras** [comment]
@LornaSIL  Thank You!
