### ISSUE TITLE
Several keyboards have .keyboard_info with custom language codes that should be corrected

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#217]
The language codes recorded for a number of keyboards should be improved now that we have BCP 47 instead of straight ISO 639-3:

- [x] 1. qab should become und-fonipa
  * bu
  * indic roman transliteration
  * ipatotal
  * nw_iranian_latin
  * ipauni111
  * ipa93_km5
- [x] 2. qae should become fr-ca
  * canadian_french
  * canadian_french_legacy
  * canadian_ms
  * european2
- [ ] 3. qaf should become en-US (or eliminated, contrast to en?)
  * dvorak
  * european2
  * us_dvorak
  * us_dvorak_lh
  * us_dvorak_rh
  * us_int
  * us
- [ ] 4. qag should probably be eliminated (es-Latin America) or replaced with country-specific codes
  * european2
  * latin_american
- [x] 5. qah should be replaced with pt-br
  * brazilian_portuguese
  * european2
  * portuguese_abnt
  * portuguese_abnt2
- [x] 6. qai should be eliminated
  * only used with european2

**Comment by darcywong00** [comment]
> 4. qag should probably be eliminated (es-Latin America)...

Per [BCP 47](http://www.rfc-editor.org/rfc/bcp/bcp47.txt) we'd use `es-419`

**Comment by mcdurdin** [comment]
For compatibility reasons we may need to list per country rather than using
a numeric region code. Need to investigate further.

**Comment by darcywong00** [comment]
3. and 4. probably need more discussion so I'm intentionally leaving them outstanding

**Comment by mcdurdin** [comment]
Okay, tested on Windows, and `es-419` works fine but `es-419` is recorded as `redundant` in the [language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry). So no further on really.

**Comment by mcdurdin** [comment]
@darcywong00 do you want to copy items 3 and 4 out of this issue and create a new issue for them so we can close off the completed work here?

**Comment by darcywong00** [comment]
Items 3 and 4 moved to new issue #300 so now we can close this issue.
