### ISSUE TITLE
Old Hungarian layout for mobile has problems on K_SLASH key on default, shift and caps layers

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2176]
@DavidLRowe In the Old Hungarian layout for mobile devices has the following wrong outputs:

on default layer at the position K_SLASH produce hyphen minus (002D) instead of reverse comma (2E41)

on shift and caps layer produce underscore (005F) instead of hyphen minus (002D)

**Comment by rovasiras** [comment]
On the caps layer on position K_SLASH text property is underscore (005F). It's incompatible with shift layer, where the text property is hyphen minus (002D). The hyphen minus is more important.

**Comment by rovasiras** [comment]
@LornaSIL @DavidLRowe  I'll be done soom.

**Comment by LornaSIL** [comment]
Fixed by #2192
