### ISSUE TITLE
For Old Hungarian mobile layout need a floating keyline for punctuation and quotation marks

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2177]
@DavidLRowe @LornaSIL  The tests showed that some punctuation and quotation marks on mobile  devices could be made more easily accessible with a floating keyline.

On the default level long press on the "full stop" (U_002E position) would display, on shift and caps level long press on the "colon" key. (U_003A position)

The keys are (Listed from left to right):

Double low reversed 9 quotation mark u+2E42,
Double high reversed 9 quotation mark u+201F,
Reversed semicolon u+204F,
Colon u+003A,
Exclamation mark u+0021,
Reversed question mark u+2E2E,
Reversed comma u+2E41,
Full stop u+002E

This extension we can't to make, it difficult for us.

**Comment by LornaSIL** [comment]
@rovasiras did you fix this in your recent update? If so, could you close the issue? Thanks!

**Comment by rovasiras** [comment]
> @rovasiras did you fix this in your recent update? If so, could you close the issue? Thanks!

@LornaSIL This issue was not fixed yet. I'll probably be able to do it tomorrow.

**Comment by LornaSIL** [comment]
Fixed by #2194
