### ISSUE TITLE
[fv_australian] yolngu keyboard help page doesn't show up correctly

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#2197]
![image](https://user-images.githubusercontent.com/28331388/235571552-ab1aa19d-e8b9-4703-a07d-b758342d25ee.png)

https://help.keyman.com/keyboard/fv_australian/9.3/fv_australian

**Comment by LornaSIL** [comment]
This looks okay now. I think the code to handle a different order must have fixed it.
