### ISSUE TITLE
bug(ios): [gff_tigrinya_ethiopia] not install on iPad as it was not supposed to

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#2214]
### Describe the bug

| screenshot | description |
| --- | --- |
| <img width="150" src="https://github.com/keymanapp/keyboards/assets/28331388/180a5555-2a0d-4bba-a3f9-f501267b3c01"> | search result from within Keyman for iPad <br> the search cue "tigri" and pick the top one to go to this screen |
| <img width="150" src="https://github.com/keymanapp/keyboards/assets/28331388/1f94b348-9dbf-4945-a365-268df93e1029"> | tap on download for iPad to get to this screen |
| <img width="150" src="https://github.com/keymanapp/keyboards/assets/28331388/d3596dd7-d7e1-42b4-a7a0-a4f7ec81a187"> | tap "Yes, Install Keyboard" to download and install the keyboard and see the error message |

Please note that the keyboard doesn't support Keyman for iPad, but it somehow appears when search for on Keyman for iPad. It however support "Mobile web".

<img width="450" src="https://github.com/keymanapp/keyboards/assets/28331388/ce1b8ab0-4687-4515-a6b8-0ee86e07a3fb">

* https://keyman.com/keyboards/gff_tigrinya_ethiopia

### Reproduce the bug

see the table above

### Expected behavior

if it doesn't support iPhone/iPad, it shouldn't have shown as an option.

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

any

### Operating system

any

### Device

iPad and iPhone 

### Target application

Keyman

### Keyboard name

gff_tigrinya_ethiopia

### Keyboard version

1.3.13

### Language name

Tigringa

### Additional context

The same issue occurs on iPhone 
<img width="150" src="https://github.com/keymanapp/keyman/assets/28331388/a93b2425-4b6a-4563-a473-c76c28c55c6b">

**Comment by darcywong00** [comment]
Transferring to keyboards repo.
I see from the kmn 
https://github.com/keymanapp/keyboards/blob/5aa99608be64de0b737f4877e6eb0acee47c3c59/release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kmn#L24

If it's really for all platforms, the kps file will need to include the compiled .js file. If it's really just for desktops, we should update targets accordingly.

**Comment by LornaSIL** [comment]
@dyacob want to tackle this? It looks like it might just be a matter of adding the .js file to the .kps and bumping the version. If you don't have time I'm willing to give it a go.

**Comment by dyacob** [comment]
@LornaSIL I'd like to tackle this in a few hours.  It is a good opportunity for me to get reacquainted with the keyboard ahead of a bigger update to follow.

**Comment by mcdurdin** [comment]
Hmm, this got addressed before I had a chance to look at one of the underlying issues -- which was that Keyman for iPhone and iPad was listing this when it shouldn't have. The screenshots don't show all the steps involved in getting to the page with the problem; I suspect that this was an issue with the Tigrinya landing page at https://keyman.com/keyboards/h/tigrigna/ listing the keyboard when it wasn't actually available for iOS.

But I don't have a good test case now for this problem, so I am going to assume that that is all it was, rather than a systemic issue from the database.

**Comment by MakaraSok** [comment]
It doesn't look like the issue has been fixed. Try and repro with the steps describe on each row above.

![image](https://github.com/keymanapp/keyboards/assets/28331388/272f7454-d388-4fa3-a8ad-0638a55a204c)

**Comment by dyacob** [comment]
FWIW, I tried installing on an iPad Mini this morning both manually, and via the Keyman website.  No issues were experienced.  On an Android 13 phone, it installs fine via the Keyman website.  The *first* time I switch layers, a popup error message will appear (some text goes outside of the message window), but then doesn't repeat later.  That was a little mysterious.

This keyboard is in need of a significant update to sync with other GFF keyboards, I'll make an effort to do so this weekend.  So some issues may go away, perhaps not the issue shown by @MakaraSok iPhone test.

**Comment by MakaraSok** [comment]
Let's ensure that this issue get fixed ASAP as it's highly visible and affects the usability of the keyboard preventing one from installing the keyboard on their iPhone/iPad.

**Comment by jahorton** [comment]
> FWIW, I tried installing on an iPad Mini this morning both manually, and via the Keyman website.

I'm not getting a reproduction for this issue now.  Granted, it seems that the package installer loaded rather slowly at first - I thought I reproduced it earlier, went to investigate further via iOS simulator... but when I returned to the reproducing device, the package installer was waiting for me.

Could you try again, @MakaraSok ?

**Comment by MakaraSok** [comment]
I've tried both the current latest stable and alpha versions of Keyman on an iPad simulator running iOS 16.4 and the keyboard is indeed installed and can be used as usual. This issue is now closed. Feel free to reopen if it re-emerges.
