### ISSUE TITLE
[khmer_angkor] bug: Long press on the spacebar key shows blank subkey in Khmer Angkor Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyboards#2221]
### Describe the bug

I noticed that an empty subkey appears over the spacebar key, after long pressing the spacebar key. 

### Reproduce the bug

1. Install Keyman 17.0.110-alpha build. 
2. Open Keyman In-App.
3. Download and Install Khmer Angkor Keyboard. 
4. Switch to Khmer Angkor keyboard. 
5. Long press the Spacebar key. 

Here, I noticed that a blank subkey appears over the spacebar key. I did not see the same behavior when I use the default EuroLatin (SIL) keyboard. 

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/fc0c9d0d-5655-4ba6-8038-54c1d76683ce

Note: Able to reproduce it in previous version of keyman 17.0.98-alpha build. 

### Expected behavior

Long press on the space bar key should not show any empty subkey on the keyboard. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0 alpha

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

### Keyboard name

khmer_angkor

### Keyboard version

1.3

### Language name

Khmer

**Comment by LornaSIL** [comment]
Fixed by #2588
