### ISSUE TITLE
Rusyn keboard

### ISSUE THREAD

**Issue by novta** [keymanapp/keyboards#2229]
What is the issue to be fixed with https://github.com/keymanapp/keyboards/pull/2228
I do not have access to TeamCity.
Thanks

**Comment by LornaSIL** [comment]
Thanks for your submission. One of the Keyman team will review the keyboard for any changes that must be made. It may take a few days.

**Comment by DavidLRowe** [comment]
See #2228 to follow progress on the pull request. Closing this issue.
