### ISSUE TITLE
[hieroglyphic] Hieroglyphics keyboard has outdated instructions on Addins

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#225]
Per https://community.software.sil.org/t/display-egyptian-hieroglyphs/766/3, the hieroglyphics keyboard instructions are outdated as they refer to UI elements only present in Keyman 8 and earlier.

**Comment by LornaSIL** [comment]
@andjc has this keyboard on his list of keyboards to move to "release".

**Comment by andjc** [comment]
Do we know whether the Egyptian Hieroglyph Format Controls block will be in the next version of Unicode or a later one?

**Comment by LornaSIL** [comment]
There are not listed for version 11.0.

**Comment by LornaSIL** [comment]
PR #322 fixes this.
