### ISSUE TITLE
[itrans_devanagari_hindi] request for short key for special rendering of 'rya'

### ISSUE THREAD

**Issue by milindchakraborty** [keymanapp/keyboards#2250]
![image](https://github.com/keymanapp/keyboards/assets/64827324/05c31c80-0112-4b70-b42c-f05cd4d829e3)

Unicode supports three forms of 'rya' conjunct in Devanagari, two of which are easily doable in the ITRANS Devanagari Hindi keyboard, the normal **reph rya र्य**, and the eyelash **raphaar rya र्‍य**.
The character sequence for the former, as defined by Unicode, is **Devanagari Ra + VIRAMA + Devanagari Ya**, and for the second one, it is **Devanadari Ra + VIRAMA + ZWJ + YA**.
On the keyboard, the former is a simple **ry** while for the second there is a short key **Ry**, while rule-based **r+y** also works.
The raphaar rya, र्‍य, is used in Marathi and Konkani while there is another form of rya which is used in languages like Rajasthani, Marwari, Braj, etc, **र‍्य**, and has a defined sequence by Unicode as **Devanagari Ra + ZWJ + VIRAMA + YA**.
See the corresponding Unicode proposal, https://www.unicode.org/L2/L2017/17309-rya-devanagari.pdf.
This is rendering correctly if one follows the Unicode rule on the keyboard as **'ra+^y'**, but given how frequently this is used in languages like Rajasthani (for example, past tense of verbs - _karyo, bharyo, dharyo, māryo_, etc.), it slows down typing quite a bit.
I request a short key for this _rya_ like the one we have for _raphaar rya_ as well. I suggest, if **Ry** forms **र्‍य**, let **r+y** form **र‍्य**, or something along the lines of this.
![image](https://github.com/keymanapp/keyboards/assets/64827324/f30a273b-2d03-491a-ac81-1be8b7bcf595)

**Comment by mcdurdin** [comment]
@Shreeshrii: as this is your keyboard, would you like to respond to this feedback?

**Comment by LornaSIL** [comment]
@milindchakraborty  Can you give me the codepoints for what you are asking for? 
![image](https://github.com/keymanapp/keyboards/assets/7071907/11d7bf5d-088a-4d8c-8f69-01eca4d3eba2)

Ra ZWJ VIRAMA YA (U+0930 U+200D U+094D U+092F) 
does not produce that glyph in any of the fonts on my system. Neither does U+0930 U+200D U+094D U+092F U+094D.

**Comment by LornaSIL** [comment]
From the proposal, I guess that is what you want:
![image](https://github.com/keymanapp/keyboards/assets/7071907/f20b06f8-fae6-4e51-9da6-636d7a0f8410)

But, I don't see any fonts following this. I do not wish to change the current behavior of the keyboard. Since you can access this the longer way (`ra+^y`) I would prefer not to change the keyboard.
