### ISSUE TITLE
[gff_tigre, giff_tigrinya_eritrea] broken pdf links

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2254]
These two .php have broken links for .pdf:

* [gff_tigre.php:82](https://github.com/keymanapp/keyboards/blob/cd87f3e2832beb39fa41fc135664a0b5cc18a5a0/release/gff/gff_tigre/source/help/gff_tigre.php#L81)

    ```diff
    -<p>A more complete typing manual is <a target="_blank" href="TigreTyping.pdf">provided as a PDF file</a> with this distribution.</p>
    +<p>A more complete typing manual is <a target="_blank" href="TigreTyping-English.pdf">provided as a PDF file</a> with this distribution.</p>
    ```

* [gff_tigrinya_eritrea.php:82](https://github.com/keymanapp/keyboards/blob/cd87f3e2832beb39fa41fc135664a0b5cc18a5a0/release/gff/gff_tigrinya_eritrea/source/help/gff_tigrinya_eritrea.php#L82)

    ```diff
    -<p>A more complete typing manual is <a target="_blank" href="TigrinyaErTyping.pdf">provided as a PDF file</a> with this distribution.</p>
    +<p>A more complete typing manual is <a target="_blank" href="TigrinyaErTyping-English.pdf">provided as a PDF file</a> with this distribution.</p>
    ```

I note that the corresponding welcome.htm do not have links to the .pdf files. This means that the .pdf files will not be accessible to users except on Windows (due to the Start Menu links, which only work on Windows). You may want to consider adding links to the .pdf for users on other platforms.

**Comment by dyacob** [comment]
PR #2257 corrects the links.  I decided to hold off on adding the links to the welcome.htm files.  I will address this as I push in a minor fix across 6 keyboards in the next day or two.

**Comment by dyacob** [comment]
@mcdurdin I did try adding a link from the welcome.htm , however clinking on the link from the Keyman installer screen that displays the welcome.htm , or from the Keyman Configuration "Help" button gives me this screenshot where it is unable to display the PDF file.  It seems to think the filetype is "chrome-extension".  Then browsing the Microsoft store it finds nothing, so it seems not to recognize the .pdf file extension.

![LinkFromKeymanWelcome](https://github.com/keymanapp/keyboards/assets/8098333/4abe2a8f-8ce1-4c15-9c71-821fc0a1bf48)

**Comment by mcdurdin** [comment]
> Hi @mcdurdin, I did try adding a link from the welcome.htm , however clinking on the link from the Keyman installer screen that displays the welcome.htm , or from the Keyman Configuration "Help" button gives me this screenshot where it is unable to display the PDF file. It seems to think the filetype is "chrome-extension". Then browsing the Microsoft store it finds nothing, so it seems not to recognize the .pdf file extension.

Hmm, that's a new issue for Keyman for Windows. I'd still be adding the link as we'll work to address that, and the link will already work on other platforms.
