### ISSUE TITLE
[fv_tsilhqotin] Suggestion for double consonants and ii

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#226]
User-provided suggestion from [community sites](https://community.software.sil.org/t/tsilhqot-in-keyboard-modification-suggestion/771)

> In the language, there are no instances of double consonants at all; my suggestion would be to adapt the current keyboard in the following way:
ss becomes ŝ
zz becomes ẑ
ww becomes ŵ
and ii becomes ɨ
>
> This would be easy to remember and also easy to type.
>
> Thanks again for all you are doing for marginalized languages of the world.

**Comment by tombogle** [comment]
Of course, you'd need to take into consideration whether this keyboard would ever be used in situations where it might be necessary to type double consonants for things like passwords, URLs, foreign/loan words,  proper names, etc.

**Comment by DavidLRowe** [comment]
@madebybridget This is a suggestion for a change to one of the FV keyboards. It's several years old. I thought I'd bring it to your attention. If you don't think you'll make the change, then I'll close this issue.

**Comment by DavidLRowe** [comment]
@madebybridget If you decide to work on this, you are welcome to reopen the issue.
