### ISSUE TITLE
[old_hungarian] Possibilities?

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2296]
@LornaSIL 
Is it possible, that Old Hungarian layout for mobile devices' Ralt key could be used as Ralt-lock and Ralt-shift key could be used as Ralt-shift-lock?

**Comment by LornaSIL** [comment]
I think you are asking about when clicking on a key on the RALT or RALT
SHIFT layer you want to stay on that layer. Yes, that is possible, but it
must be programmed for each key. Right now it looks like once you press the
key it goes to the default layer. In Developer when you have a key
selected, there should be a setting for "next layer". It probably says
"default". You can change that to "none" and I think it will do what you
want.

**Comment by LornaSIL** [comment]
Can this be closed?
