### ISSUE TITLE
Web Page for GFF Geʾez Keyboard Displays Too Many Platforms

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyboards#2297]
Maybe I've forgotten something here... Checking the Keyman.com page for the GFF Ge'ez keyboard (https://keyman.com/keyboards/gff_geez), it appears to display that most every platform is supported:

<img width="338" alt="Screenshot 2023-07-18 at 8 11 17 AM" src="https://github.com/keymanapp/keyboards/assets/8098333/6a379332-58fb-4136-bac0-f3be9e3255fe">

However, I expected only 4 platforms to be shown as per this line in the `.kmn` file:

`store(&TARGETS) 'windows macosx linux web'`

I did a test install from the Keyman.com on my Android phone, and it does offer the web layout as a mobile platform.  Which is just better than nothing for a mobile keyboard, but I was actually hoping for no mobile offering at all.  I might then restore the touch layout if the web layout will always become a mobile layout anyway.  Or I could remove the `web` target to make the mobile targets go away?  Sorry for the confusion.

**Comment by LornaSIL** [comment]
The web layout does use a .js file, but it's just built on the server. The problem is when it's in the .kmp because then that can be installed on a phone. 

We went through a whole convoluted process of updating .kmp files to remove the .js in the legacy folder one time. Otherwise I may not remember this either.

**Comment by dyacob** [comment]
The recommendation did the trick! Closing.

**Comment by DavidLRowe** [comment]
@mcdurdin : Is there (or, if not, should there be) an issue for Developer: If &Targets doesn't include a mobile target, issue a warning if the .kps file includes a .js file?

**Comment by mcdurdin** [comment]
> Is there (or, if not, should there be) an issue for Developer: If &Targets doesn't include a mobile target, issue a warning if the .kps file includes a .js file?

I've added the converse already in the 17.0 compiler; I was just observing this now as I am comparing outputs from 16.0 and 17.0 compilers. There are quite a few keyboards in the repo that trip over this. I've added a note to warn if a .js file _is_ included at keymanapp/keyman#9090.

**Comment by DavidLRowe** [comment]
Great!
