### ISSUE TITLE
Add help from welcome.htm content

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#231]
Many keyboards are missing online help documentation, but the .kmp files contain `welcome.htm` content that can be used.

Running a script, the list seems to be:

## Legacy Keyboards
- [x] ./legacy/a/acoli/source/acoli.kmp
- [x] ./legacy/a/amazigh_lat.kmn/source/amazigh_lat.kmn.kmp
- [x] ./legacy/a/aramaic/source/aramaic.kmp
- [x] ./legacy/b/bu/source/bu.kmp
- [x] ./legacy/b/buang/source/buang.kmp
- [x] ./legacy/b/bukawa/source/bukawa.kmp
- [x] ./legacy/b/busau/source/busau.kmp
- [x] ./legacy/c/cameroonqwertyunicode50/source/cameroonqwertyunicode50.kmp
- [x] ./legacy/c/creekeysdesktop3/source/creekeysdesktop3.kmp
- [x] ./legacy/c/cs-pinyin/source/cs-pinyin.kmp
- [x] ./legacy/d/deseret/source/deseret.kmp
- [x] ./legacy/d/dvsp/source/dvsp.kmp
- [x] ./legacy/e/esperantohx/source/esperantohx.kmp
- [x] ./legacy/f/farsi_unicode/source/farsi_unicode.kmp
- [x] ./legacy/g/galaxiegreekandhebrew/source/galaxiegreekandhebrew.kmp
- [x] ./legacy/g/gensalish/source/gensalish.kmp
- [x] ./legacy/g/gensalishu/source/gensalishu.kmp
- [x] ./legacy/g/grkpolycompv103/source/grkpolycompv103.kmp
- [x] ./legacy/h/hararab/source/hararab.kmp
- [x] ./legacy/h/hararabalt/source/hararabalt.kmp
- [x] ./legacy/h/harethi/source/harethi.kmp
- [x] ./legacy/h/harethialt/source/harethialt.kmp
- [x] ./legacy/h/harlatn/source/harlatn.kmp
- [x] ./legacy/h/heidelberginputsolution/source/heidelberginputsolution.kmp
- [x] ./legacy/h/hi-keyboard/source/hi-keyboard.kmp
- [x] ./legacy/i/indic roman transliteration/source/indic roman transliteration.kmp
- [x] ./legacy/i/inuktitut_4/source/inuktitut_4.kmp
- [x] ./legacy/k/khowar/source/khowar.kmp
- [x] ./legacy/k/kmhmu/source/kmhmu.kmp
- [x] ./legacy/k/km_cree/source/km_cree.kmp
- [x] ./legacy/k/km_ojibwasyllabics/source/km_ojibwasyllabics.kmp
- [x] ./legacy/k/km_ojicreesyllabics/source/km_ojicreesyllabics.kmp
- [x] ./legacy/k/korda/source/korda.kmp
- [x] ./legacy/k/korean_morse/source/korean_morse.kmp
- [ ] ./legacy/kbd/kbda1/source/kbda1.kmp
- [ ] ./legacy/kbd/kbda2/source/kbda2.kmp
- [ ] ./legacy/kbd/kbda3/source/kbda3.kmp
- [ ] ./legacy/kbd/kbdal/source/kbdal.kmp
- [ ] ./legacy/kbd/kbdarme/source/kbdarme.kmp
- [ ] ./legacy/kbd/kbdarmw/source/kbdarmw.kmp
- [ ] ./legacy/kbd/kbdaze/source/kbdaze.kmp
- [ ] ./legacy/kbd/kbdazel/source/kbdazel.kmp
- [ ] ./legacy/kbd/kbdbash/source/kbdbash.kmp
- [ ] ./legacy/kbd/kbdbe/source/kbdbe.kmp
- [ ] ./legacy/kbd/kbdbene/source/kbdbene.kmp
- [ ] ./legacy/kbd/kbdbgph/source/kbdbgph.kmp
- [ ] ./legacy/kbd/kbdbhc/source/kbdbhc.kmp
- [ ] ./legacy/kbd/kbdblr/source/kbdblr.kmp
- [ ] ./legacy/kbd/kbdbr/source/kbdbr.kmp
- [ ] ./legacy/kbd/kbdbu/source/kbdbu.kmp
- [ ] ./legacy/kbd/kbdbulg/source/kbdbulg.kmp
- [ ] ./legacy/kbd/kbdca/source/kbdca.kmp
- [ ] ./legacy/kbd/kbdcr/source/kbdcr.kmp
- [ ] ./legacy/kbd/kbdcz/source/kbdcz.kmp
- [ ] ./legacy/kbd/kbdcz1/source/kbdcz1.kmp
- [ ] ./legacy/kbd/kbdcz2/source/kbdcz2.kmp
- [ ] ./legacy/kbd/kbdda/source/kbdda.kmp
- [ ] ./legacy/kbd/kbddiv1/source/kbddiv1.kmp
- [ ] ./legacy/kbd/kbddiv2/source/kbddiv2.kmp
- [ ] ./legacy/kbd/kbddv/source/kbddv.kmp
- [ ] ./legacy/kbd/kbdes/source/kbdes.kmp
- [ ] ./legacy/kbd/kbdest/source/kbdest.kmp
- [ ] ./legacy/kbd/kbdfa/source/kbdfa.kmp
- [ ] ./legacy/kbd/kbdfc/source/kbdfc.kmp
- [ ] ./legacy/kbd/kbdfi/source/kbdfi.kmp
- [ ] ./legacy/kbd/kbdfi1/source/kbdfi1.kmp
- [ ] ./legacy/kbd/kbdfo/source/kbdfo.kmp
- [ ] ./legacy/kbd/kbdfr/source/kbdfr.kmp
- [ ] ./legacy/kbd/kbdgae/source/kbdgae.kmp
- [ ] ./legacy/kbd/kbdgeo/source/kbdgeo.kmp
- [ ] ./legacy/kbd/kbdgeoer/source/kbdgeoer.kmp
- [ ] ./legacy/kbd/kbdgeoqw/source/kbdgeoqw.kmp
- [ ] ./legacy/kbd/kbdgkl/source/kbdgkl.kmp
- [ ] ./legacy/kbd/kbdgr/source/kbdgr.kmp
- [ ] ./legacy/kbd/kbdgr1/source/kbdgr1.kmp
- [ ] ./legacy/kbd/kbdgrlnd/source/kbdgrlnd.kmp
- [ ] ./legacy/kbd/kbdhe/source/kbdhe.kmp
- [ ] ./legacy/kbd/kbdhe220/source/kbdhe220.kmp
- [ ] ./legacy/kbd/kbdhe319/source/kbdhe319.kmp
- [ ] ./legacy/kbd/kbdheb/source/kbdheb.kmp
- [ ] ./legacy/kbd/kbdhela2/source/kbdhela2.kmp
- [ ] ./legacy/kbd/kbdhela3/source/kbdhela3.kmp
- [ ] ./legacy/kbd/kbdhept/source/kbdhept.kmp
- [ ] ./legacy/kbd/kbdhu/source/kbdhu.kmp
- [ ] ./legacy/kbd/kbdhu1/source/kbdhu1.kmp
- [ ] ./legacy/kbd/kbdic/source/kbdic.kmp
- [ ] ./legacy/kbd/kbdinasa/source/kbdinasa.kmp
- [ ] ./legacy/kbd/kbdinbe1/source/kbdinbe1.kmp
- [ ] ./legacy/kbd/kbdinbe2/source/kbdinbe2.kmp
- [ ] ./legacy/kbd/kbdinben/source/kbdinben.kmp
- [ ] ./legacy/kbd/kbdindev/source/kbdindev.kmp
- [ ] ./legacy/kbd/kbdinguj/source/kbdinguj.kmp
- [ ] ./legacy/kbd/kbdinhin/source/kbdinhin.kmp
- [ ] ./legacy/kbd/kbdinkan/source/kbdinkan.kmp
- [ ] ./legacy/kbd/kbdinmal/source/kbdinmal.kmp
- [ ] ./legacy/kbd/kbdinmar/source/kbdinmar.kmp
- [ ] ./legacy/kbd/kbdinori/source/kbdinori.kmp
- [ ] ./legacy/kbd/kbdinpun/source/kbdinpun.kmp
- [ ] ./legacy/kbd/kbdintam/source/kbdintam.kmp
- [ ] ./legacy/kbd/kbdintel/source/kbdintel.kmp
- [ ] ./legacy/kbd/kbdinuk2/source/kbdinuk2.kmp
- [ ] ./legacy/kbd/kbdir/source/kbdir.kmp
- [ ] ./legacy/kbd/kbdit/source/kbdit.kmp
- [ ] ./legacy/kbd/kbdit142/source/kbdit142.kmp
- [ ] ./legacy/kbd/kbdiulat/source/kbdiulat.kmp
- [ ] ./legacy/kbd/kbdkaz/source/kbdkaz.kmp
- [ ] ./legacy/kbd/kbdkhmr/source/kbdkhmr.kmp
- [ ] ./legacy/kbd/kbdkyr/source/kbdkyr.kmp
- [ ] ./legacy/kbd/kbdla/source/kbdla.kmp
- [ ] ./legacy/kbd/kbdlao/source/kbdlao.kmp
- [ ] ./legacy/kbd/kbdlt/source/kbdlt.kmp
- [ ] ./legacy/kbd/kbdlt1/source/kbdlt1.kmp
- [ ] ./legacy/kbd/kbdlt2/source/kbdlt2.kmp
- [ ] ./legacy/kbd/kbdlv/source/kbdlv.kmp
- [ ] ./legacy/kbd/kbdlv1/source/kbdlv1.kmp
- [ ] ./legacy/kbd/kbdmac/source/kbdmac.kmp
- [ ] ./legacy/kbd/kbdmacst/source/kbdmacst.kmp
- [ ] ./legacy/kbd/kbdmaori/source/kbdmaori.kmp
- [ ] ./legacy/kbd/kbdmlt47/source/kbdmlt47.kmp
- [ ] ./legacy/kbd/kbdmlt48/source/kbdmlt48.kmp
- [ ] ./legacy/kbd/kbdmon/source/kbdmon.kmp
- [ ] ./legacy/kbd/kbdmonmo/source/kbdmonmo.kmp
- [ ] ./legacy/kbd/kbdne/source/kbdne.kmp
- [ ] ./legacy/kbd/kbdnepr/source/kbdnepr.kmp
- [ ] ./legacy/kbd/kbdno/source/kbdno.kmp
- [ ] ./legacy/kbd/kbdno1/source/kbdno1.kmp
- [ ] ./legacy/kbd/kbdpash/source/kbdpash.kmp
- [ ] ./legacy/kbd/kbdpl/source/kbdpl.kmp
- [ ] ./legacy/kbd/kbdpl1/source/kbdpl1.kmp
- [ ] ./legacy/kbd/kbdpo/source/kbdpo.kmp
- [ ] ./legacy/kbd/kbdro/source/kbdro.kmp
- [ ] ./legacy/kbd/kbdropr/source/kbdropr.kmp
- [ ] ./legacy/kbd/kbdrost/source/kbdrost.kmp
- [ ] ./legacy/kbd/kbdru/source/kbdru.kmp
- [ ] ./legacy/kbd/kbdru1/source/kbdru1.kmp
- [ ] ./legacy/kbd/kbdsf/source/kbdsf.kmp
- [ ] ./legacy/kbd/kbdsg/source/kbdsg.kmp
- [ ] ./legacy/kbd/kbdsl/source/kbdsl.kmp
- [ ] ./legacy/kbd/kbdsl1/source/kbdsl1.kmp
- [ ] ./legacy/kbd/kbdsmsfi/source/kbdsmsfi.kmp
- [ ] ./legacy/kbd/kbdsmsno/source/kbdsmsno.kmp
- [ ] ./legacy/kbd/kbdsorex/source/kbdsorex.kmp
- [ ] ./legacy/kbd/kbdsorst/source/kbdsorst.kmp
- [ ] ./legacy/kbd/kbdsp/source/kbdsp.kmp
- [ ] ./legacy/kbd/kbdsw/source/kbdsw.kmp
- [ ] ./legacy/kbd/kbdsw09/source/kbdsw09.kmp
- [ ] ./legacy/kbd/kbdsyr1/source/kbdsyr1.kmp
- [ ] ./legacy/kbd/kbdsyr2/source/kbdsyr2.kmp
- [ ] ./legacy/kbd/kbdtajik/source/kbdtajik.kmp
- [ ] ./legacy/kbd/kbdtat/source/kbdtat.kmp
- [ ] ./legacy/kbd/kbdth0/source/kbdth0.kmp
- [ ] ./legacy/kbd/kbdth1/source/kbdth1.kmp
- [ ] ./legacy/kbd/kbdth2/source/kbdth2.kmp
- [ ] ./legacy/kbd/kbdth3/source/kbdth3.kmp
- [ ] ./legacy/kbd/kbdtiprc/source/kbdtiprc.kmp
- [ ] ./legacy/kbd/kbdtuf/source/kbdtuf.kmp
- [ ] ./legacy/kbd/kbdtuq/source/kbdtuq.kmp
- [ ] ./legacy/kbd/kbdturme/source/kbdturme.kmp
- [ ] ./legacy/kbd/kbdughr/source/kbdughr.kmp
- [ ] ./legacy/kbd/kbduk/source/kbduk.kmp
- [ ] ./legacy/kbd/kbdukx/source/kbdukx.kmp
- [ ] ./legacy/kbd/kbdur/source/kbdur.kmp
- [ ] ./legacy/kbd/kbdur1/source/kbdur1.kmp
- [ ] ./legacy/kbd/kbdus/source/kbdus.kmp
- [ ] ./legacy/kbd/kbdusa/source/kbdusa.kmp
- [ ] ./legacy/kbd/kbdusl/source/kbdusl.kmp
- [ ] ./legacy/kbd/kbdusr/source/kbdusr.kmp
- [ ] ./legacy/kbd/kbdusx/source/kbdusx.kmp
- [ ] ./legacy/kbd/kbduzb/source/kbduzb.kmp
- [ ] ./legacy/kbd/kbdvntc/source/kbdvntc.kmp
- [ ] ./legacy/kbd/kbdyak/source/kbdyak.kmp
- [ ] ./legacy/kbd/kbdycc/source/kbdycc.kmp
- [ ] ./legacy/kbd/kbdycl/source/kbdycl.kmp
- [x] ./legacy/l/laounicodebasic_on_thaikbd/source/laounicodebasic_on_thaikbd.kmp
- [x] ./legacy/l/lingfilsemitica/source/lingfilsemitica.kmp
- [ ] ./legacy/l/lushootseed/source/lushootseed.kmp
- [ ] ./legacy/m/moore/source/moore.kmp
- [ ] ./legacy/m/mozhi/source/mozhi.kmp
- [ ] ./legacy/m/mozhi51/source/mozhi51.kmp
- [ ] ./legacy/m/multi pak/source/multi pak.kmp
- [ ] ./legacy/n/naskeysdesktop/source/naskeysdesktop.kmp
- [ ] ./legacy/n/ndailu keyman keyboard/source/ndailu keyman keyboard.kmp
- [ ] ./legacy/p/persian11/source/persian11.kmp
- [ ] ./legacy/p/phoneticarabic/source/phoneticarabic.kmp
~[ ] ./legacy/p/phonyrus/source/phonyrus.kmp~Already exists
- [ ] ./legacy/p/pokhto/source/pokhto.kmp
- [ ] ./legacy/r/russian-tajik/source/russian-tajik.kmp
- [ ] ./legacy/s/sabdalipi assamese/source/sabdalipi assamese.kmp
- [ ] ./legacy/s/sipon phonetic sinhala/source/sipon phonetic sinhala.kmp
- [ ] ./legacy/t/tchadunicode_with_charis_fonts/source/tchadunicode_with_charis_fonts.kmp
- [ ] ./legacy/t/thamizha anjal/source/thamizha anjal.kmp
- [ ] ./legacy/t/thamizha bamini/source/thamizha bamini.kmp
- [ ] ./legacy/t/thamizha tamil99/source/thamizha tamil99.kmp
- [ ] ./legacy/t/thamizha typewriter/source/thamizha typewriter.kmp
- [x] ./legacy/t/thompsonu/source/thompsonu.kmp
- [x] ./legacy/t/tunisianspokenarabic/source/tunisianspokenarabic.kmp
- [x] ./legacy/t/turkmen/source/turkmen.kmp
- [x] ./legacy/u/urdu ph - package/source/urdu ph - package.kmp
~[ ] ./legacy/v/venetian/source/venetian.kmp~ Already exists
- [x] ./legacy/w/waiwai/source/waiwai.kmp
- [x] ./legacy/w/wiwa/source/wiwa.kmp

## Release Keyboards
~[ ] ./release/sil/sil_ipa/build/sil_ipa.kmp~ Added in #207 

## Questions
* Are these different versions of ./legacy/m/mozhi_1_1_0?
- [ ] ./legacy/m/mozhi/source/mozhi.kmp
- [ ] ./legacy/m/mozhi51/source/mozhi51.kmp
* Is this the same as ./legacy/e/ekwnewtwuni.kmp?
- [ ] ./legacy/t/thamizha typewriter/source/thamizha typewriter.kmp
* Is this the same as visual_media_tamil_x.kmp? (modular and typewriter)
- [ ] ./legacy/t/tamil - visual media/source/tamil - visual media.kmp

------
For keyboards that contain `welcome.htm` in the .kmp file, convert them to `help/[keyboardID].php` so they'll deploy to help.keyman.com

**Comment by DavidLRowe** [comment]
see issue #237

**Comment by LornaSIL** [comment]
The remaining ones where we do have sufficient documentation to create help files are:
tamil - visual media
thamizha anjal
thamizha bamini
thamizha typewriter
gff_ethiopic_7
gff_amh_powerpack_7

**Comment by LornaSIL** [comment]
gff_ethiopic_7 doesn't have good documentation so I cannot do it or gff_amh_powerpack_7 becaise the powerpack depends on gff_ethiopic_7 documentation.

We did not create help files for the deprecated Windows Basic keyboards.

I believe all the help files we can do are done.
