### ISSUE TITLE
[old_hungarian] on Windows produce latin letter

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2313]
Since the version is updated, it produce latin letters again.

**Comment by rovasiras** [comment]
> @rovasiras Can you supply more details?
> 
> The `old_hungarian` keyboard was updated to version 1.7.2 in May 2023. Is this the change to which you refer?
> 
> Can you give an example of what is not working as you expect?

The last version is 1.7.4

I deinstalled it and reinstall again. It works now. This kind of bug already was before.

**Comment by LornaSIL** [comment]
If it's working now, I think it's not the keyboard. I'll close it. Feel free to reopen if it remains a problem.
