### ISSUE TITLE
Deprecations for `fv_xxx_kmw`

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#2314]
Relates to #2312 

@mcdurdin I'm not quite sure what to do about these deprecations (all the `_kmw` ones). I don't see the keyboards in our repo anymore. (Deleting the `_kmw` and deprecations were done with this commit `Commit: cacd6dc7dcfdcb05c09a0539f548294c2d758d61 [cacd6dc]` on Nov 5, 2018)

This doesn't exist: https://keyman.com/keyboards/fv_hulquminum_kmw

But this does:
https://keyman.com/keyboards/fv_hulquminum

And that last one deprecates `fv_hulquminum_kmw` but there is no link since it doesn't exist. So, I was thinking I would remove all the deprecations to the `_kmw` files since they are no longer in the repo. BUT the help file still exists:
https://help.keyman.com/keyboard/fv_hulquminum_kmw/9.0/fv_hulquminum_kmw

I could remove all the deprecations in the `keyboard_info` files, but it still leaves all those help files.

**Comment by mcdurdin** [comment]
The deprecations should remain, even if the old keyboard is no longer in repo. This supports existing users who will then be able to have their keyboards upgraded to the new one if they ask to update the old one.

In the same way, we keep the documentation to support existing users. We _could_ do ahead and remove old documentation but there's little value in doing so, and some marginal benefit for the possibility than an existing user will access it.

**Comment by LornaSIL** [comment]
@mcdurdin says not to delete them so this can be closed.
