### ISSUE TITLE
[old_hungarian]Missing decimal comma from Old Hungarian layouts

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2353]
When decimal numbers are used, it was the best choice to add decimal comma.

**Comment by rovasiras** [comment]
@LornaSIL I try to resolve this problem, but I don't know that I could prepare it on desktop layouts. The xkeyboard-config has a merge request already.

**Comment by LornaSIL** [comment]
> I try to resolve this problem, but I don't know that I could prepare it on desktop layouts. The xkeyboard-config has a merge request already.

Can you provide a link to the xkeyboard-config request?

**Comment by rovasiras** [comment]
> > I try to resolve this problem, but I don't know that I could prepare it on desktop layouts. The xkeyboard-config has a merge request already.
> 
> Can you provide a link to the xkeyboard-config request?

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/618/diffs

**Comment by rovasiras** [comment]
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/620/diffs
