### ISSUE TITLE
chore: publish static .keyboard_info for legacy/ folder 🎺

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2354]
The legacy/ folder needs to update all .keyboard_info files to include the full published .keyboard_info files (taken from downloads.keyman.com), which we will then use in the build in the future. kmc will not generate .keyboard_info files for legacy/ folder, so if we do make changes to packages there, we'll need to manually update the corresponding .keyboard_info.

This is because kmc will generate .keyboard_info for release/ and experimental/ keyboards entirely from the source data, and the legacy/ folder, being essentially static, will not have all the data inside .kmp files that we need.

**Comment by LornaSIL** [comment]
@mcdurdin do you want me to do this or will you run a script that does it?

**Comment by mcdurdin** [comment]
I am going to do it with a script (or extraction directly from downloads site)
