### ISSUE TITLE
[old_hungarian] There are freq. used ligs in Kende font

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2358]
@LornaSIL There are new, frequently used litarutes in the https://github.com/rovasiras/kende-font
Please update it.

**Comment by LornaSIL** [comment]
I'm assuming you updated the Kende.ttf font for the new version. It looked like it. The reason that the one in `web` was deleted is that there was also the one in `source`. They were the same version so it wasn't required in two locations. @DavidLRowe was able to make those changes for me so don't try to merge the PR I submitted yesterday to your repo. We think we can approve it once the online build completes.

**Comment by rovasiras** [comment]
@LornaSIL thanks for your job!
