### ISSUE TITLE
[web] dlia25bas does not appear to work correctly at keymanweb.com

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#236]
Only the keys with 'special' characters work - the basic alphanumeric and punctuation don't.

https://keymanweb.com/#dib,Keyboard_dlia25bas

It's not clear whether this keyboard should even be available; has it been replaced with el_dinka yet?

**Comment by MakaraSok** [comment]
@mcdurdin the el_dinka doesn't support web.

**Comment by andjc** [comment]
dlia25bas was only ever developed for Windows.  It is a minimal mnemonic layout that picks up non modified characters/key output from underlying windows keyboard.

It is an ancient design. Never developed for Web.

**Comment by mcdurdin** [comment]
I'd like to see the existing dlia25bas recompiled if possible just to give a stopgap until we have a better Dinka solution for web. It should work okay on desktop devices.

**Comment by andjc** [comment]
I'm woring on an update to el_dinka this week. dlia25bas would be exactly the same as current el_dinka. 

The new version is based on more recent code and is cross platform.

**Comment by DavidLRowe** [comment]
@andjc If I understand correctly, your pull request for el_dinka will include changes to deprecate dlia25bas, and then this issue can be closed.

**Comment by andjc** [comment]
@DavidLRowe correct. The updated el_dinka will deprecate dlia25bas.

**Comment by andjc** [comment]
@DavidLRowe correct. The updated el_dinka will deprecate dlia25bas and issue can be closed.

**Comment by LornaSIL** [comment]
Fixed by #388
