### ISSUE TITLE
[old hungarian] [mobile layouts] please follow the linked plan

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2371]
@LornaSIL Please follow your plan:
https://github.com/keymanapp/keyboards/issues/2361#issuecomment-1725737822

Thanks

**Comment by LornaSIL** [comment]
@mcdurdin interestingly the help file shows the keystrokes as designed: https://help.keyman.com/keyboard/old_hungarian/1.7.6/old_hungarian (mobile layout, the bottom 3 longpress keys). 
![image](https://github.com/keymanapp/keyboards/assets/7071907/0840759b-d0b7-4f4c-93d1-3f104d107c55)

They also work when testing with Keyman Developer on the web. 

I did not get a notification that the keyboard had been updated. So, I uninstalled and installed the new version on my android. When I installed the keyboard on my android phone I'm getting these keys (bottom right):
![image](https://github.com/keymanapp/keyboards/assets/7071907/c29991d1-c60f-4785-baa1-cee43d6c364d)

Has the build system gotten mixed up?

**Comment by rovasiras** [comment]
> @mcdurdin interestingly the help file shows the keystrokes as designed: https://help.keyman.com/keyboard/old_hungarian/1.7.6/old_hungarian (mobile layout, the bottom 3 longpress keys). ![image](https://user-images.githubusercontent.com/7071907/269341110-0840759b-d0b7-4f4c-93d1-3f104d107c55.png)
> 
> They also work when testing with Keyman Developer on the web.
> 
> I did not get a notification that the keyboard had been updated. So, I uninstalled and installed the new version on my android. When I installed the keyboard on my android phone I'm getting these keys (bottom right): ![image](https://user-images.githubusercontent.com/7071907/269341782-c29991d1-c60f-4785-baa1-cee43d6c364d.png)
> 
> Has the build system gotten mixed up?

I have the same.

**Comment by mcdurdin** [comment]
Okay, so this was confusing. The deeper I dug into this, the stranger it got. Eventually, I was inspecting the touch layout directly on my phone using Chrome Web Inspector, and examined the <kbd>"</kbd> key cap. And here's what I saw:

![image](https://github.com/keymanapp/keyboards/assets/4498365/d478327d-24d2-475f-9482-512d5b9ee874)

![image](https://github.com/keymanapp/keyboards/assets/4498365/9fd5db66-242f-45a1-bf11-9bcf5f3933fc)

Note that the inspector shows the correct character. It's a font issue: Kende has the wrong glyph for U+2E2E, swapped with U+201F. Verified in FontForge:

![image](https://github.com/keymanapp/keyboards/assets/4498365/09fbc563-1692-4f5c-b95f-0689236ff703)

**Comment by rovasiras** [comment]
@mcdurdin I see. I'll prepare this, as soon as I can.

> Okay, so this was confusing. The deeper I dug into this, the stranger it got. Eventually, I was inspecting the touch layout directly on my phone using Chrome Web Inspector, and examined the " key cap. And here's what I saw:
> 
> ![image](https://user-images.githubusercontent.com/4498365/269559656-d478327d-24d2-475f-9482-512d5b9ee874.png)
> 
> ![image](https://user-images.githubusercontent.com/4498365/269559614-9fd5db66-242f-45a1-bf11-9bcf5f3933fc.png)
> 
> Note that the inspector shows the correct character. It's a font issue: Kende has the wrong glyph for U+2E2E, swapped with U+201F. Verified in FontForge:
> 
> ![image](https://user-images.githubusercontent.com/4498365/269560587-09fbc563-1692-4f5c-b95f-0689236ff703.png)

@mcdurdin I see. I'll prepare it, as soon as I can.

**Comment by LornaSIL** [comment]
@mcdurdin Oh goodness, gracious, sakes alive. How did you figure that out! Thank you!

**Comment by rovasiras** [comment]
@mcdurdin I'm sorry about it. There are other mistakes in the font. When I prepare these mistakes, I come back.

**Comment by rovasiras** [comment]
@LornaSIL @mcdurdin The https://github.com/rovasiras/kende-font/Kende.ttf refreshed now.

**Comment by mcdurdin** [comment]
@rovasiras are you asking us to publish an updated keyboard with the new version of the font?

**Comment by rovasiras** [comment]
> @rovasiras are you asking us to publish an updated keyboard with the new version of the font?

Yes. The previous version had encoding errors.
https://github.com/keymanapp/keyboards/issues/2371#issuecomment-1729185663

**Comment by mcdurdin** [comment]
OK, we'll put it on the list. Please do remember that this is an open source project and our contributions are a 'best effort' -- we cannot promise a specific response time.

**Comment by rovasiras** [comment]
@mcdurdin I close it and I'll make a concrete plan.
