### ISSUE TITLE
bug(sil_cameroon_qwerty): broken links in php help

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2379]
The following links are broken in sil_cameroon_qwerty.php [6.0.9], because they should have a .php extension:
```
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-ch-fr.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-us-en.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-us-fr.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-uk-en.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-de-en.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-uk-fr.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-ch-en.htm
/keyboard/sil_cameroon_qwerty/6.0.9/qwerty-de-fr.htm
```

**Comment by DavidLRowe** [comment]
@MattGyverLee

**Comment by MattGyverLee** [comment]
Makes sense...I guess I have to increment the version number when I fix it. Right?

**Comment by LornaSIL** [comment]
No, not if it's just the online help.

**Comment by MattGyverLee** [comment]
The PHP files are the one thing I'm not set up to test on my side. Sent a PR to handle them.

**Comment by mcdurdin** [comment]
The php files are something we are working to improve workflow on. It's a little tricky, but it isn't ideal having the same docs twice in slightly different formats!
