### ISSUE TITLE
[sil_ipa] Keyboard fails to install

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#238]
On Keyman Android, the **sil_ipa** 1.6 keyboard is available to download as

**Undetermined**
SIL IPA

When trying to download and install though, installation fails because the API returns null for `languages`
```
{
	"options": {
		"context": "language",
		"dateFormat": "standard",
		"device": "androidphone",
		"keyboardBaseUri": "https://s.keyman.com/keyboard/",
		"fontBaseUri": "https://s.keyman.com/font/deploy/",
		"keyboardid": "sil_ipa",
		"languageid": "und",
		"keyboardVersion": "current"
	},
	"language": []
}
```

.kps defines
```html
<Languages>
    <Language ID="und-Latn">und-Latn</Language>
</Languages>
```

.keyboard_info defines
```
    "languages": ["und-fonipa"],
```

PR #141 has the history of choosing those language tags

Update: June 13, 2018
If any language tags need to be changed, might as well also investigate with sil_ipa doesn't exist on KeymanWeb.

Not found on:
https://keymanweb.com/?tier=alpha
https://keymanweb.com

**Comment by darcywong00** [comment]
* It might be worth setting a region so **sil_ipa** is available on keymanweb.com
* A workaround on mobile apps is downloading https://downloads.keyman.com/keyboards/sil_ipa/1.6/sil_ipa.kmp to install

**Comment by darcywong00** [comment]
Some data points from keymanweb.com (Chrome mobile viewport)

https://keymanweb.com/#und,Keyboard_sil_ipa successfully loads

https://keymanweb.com/?tier=alpha#und,Keyboard_sil_ipa does not

**Comment by mcdurdin** [comment]
>https://keymanweb.com/#und,Keyboard_sil_ipa successfully loads

However, the keyboard does not appear work on desktop even though it shows as loaded.

**Comment by darcywong00** [comment]
Adding another data point.
On Desktop 10.0.1086.0

selecting "Undetermined" from the keyboard search results in
> No matches found for `'l:id:und'`

**Comment by LornaSIL** [comment]
I don't understand what is needed here. If someone can explain what is needed, I'll update the keyboard.
I could add some major language like en if that is helpful

Setting a region - maybe -001 for world?

Or, should I change the ```<Language ID="und-Latn">und-Latn</Language>``` to ```<Language ID="und-Latn">IPA for all languages</Language>```

Or, does something in Keyman need fixing?

**Comment by mcdurdin** [comment]
I think these are issues in Keyman that need fixing. Can try and review next sprint if I don't get too swamped.

**Comment by darcywong00** [comment]
This seems to work now. api.keyman.com is returning
```
    "languages": [
        "und-fonipa"
    ],
```

and the keyboard "Undetermined --> SIL IPA" installs on Keyman for Android 11.0.47 alpha.
