### ISSUE TITLE
[kayan] Request to reorder punctuation longpress keys

### ISSUE THREAD

**Issue by sdysart** [keymanapp/keyboards#2402]
Request from User
"I am wondering who I should initially ask if I want to adjust the Keyman
keyboard for Kayan for Android?  The main need is to change the order of
the symbols that appear on long press for the period/full stop so that
the more commonly used symbols are closer to the period and the less
used ones are farther away. The rest of the keyboard, at this point, is
to remain unchanged."

**Comment by darcywong00** [comment]
Can you confirm if this is the keyboard?
https://keyman.com/keyboards/kayan

Would need your user to specify what are "more commonly used symbols" (and the order they want).

(modifies https://github.com/keymanapp/keyboards/blob/master/release/k/kayan/source/kayan.keyman-touch-layout)

**Comment by sdysart** [comment]
Yes, that is the keyboard.
I'll ask the user for the preferred order

**Comment by darcywong00** [comment]
A few weeks late, but here's what the user requested:

> We want the comma and question mark to be nearest the place where the person is pressing, since they are more commonly used than the colon and semicolon and slash.
So, I think it would be fine if we sort of just swapped the places of those items.
>
>It would end up being
: ; / ' " ! , ? 
>or something like that. I think the slash is going the wrong way for use in things like typing websites, so probably best to use the more common one, if one is to be included at all there.

Darcy: I read this as wanting the period right of the question mark.
