### ISSUE TITLE
bug(fv_dene_zhatie): broken link in keyboard help v10.0

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2412]
Getting links from: http://localhost:8888/keyboard/fv_dene_zhatie
├─BROKEN─ http://localhost:8888/keyboard/fv_dene_zhatie/10.0/fv_dene_zhatieU_.png (HTTP_404)

**Comment by DavidLRowe** [comment]
This specific problem (missing file causing broken link) is fixed by #2403
