### ISSUE TITLE
Shan SIL keyboard issues with LibraOffice in Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by monghsei** [keymanapp/keyboards#2420]
when typing the Shan characters ​ေ​ and ​ႄ there is a kind of "," appears in front of them. 

![image](https://github.com/keymanapp/keyboards/assets/4498365/54b429f0-08b8-456c-9860-591514e4492b)

[source image](https://www.dropbox.com/scl/fi/w0gqjjta0rid23noio7xg/Screenshot-from-2023-10-23-09-15-25.png?rlkey=y0n8l1h2ni2fj1dkplgojcf30&dl=0)

@SZTSIIT would know more. 

Thanks :)

**Comment by mcdurdin** [comment]
Thanks for the report. For the video you've attached, could you please tell us (a) the exact key sequence typed, and (b) the expected output?

**Comment by monghsei** [comment]
Sorry! forget about the video. The issues with LibraOffice is on the image above.When type "a" and "s" the Shan Characters show show "​ေ“ “​ႄ“ instead they show ",​ေ" and ",​ႄ". But this only happens on LibraOffice. It works find on MS Word online.

**Comment by SZTSIIT** [comment]
@monghsei @mcdurdin It is not because of the Shan Sil Keyboard. It is the "Arial Unicode MS "'s issue. Please see the attached image. 
<img width="685" alt="image" src="https://github.com/keymanapp/keyboards/assets/69423986/b17cd0de-e02d-41cc-863e-b14d006168e9">
@monghsei If you change your font to other stable Unicode fonts like Padauk or GHK Yangon, the keyboard should work properly as expected. Thank you the report anyway. :D

**Comment by monghsei** [comment]
I see, big thanks !!!!

**Comment by SZTSIIT** [comment]
@monghsei And it is ok we would never type only ​ေ or ​ႄ anyway. So it should be fine. 
<img width="834" alt="image" src="https://github.com/keymanapp/keyboards/assets/69423986/5155a1de-1c6b-4dad-a43a-9f0de01838a7">

**Comment by SZTSIIT** [comment]
> As indicated those characters will not be typed by themselves or next to each other. But this sequence that should not occur, does indicate a difference between LibreOffice and MS Word. What you are seeing in LibreOffice is not a glyph from a font, rather its an editing apparatus, A way for LibreOffice to highlight the presence of a non-visual character, in this case ‎U+200B ZERO WIDTH SPACE. In MS Word, there is no U+200B present. Looking at the keyboard source, we have the following line of code: + any(prevK) > outs(filler) index(prevU, 1) so if you type the a or s key, you get U+200B (the filler) followed by U+1031 or U+1084. The U+200B is removed and U+1031 or U+1084 are reordered when the base character is typed. So if you type in "as" you should get U+200B U+1031 U+200B U+1084 as displayed in LibreOffice, and not U+1031 U+1084 as displayed in MS Word. This was tested on macOS, so may also need to be tested on Windows separately. But at first glance there is a difference between what LibreOffice is doing and what MS Word is doing. Additionally LibreOffice seems to be working as expected. MS Word is divergent.

Thank You so much. I will pass this information in our community for a future reference.

**Comment by monghsei** [comment]
@SZTSIIT  I have tried changing fonts in the Ubuntu version of LibreOffice and the problems is not solved. I also have tried in Windows versions and the keyboard works fine.

**Comment by SZTSIIT** [comment]
> @SZTSIIT I have tried changing fonts in the Ubuntu version of LibreOffice and the problems is not solved. I also have tried in Windows versions and the keyboard works fine.

​​ၵေႃႉၼၼ်ႉသပ်းလႅင်းၼႄဝႆႉယဝ်ႉၶႃႈ ဢၼ်​​ပေႃးႁဝ်းတႅမ်ႈ ​​​ေ လႄႈ ​ႄ ပဝ်ႇဢမ်ႇမီးတူဝ် သရ ၸွမ်းလင်မၼ်းၼႆ မၼ်း​​တေၼႄဝႆႉပၼ်ဝႃႈ ​​​ေ လႄႈ ​ႄ ၼၼ်ႉပဝ်ႇဝႆႉၼႆ​​ဢေႃႈ။   တႄႇ ​​ပေႃးႁဝ်းမႃး ဢိတ်ႇဢွၵ်ႇ ႁိုဝ် ႁဵတ်းပဵၼ်  PDF ႁိုဝ်ၸိူဝ်းၼႆႉတႄႉ မၼ်း​​တေၼႄဝႆႉပၼ် ဢၼ်ပဝ်ႇလွၼ်ႉလွၼ်ႉၼႆၶႃႈ ။ မၼ်းပဵၼ် Feature ၶွင် Libreoffice ၶႃႈၵႂႃႈ ။ ႁဝ်းလွၵ်းမိုဝ်းသင်မႃး​​ပေႃႉ ၼႂ်း Libreoffice ​​ၵေႃႈလီ ၵႂႃႇ Copy မႃး Paste သႂ်ႇ​​ၵေႃႈလီမၼ်းတိုၼ်း​​တေၼႄဝႆႉမႆႉတိုတ်ႉၼၼ်ႉၶႃႈ ၵွပ်ႇ မၼ်းပဵၼ် ​​​ေ ​ႄ ပဝ်ႇ ၶႃႈလု ။ လွၵွးမိုဝ်းတႄႉ ႁဵတ်းၵၢၼ်လီယူႇၶႃႈ။ 

မႂ်ႇသုင်

**Comment by LornaSIL** [comment]
Since this does not appear to be a keyboard issue, it appears to be a LibreOffice issue, I am closing this Keyman keyboard Github issue. If the problem remains, this should be raised to LibreOffice.
