### ISSUE TITLE
bug(gff_sbs): missing pdf in documentation

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2482]
gff_sbs/1.0.0/SBS-Typing-Manual.pdf is referenced but actually called SBS-Typing-English.pdf.

Detected in checks on https://github.com/keymanapp/help.keyman.com/pull/903

@dyacob

**Comment by dyacob** [comment]
Thanks, @mcdurdin, sorry...  Addressed in #2483 . 

In the course of the correction, I did now catch a small issue with KMD that I'll report, so that should be a plus.

**Comment by dyacob** [comment]
Thank you @LornaSIL , I adjusted it in the `.kmn` file, I believe that was the only place. LMK if there was another.
