### ISSUE TITLE
feat: add an experimental LDML keyboard to validate CI (on staging branch)

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2484]
Suggest adding the CLDR bengali keyboard, based on SIL Bengali Keyman keyboard

**Comment by darcywong00** [comment]
Is @srl295 doing this in #2446?

**Comment by mcdurdin** [comment]
I think we should aim to make that our experiment, yes. I don't know who will add it to the keyboards repo though.

**Comment by mcdurdin** [comment]
This is being done in #2865.

**Comment by mcdurdin** [comment]
We have a real keyboard imperial_aramaic added in #2993. This can be considered complete.
