### ISSUE TITLE
[armenian] Legacy keyboard `armenian.js` outputs wrong character when typing `-`

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyboards#2487]
According to the OSK typing <kbd>-</kbd> should output `ռ` but does output `ժ`. Typing <kbd>=</kbd> outputs `=` but should output `ժ`. Things are correct with <kbd>Shift</kbd>.

Things are correct with `armenian.kmp`.

**Comment by LornaSIL** [comment]
So, should we close this or what needs to happen? Since this is in `legacy` we don't make changes to the keyboards.
If there is a problem, the only thing we *could* do is to add an online help file as it appears that doesn't exist.

**Comment by mcdurdin** [comment]
This may be a bug in KeymanWeb or in the Keyman Developer Compiler. I would like to transfer to keyman repo and try and track it down, to ensure that we don't have something else going on.

Note: have tested with KeymanWeb back to 11.0 and behaviour is the same in all versions.

**Comment by mcdurdin** [comment]
See keymanapp/keyman#10223
