### ISSUE TITLE
bug(fonts): 3 characters shown up as tofu on baybayin keyboard 

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyboards#2489]
There are 3 keys that appear as tofu instead of its glyph, even with the latest font ["Noto Sans Tagalog"](https://fonts.google.com/noto/specimen/Noto+Sans+Tagalog/tester). 

These images are before the installation. 
![image](https://github.com/keymanapp/keyboards/assets/123520338/e4ebf3c2-6c1c-4412-8ec9-de39b102d615)

shift layer:  
![image (1)](https://github.com/keymanapp/keyboards/assets/123520338/4ea9e106-b435-44f4-a353-fab21619e2e0)

We also test it on google fonts website and it looks good. 
![image (2)](https://github.com/keymanapp/keyboards/assets/123520338/89d6ff34-55a4-48a3-a7ff-ba80c3ee0abd)

And this is how it looks on Keyman test page in both before and after installing the new font. -- they're all tofu. 
![image (3)](https://github.com/keymanapp/keyboards/assets/123520338/8adc0472-89e0-41b3-be08-404c0412c73f)

Keyman Developer v16.0.143
Windows 10 Home v2004
Noto Sans Tagalog v1.03uh and 2.002 (old and new fonts) 
Keyboard PR: https://github.com/keymanapp/keyboards/pull/2485 

These characters are shown correctly on macOS 14.1.2: 
![image](https://github.com/keymanapp/keyboards/assets/123520338/9a459ec2-6c5b-499f-8c2b-fb124fc0abf5)
![image](https://github.com/keymanapp/keyboards/assets/123520338/20e8a740-458f-4e2b-aa63-0fcc3a00e5a1)

 Let us know if you need further infos.

**Comment by LornaSIL** [comment]
This now displays in the Web keyboard and on my Android.
