### ISSUE TITLE
The "Ctrl Alt" Simulation Doesn't Output the Expected Characters

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#250]
With the keyboards that use AltGr, when simulating the AltGr for the "Ctrl Alt", the expected characters are not output when using "the Ctrl Alt"; the OSK shows those characters though. 

For instance, when pressing AltGr or "Ctrl Alt", the OSK shows this same layout:
![khmer angkor when pressing altgr or ctrl alt](https://user-images.githubusercontent.com/28331388/39414154-a552de80-4c5e-11e8-840a-ea6b840a3485.PNG)

but nothing is output when press any key while press & hold the "Ctrl Alt". Only with the AltGr that the expected characters are output. 

The bug can be reproduced using this keyboard: https://keyman.com/keyboards/khmer_angkor .

**Comment by mcdurdin** [comment]
Issue is tracked with keymanapp/keyman#835
