### ISSUE TITLE
[fv_all] - Some keyboards are not the latest

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2502]
@caforbes reported the latest 16.0 FV app doesn't include the latest versions for some keyboards:
* Southern Tutchone (updated 4mo ago) - on my Android phone it's listed as 9.2.1 but I see a plain qwerty layout (9.2)
* For Dane-Zaa Zaage (updated 2mo ago) I can only download 9.2, not 9.3
* we don't see a recently added keyboard in the list anywhere to download (Hul̓q̓umin̓um̓/hulquminum_combine

-----

Some other things to investigate:
* The latest [fv_all.kmp](https://downloads.keyman.com/keyboards/fv_all/12.5/) package (12.5) has a Last-modified timestamp 2023-04-03 while the folder is 2023-12-12
* fv_all (12.5) is including fv_dane_zaa_zaage 9.2

**Comment by darcywong00** [comment]
> The latest fv_all.kmp package (12.5) ....

Ah right, I forgot this is where we increment the fv_all.kmp version
https://github.com/keymanapp/keyboards/blob/1a34852801783764f475743c6c515068b0910594/release/packages/fv_all/source/fv_all.kps.in#L21

**Comment by darcywong00** [comment]
We might also need to update [keyboards.csv](https://github.com/keymanapp/keyman/blob/master/oem/firstvoices/keyboards.csv) in the main repo so the FV apps can associate the BC region with fv_hulquminum_combine

**Comment by DavidLRowe** [comment]
@darcywong00 Does #2504 fix this issue?

**Comment by darcywong00** [comment]
> Does https://github.com/keymanapp/keyboards/pull/2504 fix this issue?

That plus keymanapp/keyman#10269 which associates the BC Coast region for fv_hulquminum_combine will fix the issue.

**Comment by darcywong00** [comment]
Fixed by the 3 associated PRs.
keymanapp/keyman#10285 has the fix for 16.0
