### ISSUE TITLE
bug[itrans_bengali]: key v and b has the same output letter.

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyboards#2542]
On the [keyboard ](https://keyman.com/keyboards/itrans_bengali)and [documentation](https://help.keyman.com/keyboard/itrans_bengali/1.0.1/itrans_bengali):
![image](https://github.com/keymanapp/keyboards/assets/90595388/d4c8c4e0-5feb-4118-a7da-75ba2b0bd4bd)

The expected outputs: 
![image](https://github.com/keymanapp/keyboards/assets/90595388/c4832d43-1749-4b9a-9054-144a3e0dcf55)

Only <kbd>v</kbd> is incorrect.

Original post - https://community.software.sil.org/t/output-character-not-displaced-by-the-key/8402

**Comment by LornaSIL** [comment]
#2400 should be addressed at the same time as this one.

**Comment by jayaradhakrishna** [comment]
My suggestion is to change different output letter for two different keys v and b. 

There is no need to have the current keys v and b having the same output letter ব্
 
I suggest the following: 

Option 1
v should give the output as  ৎ as stated for the Special Bengali Sign 
b should give the output as ব্
B should give the output as ভ্

Option 2
b should give the output as  ৎ as stated for the Special Bengali Sign 
v should give the output as ব্
V should give the output as ভ্

Option 3
_  should give the output as  ৎ 
Let keys v and b have the same output letter  ব্

**Comment by jayaradhakrishna** [comment]
Any progreess regarding this  
https://community.software.sil.org/t/output-character-not-displaced-by-the-key/8402

**Comment by mcdurdin** [comment]
> Any progreess regarding this
> https://community.software.sil.org/t/output-character-not-displaced-by-the-key/8402

We are working on it

**Comment by jayaradhakrishna** [comment]
Thank you so much for this.

I guess the bug is fixed and the next step is to fix the keyboard.

Jaya Radhakrishna dasa

**Comment by jayaradhakrishna** [comment]
Do we need to download the new keyboard since the bug is fixed now?

**Comment by LornaSIL** [comment]
#2545 hasn't been approved yet. There is one more action that needs doing before it can be approved. Once it's approved and merged then I think it will automatically be offered to anyone who has installed the keyboard from the Keyman site.

**Comment by mcdurdin** [comment]
Yes, once the fix is approved and merged, it will be distributed via an automatic update within a few days. You can check for keyboard updates or manually update it once it has been merged. The new version of the keyboard will be 1.0.2.

**Comment by jayaradhakrishna** [comment]
Thank you all so much for this. Great to see that it was updated nicely.

**Comment by jayaradhakrishna** [comment]
Great to see that it was updated. Thank you all.

Sincerely,
Jayaradhakrishna dasa

**Comment by gsghyd** [comment]
There is good reason to have the keys [b] and [v] output the same akṣara ব in a phonetic keyboard. This is exactly what happens in Gautami Bangla/Bengali. But itrans_bengali is *not* a phonetic keyboard.
