### ISSUE TITLE
[grkpoly2] Keyboard fails to update on iOS

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#258]
User reports from Support Case 78779

> It said an update was available, but the alert dialog that came up has an unlabelled button! (Keyboard Update Error, "OK", and “—-“).

![keyboard update error](https://user-images.githubusercontent.com/7358010/39668638-4476d988-50fd-11e8-9c18-050578bdb143.png)

### Configuration
Keyboard 11.0.5 alpha
iPhone 7
iOS 11.3
Keyboard ID: grkpoly2
Language ID: grc

We should investigate why this keyboard failed to update

see keymanapp/keyman#824

**Comment by DavidLRowe** [comment]
@darcywong00 is it a problem with the language id? Code is "el" (rather than "grc").

**Comment by darcywong00** [comment]
It sounds like we need to add `grc` to the keyboard_info file?

https://api.keyman.com/search?q=k&platform=ios currently doesn't include `grkpoly2` for language ID: `grc`

**Comment by DavidLRowe** [comment]
I see now that grc is the code for Ancient Greek. If this keyboard is suitable for typing Ancient Greek, then grc should be added to the list of BCP 47 codes.

**Comment by srl295** [comment]
@DavidLRowe out of curiosity, what is the 'list of BCP 47 codes'? do you keep a specific whitelist of codes?

**Comment by darcywong00** [comment]
@DavidLRowe was referring to the list of BCP 47 language tags in the metadata file
`legacy/g/grkpoly2/grkpoly2.keyboard_info`

that says what languages are associated with this `grkpoly2` keyboard.

If you're asking for a full listing of tags, we use a snapshot of [alltags.txt](https://github.com/silnrsi/sldr/blob/master/extras/alltags.txt) from the NRSI.

**Comment by DavidLRowe** [comment]
So, it turns out to be more complicated. The keyboard is currently in the legacy collection and, IIUC, would need to be released under the MIT license (after getting the author's consent) in order to be placed in the release collection, where we could add the `grc` code to the package.
