### ISSUE TITLE
Roman transliteration output and Devanagari output not working

### ISSUE THREAD

**Issue by jayaradhakrishna** [keymanapp/keyboards#2582]
I have installed 
https://keyman.com/keyboards/heidelberginputsolution 
https://keyman.com/keyboards/itrans_bengali?bcp47=bn

The Bengali output is perfect as expected in https://help.keyman.com/keyboard/itrans_bengali/1.0.2/itrans_bengali, 

The Roman transliteration output and Devanagari output not working as expected in https://help.keyman.com/keyboard/heidelberginputsolution/1.0/heidelberginputsolution

**Comment by LornaSIL** [comment]
Unfortunately we are not able to update the heidelberginputsolution as it is an older keyboard where the licensing does not allow us to make modifications. I'm very sorry for this. I hope you can find a different keyboard that will work for you.

**Comment by mcdurdin** [comment]
I think this may be related to a [recent forum discussion](https://community.software.sil.org/t/devanagari-transliteration-not-working/8480/11) and may be a configuration or compatibility issue rather than a bug specifically with the keyboard.
