### ISSUE TITLE
feat [yiddish_pasekh]: independent keys for letters אױ and אײַ 

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyboards#2589]
@LornaSIL, a User contacted Keyman via Email and is looking for this implementation. Here is what they said:

_The full context translated from German using Google Translate:_
> Regarding the two missing letters אײַ / אױ: I know that I can "make" them. But I don't understand why these two missing letters don't have their own key assignment when the remaining letters, which also require a א at the beginning of the word, do have their own key. Especially since there are still unused keys (see below for the shifted keys) on the keyboard. It would just be easier to write.
> 
> Thank you again and greetings from Vienna!
> 
> ![image](https://github.com/keymanapp/lexical-models/assets/90595388/c2a3c7a0-d116-45e5-90cc-18cee71aa8e8)

Keyboard - https://keymanweb.com/#ydd-hebr,Keyboard_yiddish_pasekh
Keyboard help document - https://help.keyman.com/keyboard/yiddish_pasekh/1.9/yiddish_pasekh

The other keys that the User mentioned are **או, אי, אײ**...have their independent keys and combination keys to output them. But not for **אױ** and **אײַ** (the keys that the User wants as independent keys too).

To produce the אױ, press <kbd>Shift</kbd> + <kbd>a</kbd> and <kbd>Shift</kbd> + <kbd>o</kbd>
To produce the אײַ, press <kbd>Shift</kbd> + <kbd>a</kbd> and <kbd>Shift</kbd> + <kbd>y</kbd>

Would it be ideal to add these two characters to the SHIFTED layer or is there another reason that this is not recommended?

**Comment by LornaSIL** [comment]
I can write the keyboard author to see what he thinks.

**Comment by zsigrigy** [comment]
You can simply type ay and oy to get אײַ and אױ at the beginning of a word. Otherwise, you don't really need a shtumer alef before them.

**Comment by Meng-Heng** [comment]
Hello @zsigrigy, can we add אײַ and אױ on the <kbd>SHIFT R</kbd> and <kbd>SHIFT D</kbd>?

**Comment by EvafromVienna** [comment]
Die von @zsigrigy  angeführte Lösung, nämlich dass der shtumer alef automatisch am Wortanfang eingefügt wird, wäre natürlich die beste Lösung. Derzeit funktioniert das jedoch nur bei i, u und ey, nicht jedoch bei ay und oy.

**Comment by EvafromVienna** [comment]
> You can simply type ay and oy to get אײַ and אױ at the beginning of a word. Otherwise, you don't really need a shtumer alef before them.

**Comment by EvafromVienna** [comment]
That would be the best solution, but at the moment this works only with i,u and ey, but not with ay and oy.

**Comment by EvafromVienna** [comment]
> That would be the best solution, but at the moment this works only with i,u and ey, but not with ay and oy.

Update: It doesnt work with ey either.

**Comment by EvafromVienna** [comment]
> > That would be the best solution, but at the moment this works only with i,u and ey, but not with ay and oy.
> 
> Update: It doesnt work with ey either.

Oh, sorry, is does with the key J.

**Comment by LornaSIL** [comment]
> Hello @zsigrigy, can we add אײַ and אױ onto the SHIFT R and SHIFT D?

The author of the keyboard doesn't really think these are needed.
> Those digraphs can be typed as ay or oy at the beginning of a word where a silent א is automatically inserted before the ײַ or ױ. Otherwise, a silent א is not normally used before ײַ or ױ. So it seems the user wants to solve a problem that does not exist.

I don't think we need to update the keyboard.

**Comment by EvafromVienna** [comment]
"Those digraphs can be typed as ay or oy at the beginning of a word where a silent א is automatically inserted before the ײַ or ױ."
That automatical insertion doesn't work at my keyboard with these two letters (it does work with the letters i, u and ey)! Does it at yours?

**Comment by Meng-Heng** [comment]
Hello @EvafromVienna

Yes, the ay and oy insertion does work for me. I'm using version 1.9 of the Yiddish Pasekh keyboard with Keyman v-16.0.145. What outputs are shown for you when typing oy and ay and what is the keyboard version that is installed?

Would you be able to get the same result as oy and ay with these keystrokes below:
> To produce the אױ, press Shift + a and Shift + o
> To produce the אײַ, press Shift + a and Shift + y

If it doesn't work then we should look further at the information from your side:
1. What is your OS? (Windows, Mac...)
2. What is the keyman version?
3. Please send a [diagnostic report](https://help.keyman.com/knowledge-base/?id=40)

Let us know how it goes. Thank you!

**Comment by Meng-Heng** [comment]
The conversation continues on Keyman's community site - https://community.software.sil.org/t/diagnostic-report-from-eva-tiefenbrunner-gm/8567/2

**Comment by EvafromVienna** [comment]
Dear MengHong
When does the conversation take place?
Eva

MengHeng ***@***.***> schrieb am Fr., 22. März 2024, 03:52:

**Comment by Meng-Heng** [comment]
Hello @EvafromVienna, 

The message you see is on GitHub and I have already sent you the details of the remote session via Gmail. Would you be able to confirm?

**Comment by Meng-Heng** [comment]
Upon investigation, we found that the a + y and o + y work normally with the Yiddish Pasekh keyboard, and there won't be any implementation of the keyboard.
