### ISSUE TITLE
Add Shina Keyboard

### ISSUE THREAD

**Issue by rachitralli** [keymanapp/keyboards#261]
https://github.com/rachitralli/Initial-Shina-Keyboard

**Comment by MakaraSok** [comment]
@rachitralli Please create a PR for this keyboard and organize the files and folders in a way that is similar to that of your previous keyboard (i.e. [rac_khowar](https://github.com/keymanapp/keyboards/tree/28fb1eefd11133345cf7619586fa2139ccb934ff/release/rac/rac_khowar)).

**Comment by rachitralli** [comment]
@MakaraSok sir, I have uploaded all the source file of Shina Keyboard here https://github.com/rachitralli/Initial-Shina-Keyboard please guide me regarding another PR for this keyboard or to create folders or files? I request to @LornaSIL @mcdurdin and @DavidLRowe to please look into the https://github.com/rachitralli/Initial-Shina-Keyboard and shift all the files in one PR. I have no write access to github and i am unable to modify the files. please guide and help me. thanks

**Comment by mcdurdin** [comment]
@MakaraSok are you able to create the PR based on @rachitralli's request and shared files?

**Comment by rachitralli** [comment]
@mcdurdin @MakaraSok created PR here https://github.com/keymanapp/keyboards/pull/283 please check and guide if anything is missing, regards

**Comment by rachitralli** [comment]
Merged at https://github.com/keymanapp/keyboards/pull/283 therefore I am closing this issue as solved.
