### ISSUE TITLE
Medefaidrin: Design for a new keyboard

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#2616]
This was requested on the community site:
https://community.software.sil.org/t/scripts-missing/8498/9
If someone wishes to create one, that would be great!

![bd38f930180eb9b0ed28e62dd0ca74a416f7dd73](https://github.com/keymanapp/keyboards/assets/7071907/df9da9cf-d3ad-429d-9c20-893d5e0fab7b)

More research needed on what punctuation to include and what digits.

Language associations would be:
`dmf` (no script code needed)

**Comment by mauriu** [comment]
![Medefaidrin](https://github.com/keymanapp/keyboards/assets/161212377/fa7ee032-c0aa-4cec-823d-e6318dbe14a7)
store(&VERSION) '10.0'
store(&NAME) 'Medefaidrin'
store(&VISUALKEYBOARD) 'medefaidrin.kvks'
store(&BITMAP) 'medefaidrin.ico'
store(&LAYOUTFILE) 'medefaidrin.keyman-touch-layout'
store(&COPYRIGHT) '© SIL International'
store(&KEYBOARDVERSION) '1.0'
store(&TARGETS) 'any'

begin Unicode > use(main)

group(main) using keys

+ [K_SPACE] > U+0020

+ [K_0] > U+0030
+ [SHIFT K_0] > U+0029

+ [K_1] > U+0031
+ [SHIFT K_1] > U+0021

+ [K_2] > U+0032
+ [SHIFT K_2] > U+0040

+ [K_3] > U+0033
+ [SHIFT K_3] > U+0023

+ [K_4] > U+0034
+ [SHIFT K_4] > U+0024

+ [K_5] > U+0035
+ [SHIFT K_5] > U+0025

+ [K_6] > U+0036
+ [SHIFT K_6] > U+005e

+ [K_7] > U+0037
+ [SHIFT K_7] > U+0026

+ [K_8] > U+0038
+ [SHIFT K_8] > U+002a

+ [K_9] > U+0039
+ [SHIFT K_9] > U+0028

+ [NCAPS K_A] > U+16E6D
+ [CAPS K_A] > U+16E4D

+ [NCAPS K_B] > U+16E7E
+ [CAPS K_B] > U+16E5E

+ [NCAPS K_C] > U+16E71
+ [CAPS K_C] > U+16E51

+ [NCAPS K_D] > U+16E79
+ [CAPS K_D] > U+16E59

+ [NCAPS K_E] > U+16E6F
+ [CAPS K_E] > U+16E4F

+ [NCAPS K_F] > U+16E6A
+ [CAPS K_F] > U+16E4A

+ [NCAPS K_G] > U+16E69
+ [CAPS K_G] > U+16E49

+ [NCAPS K_H] > U+16E76
+ [CAPS K_H] > U+16E56

+ [NCAPS K_I] > U+16E6B
+ [CAPS K_I] > U+16E4B

+ [NCAPS K_J] > U+16E6E
+ [CAPS K_J] > U+16E4E

+ [NCAPS K_K] > U+16E6C
+ [CAPS K_K] > U+16E4C

+ [NCAPS K_L] > U+16E74
+ [CAPS K_L] > U+16E54

+ [NCAPS K_M] > U+16E60
+ [CAPS K_M] > U+16E40

+ [NCAPS K_N] > U+16E7B
+ [CAPS K_N] > U+16E77
+ [SHIFT K_N] > U+16E5B
+ [CAPS SHIFT K_N] > U+16E57

+ [NCAPS K_O] > U+16E7D
+ [CAPS K_O] > U+16E5D
+ [NCAPS SHIFT K_O] > U+16E7A
+ [CAPS SHIFT K_O] > U+16E5A

+ [K_P] > U+16E67
+ [CAPS K_P] > U+16E47

+ [NCAPS K_Q] > U+16E75
+ [CAPS K_Q] > U+16E55

+ [NCAPS K_R] > U+16E7C
+ [CAPS K_R] > U+16E5C

+ [NCAPS K_S] > U+16E61
+ [CAPS K_S] > U+16E41

+ [NCAPS K_T] > U+16E68
+ [CAPS K_T] > U+16E48

+ [NCAPS K_U] > U+16E72
+ [CAPS K_U] > U+16E52
+ [NCAPS SHIFT K_U] > U+16E73
+ [CAPS SHIFT K_U] > U+16E53

+ [NCAPS K_V] > U+16E62
+ [CAPS K_V] > U+16E42

+ [NCAPS K_W] > U+16E63
+ [CAPS K_W] > U+16E43

+ [NCAPS K_X] > U+16E78
+ [CAPS K_X] > U+16E58

+ [NCAPS K_Y] > U+16E7F
+ [CAPS K_Y] > U+16E5F

+ [NCAPS K_Z] > U+16E65
+ [CAPS K_Z] > U+16E45

+ [K_COLON] > U+003b
+ [SHIFT K_COLON] > U+003a

+ [K_EQUAL] > U+003d
+ [SHIFT K_EQUAL] > U+002b

+ [K_COMMA] > U+002c
+ [SHIFT K_COMMA] > U+003c

+ [K_HYPHEN] > U+002d
+ [SHIFT K_HYPHEN] > U+005f

+ [K_PERIOD] > U+002e
+ [SHIFT K_PERIOD] > U+003e

+ [K_SLASH] > U+002f
+ [SHIFT K_SLASH] > U+003f

+ [K_BKQUOTE] > U+0060
+ [SHIFT K_BKQUOTE] > U+007e

+ [K_LBRKT] > U+005b
+ [SHIFT K_LBRKT] > U+007b

+ [K_BKSLASH] > U+005c
+ [SHIFT K_BKSLASH] > U+007c

+ [K_RBRKT] > U+005d
+ [SHIFT K_RBRKT] > U+007d

+ [K_QUOTE] > U+0027
+ [SHIFT K_QUOTE] > U+0022

+ [K_oE2] > U+005c
+ [SHIFT K_oE2] > U+007c

**Comment by LornaSIL** [comment]
Fixed by #2825. I didn't actually use the code above as I forgot it was there.
