### ISSUE TITLE
[dega] Missing grave accent  

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyboards#2618]
The picture below is the K’Ho language we are using. In addition to special characters with unique characteristics, it also has an apostrophe ("") in Vietnamese. For example: Kơnràñ, dà Làc, dơ…"Although Keyman allows conversion to Talex for use in typing Vietnamese characters. But it’s very time consuming and inconvenient. Can you help us add the feature of typing talex (with Vietnamese accents) in the K’Ho keyboard? This way the software will be more complete. We thank you very much.

from the community site: https://community.software.sil.org/t/dega-keyboard-of-keyman/8578

**Comment by LornaSIL** [comment]
Fixed by #2713
