### ISSUE TITLE
Add Indus-Kohistani Keyboard

### ISSUE THREAD

**Issue by rachitralli** [keymanapp/keyboards#262]
@mcdurdin sir I am pleased to inform you that I have completed another keyboard i.e. Indus-Kohistani keyboard and uploaded all the source files here https://github.com/rachitralli/Initial-Indus-Kohistani-Keyboard please look into the matter and assign someone for amendments if any. I request the team to create a PR based on the following files https://github.com/rachitralli/Initial-Indus-Kohistani-Keyboard for this keyboard. With profound regards

**Comment by mcdurdin** [comment]
@MakaraSok would you be able to look into this?

**Comment by rachitralli** [comment]
@mcdurdin sir, thanks

**Comment by DavidLRowe** [comment]
@rachitralli It seems that pull request #367 addresses this issue. Is that correct?

**Comment by MakaraSok** [comment]
@DavidLRowe It looks like this is no-longer an issue as the PR you mentioned above should take care of it. Thus, this issue is closed now.
