### ISSUE TITLE
chore: migrate master into staging-17.0

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2627]
Need to migrate changes in master since staging-17.0 was established. See #2423, notes in commit history on steps that need to be taken. Mostly relates to merging .keyboard_info metadata into .kps, some smaller tidyup sometimes required.

**Comment by darcywong00** [comment]
* Standardize Copyright notice in LICENSE.md
* .kps changes:
  *  Add `<LicenseFile>..\LICENSE.md</LicenseFile>`
  * Add File LICENSE.md

Migrate from .keyboard_info to .kps   
  * `<Description>`
  * `Examples`
  * languages.font --> `<WebDisplayFonts>`
  * languages.oskFont --> `<WebOSKFonts>`
 
* Remove keyboard_info

**Comment by darcywong00** [comment]
Link to wiki on splitting massive merges
https://github.com/keymanapp/keyman/wiki/One-way-to-refresh-a-long%E2%80%90lived-staging-branch-on-keyboards-(or-any)-repo

**Comment by LornaSIL** [comment]
@mcdurdin has this been done?

**Comment by mcdurdin** [comment]
Yep, all done now. Hurrah!
