### ISSUE TITLE
Glagolitic: Design for a new keyboard

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#2632]
This was requested on the community site:
https://community.software.sil.org/t/scripts-missing/8498/9
If someone wishes to create one, that would be great!

![514f3327de2c971e55559042ba7376cb48b027d1_2_690x220](https://github.com/keymanapp/keyboards/assets/7071907/6126f488-7759-4266-b1b3-a49b8bd3d27b)

More research needed on what punctuation to include and what digits.

The language associations would be:
ckm-Glag
cu-Glag
sr-Glag

**Comment by mareuo** [comment]
![glagolitic](https://github.com/keymanapp/keyboards/assets/170236007/da0fcd84-7fbe-4d20-be3b-cade7f8c0535)
