### ISSUE TITLE
update FV files

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyboards#2675]
At some point after this [#2648] is released, in order to get this keyboard distributed in the mobile apps, one of us will needed to update:
* fv_all kps version in the [source file](https://github.com/keymanapp/keyboards/blob/02603516ed2382d610d5571a0cd2dbdd3fa4d416/release/packages/fv_all/source/fv_all.kps.in#L21)
* add fv_sguux entry (for BC Coast region / tsi - Tsimshian language) in [keyboards.csv](https://github.com/keymanapp/keyman/blob/master/oem/firstvoices/keyboards.csv)

_Originally posted by @darcywong00 in https://github.com/keymanapp/keyboards/issues/2648#issuecomment-2041659418_

**Comment by darcywong00** [comment]
The updated fv_all.kmp versions will be in 17.0.306 beta
