### ISSUE TITLE
bug(sil_khmer v1.5): missing characters, confusing key hints and letter encoding, and no documentation of touch layout

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyboards#2703]
**Keyboard help document: https://help.keyman.com/keyboard/sil_khmer/1.5/sil_khmer**
### Missing keys:

- [x] - Missing letters are:<kbd> ៏</kbd><kbd> ៌</kbd> and<kbd> ៃ</kbd>

### Key hints:

- [x] Updated

- The document stated <kbd>|</kbd> (ឫ) + <kbd>,</kbd> to toggle between <kbd>ឬ ឫ ឩ</kbd>but there is no <kbd>|</kbd> on the mobile layout, except there is ឫ with the key hint of <kbd>\\</kbd> which stands for ឮ
![image](https://github.com/keymanapp/keyboards/assets/90595388/59d891b2-66a6-40e1-9939-d5fa54e7406f)
![image](https://github.com/keymanapp/keyboards/assets/90595388/af7576c7-5ad2-4fd4-8f19-8ae299c0b7d8)
- Similarly, the key hints for < or ។ are not the same as stated on the document (desktop documents)
![image](https://github.com/keymanapp/keyboards/assets/90595388/714ba10a-4377-4fdc-ab19-ac0a721a6567)
- What we have instead:
![IMG_2590](https://github.com/keymanapp/keyboards/assets/90595388/03db8853-4a87-40af-ae26-7554c8a67078)

### Issue with the Khmer Encoding:

- [x] - Typing ោះ on sil_khmer keyboard will output <kbd>េ‍ា‍ះ</kbd> (on mobile and NotePad for Windows)

### Documentation for Touch Layout:

- [x] - No documentation shows the CTRL + ALT or SHIFT + CTRL + ALT layer and it was confusing enough to locate the missing characters that were hidden behind additional keystrokes.

Thank you!

**Comment by LornaSIL** [comment]
Fixed by #2712
