### ISSUE TITLE
[aava1.ttf] - Need licensing info

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2729]
As part of #2728 , I added a copy of aava1.ttf from s.keyman.com to the .kps files that needed to include it for 17.0.
/release/shared/fonts/tamil/aava1.ttf

TODO - locate the licensing info to distribute that font.

**Comment by LornaSIL** [comment]
I don't think we should include the `aava1.ttf` font. There's no clear license on it. We've specifically been removing fonts that don't have an open license.
These are the only bits of legal information in the font:
```
http://www.gbizg.com/fonts/avarangal.htm (not archived in wayback machine)
Copyright (c) Sinnathurai Srivas, 2000. All rights reserved.
aAvarangal is a trademark of the Sinnathurai Srivas.
```

**Comment by LornaSIL** [comment]
The Tamil Noto fonts are in the shared repo. It might be better to use those.

**Comment by darcywong00** [comment]
ok, since #2479 removes aava1.ttf from the repo, I'll leave it out and close this issue
