### ISSUE TITLE
[sil_boonkit] Windows language tag needs to be nod-Lana-TH

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#276]
Desktop 10.0.1090.0

The current tag `nod` isn't specific enough to download "Northern Thai" from the keyboard beta search.
> No matches found for `l:id:nod`

By manually changing the associated language tag in Keyman Configuration, `nod-Lana-TH` seems to be successful.

**Comment by darcywong00** [comment]
@MakaraSok is prioritizing which issues need to be resolved for 10.0

@mcdurdin Is this correct BCP-47 to require id-script tag?

**Comment by mcdurdin** [comment]
The `Lana` script subtag will definitely be needed. Is there a difference between Northern Thai (Thailand) and Northern Thai (other country)? If not, then the `TH`  subtag is not required.

Note that https://github.com/keymanapp/keyman/issues/886 will probably automatically correct this for recognised language subtags (vast majority of them).

**Comment by DavidLRowe** [comment]
@LornaSIL The .keyboard_info file has `nod-Lana`. Is that enough to close this issue?

**Comment by LornaSIL** [comment]
There is no BCP-47 code or language name in the .kps.
One of us should update the keyboard probably which will entail a tiny bump in version (0.6.2)???
