### ISSUE TITLE
[staging-17.0] Audit examples

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2788]
As examples got migrated from .keyboard_info to .kps files in the staging-17.0 chain, there was some uncertainty on 
https://github.com/keymanapp/keyboards/commit/f73adec0c7ce4ef744531e00783e7056199e3721

where keyboard_info had
```
"text": "𐖑𐖥𐖵𐖣''𐖟",
```

Does that output a single quote?

**Comment by darcywong00** [comment]
Typing the example on
https://keymanweb.com/#sq-vith,Keyboard_vithkuqi

yielded text with single-quote

![image](https://github.com/user-attachments/assets/2924ffe2-f1e8-428e-919f-639cbafb1385)

I'll fix the example in the kps file

**Comment by mcdurdin** [comment]
Note that it looks to me like the name of the script may be wrong there?

**Comment by darcywong00** [comment]
afaict, we're just using the keyboard example @mauriiu provided in the initial creation #2671 

https://github.com/keymanapp/keyboards/blob/997406f4d373873de786d66a61e36fd4f0203a7b/release/v/vithkuqi/vithkuqi.keyboard_info#L22

**Comment by DavidLRowe** [comment]
The text after "Example: To enter" contains two apostrophes. Keystrokes include only one "[". Original had two "[" characters, but was that because the apostrophe was doubled?

**Comment by mcdurdin** [comment]
> Original had two "[" characters

This was the complicated bit -- the `[` needed to be doubled for the encoding of the key string (`[` started a key combination, so as rendered on keymanweb.com it would have had 1 `[` in the key sequence) so it's unclear why the example also had two apostrophes.
