### ISSUE TITLE
bug(fv_nlekepmxcin): Typo in .kps related keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2794]
Typo identified, minor:

```
# fv_nlekepmxcin.clean.diff
### keyboard_info
@ ["related","fv_nlha7kapmxtsin"]
- {"deprecates":false}
@ ["related","fv_nlha7kapxtsin"]
+ {"deprecates":false}
```

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyboards/issues/2423#issuecomment-2143654168_

This depends on #2423 being merged, a minor bug for related keyboard metadata for this keyboard only.

**Comment by LornaSIL** [comment]
@HopsAndHops I think this issue is for this keyboard: `fv_nlekepmxcin` to have the .kps file changed to fix the typo in this line:
`    <RelatedPackage ID="fv_nlha7kapxtsin"/>`
It should be `fv_nlha7kapmxtsin` (add the "m")

Unfortunately, that would require a version bump.

**Comment by HopsAndHops** [comment]
Thanks for notifying me of this Lorna! I'll make that change and push it shortly
