### ISSUE TITLE
chore: check langtags for several keyboards that are returning 'undefined' data

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2798]
```
cs-pinyin	0	NULL	NULL	NULL	undefined
dvorak	qaf	qaf	NULL	NULL	undefined
european2	qaf	qaf	NULL	NULL	undefined
european2	qag	qag	NULL	NULL	undefined
latin_american	qag	qag	NULL	NULL	undefined
nigeria unicode underline	fiz	fiz	NULL	NULL	undefined
tengwar	qaa	qaa	NULL	NULL	undefined
us	qaf	qaf	NULL	NULL	undefined
us_dvorak	qaf	qaf	NULL	NULL	undefined
us_dvorak_lh	qaf	qaf	NULL	NULL	undefined
us_dvorak_rh	qaf	qaf	NULL	NULL	undefined
us_int	qaf	qaf	NULL	NULL	undefined
```

Coming out of #2423 merge.

**Comment by LornaSIL** [comment]
These are all "legacy" keyboards. Most of them are deprecated (except cs-pinyin and tengwar). Do we really want to add language tags to langtags for something that isn't valid? `qaf`, `qag`, `qaa` are all private use aren't they? 
I'm not seeing `fiz` as a valid language code. We did replace "nigeria unicode underline" with `sil_nigeria_underline` and I'm not seeing that as a language code in the new keyboard. I think it was a typo because it's also not in ISO 639-3.

**Comment by LornaSIL** [comment]
So, I see there are still `keyboard_info` files in legacy. I'm happy to remove the pesky language codes from there if that is all that is needed. `cmn` for cs-pinyin is apparently wrong. I would change that to `zh` which is the macro language.

**Comment by LornaSIL** [comment]
@mcdurdin did my PR fix this or is more work needed?

**Comment by mcdurdin** [comment]
Yes that looks good thanks. I think it turns out that that data has always been wrong, and the new tooling is a bit stricter on missing language data. So this is a good cleanup.

**Comment by mcdurdin** [comment]
e.g. https://downloads.keyman.com/keyboards/dvorak/1.0/dvorak.keyboard_info shows:

```json
{
  "id": "dvorak",
  "name": "dvorak",
  "jsFilename": "dvorak-1.0.js",
  "platformSupport": {
    "desktopWeb": "full",
    "ios": "basic",
    "android": "basic"
  },
  "version": "1.0",
  "license": "mit",
  "languages": {
    "en": {
      "displayName": "English",
      "languageName": "English"
    },
    "qaf": {
      "example": {
        "keys": "Kjd xfgiv nos,l ysb",
        "text": "The quick brown fox",
        "note": "\"The quick brown fox\""
      },
      "displayName": "",
      "languageName": ""
    }
  },
  "lastModifiedDate": "2014-03-21T16:22:19Z",
  "encodings": [
    "unicode"
  ]
}
```

**Comment by LornaSIL** [comment]
I fixed it by removing `qaf`, and it's showing properly at https://keyman.com/keyboards/dvorak
So, why is that link still showing `qaf`?

**Comment by mcdurdin** [comment]
> So, why is that link still showing `qaf`?

The files on downloads.keyman.com are permanent, and are uploaded only the first time we release a given version of a keyboard. However, .keyboard_info data that is sent to api.keyman.com (and thence to keyman.com) can be updated whenever we deploy keyboards.
