### ISSUE TITLE
[sil_greek_polytonic] add support for mobile

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2818]
Copied from: https://community.software.sil.org/t/ancient-greek-ios-support/8820/3

---

I think what is happening here is that we resolved a problem in the deployment of keyboards, where some keyboards were being made available to mobile platforms, even if they weren't listed as supporting them (and in some cases didn't work at all on mobile).

The SIL Polytonic Greek keyboard is listed as supporting only ['web' and 'desktop'](https://github.com/keymanapp/keyboards/blob/f63cd02e14f9a9953bc4b72068056e205b3e3e48/release/sil/sil_greek_polytonic/source/sil_greek_polytonic.kmn#L38C18-L38C29) platforms. So OP were effectively using a desktop keyboard on the phone -- it works, but the layout is not optimal.

Obviously, as OP are successfully using the keyboard on their phone, it is not optimal to take it away.

So, I think we'll do this:
- [x] We will patch the keyboard to make it available to mobile platforms again, but without any other changes :link: keymanapp/keyboards#2820
- [ ] Someone (us, OP, anyone!) builds a proper optimized mobile layout for the keyboard

**Comment by darcywong00** [comment]
I can tackle this

> 1. We will patch the keyboard to make it available to mobile platforms again, but without any other changes

Question: currently the kps file has
https://github.com/keymanapp/keyboards/blob/f63cd02e14f9a9953bc4b72068056e205b3e3e48/release/sil/sil_greek_polytonic/source/sil_greek_polytonic.kps#L87

Should I also add mobile fonts?
```xml
      <OSKFont>GentiumPlus-Regular.ttf</OSKFont>
      <DisplayFont>GentiumPlus-Regular.ttf</DisplayFont>
      <WebDisplayFonts><Font Filename="GentiumPlus-Regular.ttf" /></WebDisplayFonts>
```

**Comment by LornaSIL** [comment]
> Should I also add mobile fonts?

It seems that would be useful.

**Comment by DylanCross** [comment]
@mcdurdin Wonderful! Thank you very much!!!
