### ISSUE TITLE
Add published versions by keyboard to avoid having to download the whole repo

### ISSUE THREAD

**Issue by eugenesvk** [keymanapp/keyboards#2956]
If someone wants to build a keyboard, one of the better ways it taking an existing keyboard and editing it. This repo has many such examples, however, it has too many of them, so it's rather huge and thus inefficient to download it whole for just a single example.
There are some tricks to do that, but they're not widely known and thus don't eliminate the issue.

Instead please add a workflow to release artifacts with individual keyboard folders as zipped files

**Comment by DavidLRowe** [comment]
One way to get a zipped folder containing a keyboard is to navigate to the keyboard in the GitHub keymanapp/keyboards repository (for example go to https://github.com/keymanapp/keyboards then navigate to "release", "sil", "sil_euro_latin"), copy the URL (https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_euro_latin for this example), then go to https://download-directory.github.io/ and paste in the URL, then download the resulting zipped file.

**Comment by DavidLRowe** [comment]
See additional comments on cloning a keyboard project: https://github.com/keymanapp/keyman/issues/10166

**Comment by eugenesvk** [comment]
Thanks, these are the tricks I meant, there is also an extension that adds a download button that might be more convenient as it doesn't require visiting a website, but still think this is needless friction

I don't see any comments in the issue you linked, it's empty

**Comment by DavidLRowe** [comment]
Sorry! I was thinking of another issue (https://github.com/keymanapp/keyman/issues/2264). I found this was duplicated by the later issue I mentioned, so I redirected comments to https://github.com/keymanapp/keyman/issues/10166 . I've now added a link to this issue there as well.

**Comment by mcdurdin** [comment]
Thank you for your feedback @eugenesvk.
 
I definitely agree that the whole repo is too large and unwieldy, and adds friction. We have two projects on the boil to mitigate this:

1. Single keyboard repositories -- this technically works today, but we need to quite a lot of work on documentation, review process, and supporting infrastructure (keymanapp/keyman#12014)
2. Tools for cloning keyboards (keymanapp/keyman#2264)

I will go ahead and close this issue as the two projects above should together provide a solid solution. I welcome your comments on either of the above issues.
