### ISSUE TITLE
[sil_euro_latin] Update help for unmodified apostrophe `'`

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyboards#2957]
The EuroLatin  Keyboard help (3.04)  has a lot of diacritics composed by typing a punctuation or symbol before a vowel. It seems these rules are written that if you press the punctuation or symbol key twice, the diacritic  does not appear. But this information is not mentioned in the keyboard help file. 

This is a useful  feature, for example in the French word **l'enfant**. You want apostrophe, then e, not e acute. 

A user who asked this question: https://community.software.sil.org/t/control-when-character-is-inserted/8971

**Comment by mcdurdin** [comment]
Fixed by #3235
