### ISSUE TITLE
Fix custom language codes (Part 2)

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#300]
This is follow-on to #217 for the items that haven't been resolved

> The language codes recorded for a number of keyboards should be improved now that we have BCP 47 instead of straight ISO 639-3:

- [ ] 3. qaf should become en-US (or eliminated, contrast to en?)
  * dvorak
  * european2
  * us_dvorak
  * us_dvorak_lh
  * us_dvorak_rh
  * us_int
  * us
- [ ] 4. qag should probably be eliminated (es-Latin America) or replaced with country-specific codes
  * european2
  * latin_american

## es-Latin America
Per [BCP 47](http://www.rfc-editor.org/rfc/bcp/bcp47.txt) we'd use `es-419`
@mcdurdin tested on Windows, and `es-419` works fine, but `es-419` is recorded as `redundant` in the [language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry). So no further on really.

**Comment by LornaSIL** [comment]
All of these keyboards have been dealt with in recent PRs. The "release" keyboards no longer have qaf or qag and the "legacy" keyboards are all deprecated.
