### ISSUE TITLE
bug: naijatype instruction-keyboard width is too wide, and it is not resizable

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyboards#3043]
The keyboard popup is displaying beyond the screen size, and the texts are not correctly align:
![image](https://github.com/user-attachments/assets/9b9ac76f-607e-4672-bce1-245af5cb0e42)

This is hard to drag if I want to get to the end of the sentence. I would have to drag the header of the keyboard.

Full width: 
![image](https://github.com/user-attachments/assets/7006a62f-3cb7-4a86-b38d-0090800c401e)

Check it out: https://keymanweb.com/#abn,Keyboard_naijatype (I only found this, I'll mention this if there are more keyboards.)

Please make it resizable or scrollable.

If this is a quick fix, I can help get this done. More guidance would be appreciated too!

**Comment by LornaSIL** [comment]
@Meng-Heng does this look okay now?

**Comment by Meng-Heng** [comment]
No, @LornaSIL. The keyboard still look the same.

**Comment by LornaSIL** [comment]
This is how the documentation currently works. I don't think it's a keyboard issue anymore. There is no intention that you could select the text. If a person wants to select text they can go to the help button which takes them to the help documentation. This documentation is just to help them know how to use the web keyboard.

**Comment by mcdurdin** [comment]
We perhaps should close this issue and continue tracking in:
* https://github.com/keymanapp/keyman/issues/12292
