### ISSUE TITLE
[Old Hungarian] [mobile devicess]"ak" symbols alvays produce as small sym.

### ISSUE THREAD

**Issue by kovacshviktor** [keymanapp/keyboards#3048]
1st : The keycode on mobile "aK" and "eK" letterers defined with K_K keycode. On the previous version level "caps" produced "eK" ( 𐲓 )  symbol instead of "aK" ( 𐳔 ).‎
2nd: Now on all level produce small "aK". Is it possible that "aK" symbol got another keycode than K_K?

**Comment by kovacshviktor** [comment]
@DavidLRowe ? Is it possible to make the letter "aK" not be assigned to the K_K key? letter "aK":U+10C94/U+10cd4, letter "eK":U+10c93/U+10c93

**Comment by LornaSIL** [comment]
Instead of using the `K_K` ID you can use the unicode like this `U_10C93`

**Comment by kovacshviktor** [comment]
It's done
