### ISSUE TITLE
[sil_khmer] No mobile layout in source

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#3097]
@Meng-Heng I think you worked on this keyboard last? It seems to indicate that you added a touch layout (see the welcome and help files in the repo). 

However, there is no `sil_khmer.keyman-touch-layout` file in the repo so I am very bewildered! Did you happen to create that file and not commit it?

We do need to make this keyboard have more consistency. If we want to support a mobile layout, it needs `sil_khmer.keyman-touch-layout`. Also, we would need to change the targets to "any".

If we do not want to support mobile, then the documentation will need to be changed to remove references to the mobile and tablet layouts.

**Comment by Meng-Heng** [comment]
Hello @LornaSIL,
I was able to use the keyboard on my phone before the mobile was listed as one of the supported devices, so I added that in there. No touch layout was created. 
If I remember, I was only changing the document to mention what I could type on touch devices and including extra characters that was in the comments in the text editor.
