### ISSUE TITLE
Language Association is sometimes wrong

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#312]
Sometimes Keyman gets confused about what language to associate a keyboard with. For example Khmhmu:
![image](https://user-images.githubusercontent.com/7071907/40732013-f99fd85c-63f7-11e8-9894-555c9a214b50.png)
If I delete Greek through Region and Language Settings (Windows 10)
Then it switches to Arabic:
![image](https://user-images.githubusercontent.com/7071907/40732135-43c5bfc8-63f8-11e8-950c-442af1b14cc4.png)

Delete Arabic and it switches to Yi:
![image](https://user-images.githubusercontent.com/7071907/40732256-872dd1f6-63f8-11e8-867e-b4b158f34b07.png)

The keyboard seems to work fine.
I just upgraded to Keyman Desktop v 10.0.1098.0 but it was doing this before with 10.0.1092.0 (I think).

I haven't been too worried since I'm installing and uninstalling so many keyboards for testing, but I don't know if others have seen this.

**Comment by mcdurdin** [comment]
Moved to keymanapp/keyman#936
