### ISSUE TITLE
bug:(kawi_inscript): Error message about missing .js file

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#3189]
https://keyman.com/keyboards/kawi_inscript
@mcdurdin 

We've got errors that I cannot identify where the problem is.

Use Keyboard online displays:

![image](https://github.com/user-attachments/assets/e4726580-8748-4d53-b13f-fd801ae617ad)

Help file displays:

![image](https://github.com/user-attachments/assets/9f76728c-7fb5-4ee0-aa8c-e88c20ec0212)

**Comment by mcdurdin** [comment]
s.keyman.com deployment has failed. Reaching out to @tim-eves.

**Comment by LornaSIL** [comment]
This appears to have been resolved.

**Comment by mcdurdin** [comment]
Yes, ltops were able to resolve the server issue overnight my time.
