### ISSUE TITLE
[burmese02] User suggestions for improving touch keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#319]
@andjc is the Copyright holder (on behalf of VicNet?) to `/legacy/b/burmese02`

@sdysart has a user that would like to dialog about some improvements

>Do you know who made the current Keyman Android keyboard for Burmese?
>
>It has some left-over English letters on the default and shift layers, 
and there are rare characters on the default layer and common characters 
on the shift layer.
>
>Who should we talk to about improving that?
>
>Thanks,

**Comment by mcdurdin** [comment]
Probably best to document the suggested improvements and add them to this issue which can then be reviewed as the volunteers working on this project have the time.

**Comment by andjc** [comment]
@darcywong00 @sdysart @mcdurdin, the Vicnet Burmese layout did not support touch devices, initially it was Windows only, then had Web (desktop) support added at some point.

@sdysart if you would provide more detailed feedback, I will followup with a version that is more suited to touch devices. The entire layout is old and needs reviewing. And a proper touch implementation needs to be developed.

**Comment by sdysart** [comment]
@andj @darcywong00 @mcdurdin I will have to ask the users of the 
keyboard for more information.  Once I get that I will let you know.

Scott

**Comment by darcywong00** [comment]
It sounding like the touch keyboard will be completely new layout. Maybe instead of updating `burmese02`, this issue creates a new alternate keyboard?

I'm attaching two proposals on behalf of @sdysart 's user.

> basically I try to put all the normal characters on the 
default layer and only punctuation and very rare characters on the shift 
layer.
>
>I would actually prefer my sample #2 but it includes a context sensitive 
rule - my Samsung Burmese keyboard does something like the rule, but I'm 
not sure how difficult it would be to implement in Keyman.
--------------

### Proposal 1
![image](https://user-images.githubusercontent.com/7358010/41456379-7fd0085c-70aa-11e8-8af3-b51b08fa6b42.png)

---------------
### Proposal 2
![image](https://user-images.githubusercontent.com/7358010/41456458-b47d2828-70aa-11e8-8c4a-60b5618bb229.png)

**Comment by andjc** [comment]
@darcywong00 It would either be a new keyboard that deprecates burmese02 or a bump in major version. There is no reason a  touch layout needs to mimic a physical layout and good reasons that the two shouldn''t for certain scripts. But It is probably worth me spending time reanalysing the physical layout as well.

Although both those layouts will be difficult to use on mobile phones with small screens, the space bar.

context sentive rules will be interetsing since they also need to accomodate other characters between the consonant and 102C ... moments like this I wish the keyman language supported soem form of regex.

**Comment by LornaSIL** [comment]
This keyboard has now been deprecated to: https://keyman.com/keyboards/sil_myanmar_my3
So, the sil_myanmar_my3 keyboard should be updated to include a mobile layout and address these issues.

**Comment by DavidLRowe** [comment]
Should we make a note in the "TO DO" section of sil_myanmar_my3/README.md that references this issue, then close this issue?
