### ISSUE TITLE
[eurolatin2] User request to add Cheyenne

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#320]
From [Keyman Community Site](https://community.software.sil.org/t/cheyenne-keyboard-for-android/929)

## Cheyenne keyboard for Android
>Dear coworkers,
>
>The EuroLatin keyboard contains all the characters needed for the Cheyenne language in Keyman for Android. Feel free to add Cheyenne to the list of languages for the EuroLatin keyboard:
>
>http://tavultesoft.com/eurolatin/
>
>I see that Aleut has its own keyboard which looks the same as the EuroLatin keyboard in Keyman for Android. Is it possible for someone on your team to copy the Aleut or EuroLatin keyboard and give it the name Cheyenne so that Cheyenne people can find their language when they look for a Cheyenne keyboard for an Android phone? Also for the iPhone?
>
>The longtime legacy and unicode Keyman keyboards specially designed for Cheyenne continue to work well on PC computers. I don’t know if they have been ported to work on Mac computers.
>
>Thanks,

**Comment by LornaSIL** [comment]
@andjc is working on porting eurolatn to "release"

**Comment by LornaSIL** [comment]
Fixed by #393
