### ISSUE TITLE
bug(sil_jarai): OSK shows tofu

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#3227]
![Image](https://github.com/user-attachments/assets/4e3ae349-3036-469b-aea5-92edce3e2383)

See for example at https://keyman.com/keyboards/sil_jarai?bcp47=jra-khmr

Ref https://community.software.sil.org/t/jarai-jra-khmr-kh-on-screen-keyboard-doesnt-show-all-characters/9474

**Comment by mcdurdin** [comment]
@nnyny can you investigate?

**Comment by Nnyny** [comment]
Noted!

**Comment by Nnyny** [comment]
It seems like the vowels text Unicode have change to U+EF and when I change it back to U+17, the correct display show up. 

![Image](https://github.com/user-attachments/assets/3934e519-1a31-4071-afb2-146d9a224f7e)

**Comment by Nnyny** [comment]
I'm not sure why it suddenly changes like this. The keyboard is using KbdKhmr and Mondulkiri-R font just like Khmer Angkor keyboard.

**Comment by mcdurdin** [comment]
Hmm, this seems strange, yes. We should be using the `&displaymap` function to translate these at compile time, not at source time. Perhaps this was done before `&displaymap` was available? (I can't remember)

**Comment by Nnyny** [comment]
The displaymap is included here:

```
store(&VERSION) '10.0'
store(&NAME) 'Jarai ចារាយ (SIL)'
store(&COPYRIGHT) '© SIL Global'
store(&KEYBOARDVERSION) '1.1.1'
store(&TARGETS) 'any'
store(&VISUALKEYBOARD) 'sil_jarai.kvks'
store(&LAYOUTFILE) 'sil_jarai.keyman-touch-layout'
store(&BITMAP) 'sil_jarai.ico'
store(&DISPLAYMAP) '../../../shared/fonts/kbd/kbdkhmr/KbdKhmr.json'
```

**Comment by mcdurdin** [comment]
> It seems like the vowel Text Unicode has change to U+EF and when I changed it back to U+17, the correct displays show up.

Yes, this is what we need to do for all the problem characters on both the On Screen Keyboard and Touch Keyboard views. The reason this is like this is that the change was made before we supported `&displayMap`.

**Comment by LornaSIL** [comment]
**Some History**
I did a survey of the Khmr keyboards in this PR: https://github.com/keymanapp/keyboards/pull/3168

I believe the only keyboard using `Khmer Busra Kbd` was `sil_jarai`

I am the one who updated sil_jarai in this commit on Oct 30:
Commit: 2650f60f628465a14483fd3f798cf2dcf5200257 [2650f60]

I changed the font from `Khmer Busra Kbd` to `KbdKhmr`
![Image](https://github.com/user-attachments/assets/e6f0c3f1-1b3e-4e8d-9268-abca117207e9)

I added the displaymap at the same time.

I did not realize that the .kvks file was using PUA codepoints. I think if you reimport the .kvks file it will get rid of the PUA codepoints and then it will probably be fine.

**Comment by mcdurdin** [comment]
> I did not realize that the .kvks file was using PUA codepoints. I think if you reimport the .kvks file it will get rid of the PUA codepoints and then it will probably be fine.

The .keyman-touch-layout is also using PUA codepoints, again same reason, this was done before `&displaymap` was in place. I think the touch layout will need to be manually fixed because if we re-import, we lose the layout customizations.

**Comment by LornaSIL** [comment]
@Nnyny do you feel you can make the right changes? I think you can reimport the osk, but you'll have to manually fix the touch layout :( Sorry for that. Let me know if this is too complex.

**Comment by Nnyny** [comment]
Yes, I already fixed it. Please review https://github.com/keymanapp/keyboards/pull/3243.
