### ISSUE TITLE
[FirstVoices] Consolidate keyboards and apps to v10

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#334]
- [ ] Discuss with FV people

**Comment by DavidLRowe** [comment]
There are 33 "fv_" keyboards where the .kps file doesn't have the FollowKeyboardVersion flag set. (See issue #246 .) If and when these keyboards are revised, it would be good to set the FollowKeyboardVersion.

**Comment by LornaSIL** [comment]
@mcdurdin or @darcywong00  was this done with the fv_all PR?

**Comment by mcdurdin** [comment]
I think this is complete.
