### ISSUE TITLE
[infrastructure] Audit JS keyboards that have SMP characters

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#336]
Ensure the KS flag is set in the JS file. (Is this primarily for legacy/ keyboards?)

Some keyboards to check:
- [ ] ancient Greek numbers
- [x] hieroglyphic
- [x] osage
- [ ] osmanya10

**Comment by darcywong00** [comment]
osmanya10 is missing the KS flag

**Comment by LornaSIL** [comment]
@darcywong00 what is a KS flag and what do we need to do to fix it?

**Comment by darcywong00** [comment]
`KS` = 1 for keyboards that have Unicode characters in the SMP

Reference buried in the [keyboard objects](https://help.keyman.com/DEVELOPER/engine/web/10.0/reference/keyboard_properties) table

@mcdurdin wanted to make sure this wasn't missed in some of the older keyboards

**Comment by andjc** [comment]
Is it sufficient to rebuild in current developer version.

**Comment by mcdurdin** [comment]
We really only need to validate the legacy folder -- release folder will be fine with current compiler version as @andjc notes.

Perhaps the best way to validate is to search for SMP characters in the .js. Here's a python script which looks for SMP characters in js files:

```python
import os
import fnmatch
import re

def scan(base):
  directory = os.listdir(base)
  #print('scanning '+base)
  for fname in directory:
    if os.path.isfile(base + os.sep + fname) and fnmatch.fnmatch(fname, '*.js'):
      # Full path
      f = open(base + os.sep + fname, 'r', encoding = 'utf8')
      data = f.read()
      if re.search(r"[\U00010000-\U0010FFFF]", data):
        print('Contains SMP characters: %s' % base + os.sep + fname)
      #else:
      #  print('string not found in file %s' % fname)
      f.close()
    elif os.path.isdir(base + os.sep + fname):
      scan(base + os.sep + fname)


scan(".")
```

When I run on my local repo, I get the following results:

```
Contains SMP characters: .\legacy\o\osmanya10\build\osmanya10.js                                                                                                                  Contains SMP characters: .\release\basic\basic_kbdsora\build\basic_kbdsora.js                                                                                                     Contains SMP characters: .\release\e\easy_chakma\build\easy_chakma.js                                                                                                             Contains SMP characters: .\release\h\hieroglyphic\build\hieroglyphic.js                                                                                                           Contains SMP characters: .\release\o\osage_nation\build\osage_nation.js                                                                                                           Contains SMP characters: .\release\sil\sil_hmd_plrd\build\sil_hmd_plrd.js                                                                                                         Contains SMP characters: .\release\sil\sil_ipa\source\sil_ipa-layout.js
```

Note, the `KS` flag is really for optimisation. KeymanWeb switches into a string-handling mode for SMP which is quite a bit slower than its normal BMP string handling. So if `KS` is not set or set to `0`, then keyboards with SMP characters would not work.

**Comment by mcdurdin** [comment]
And I note that osmanya10.js does *not* have the `KS=1` flag. The others are all fine.

**Comment by LornaSIL** [comment]
@andjc PR #71 was our early attempt to move it to release. I believe there was an issue with versioning? Should we start from that point and figure out what's needed for Osmanya?

**Comment by DavidLRowe** [comment]
What is the status of this issue? It seems that all the keyboards are fine except osmanya10.
- Can we add KS=1 to the .js file and repackage?
- Or do we need to migrate to release?
- or just close this issue?

**Comment by mcdurdin** [comment]
> It seems that all the keyboards are fine except osmanya10.

I think osmanya10 was created by @andjc. Is that correct? If so, he might be able to provide an updated version.

If not, I will take a closer look at mitigation options.

**Comment by mcdurdin** [comment]
> I think osmanya10 was created by @andjc. Is that correct? If so, he might be able to provide an updated version.

And ... I should have read the issue a bit better. I think we go ahead and close this issue. The initial el_osmanya keyboard PR didn't work as @LornaSIL noted, but we should be able to take the bones of that PR and regenerate it?

**Comment by DavidLRowe** [comment]
Closing this issue. If someone wants to open a new issue for the migration of osmanya10 to release, it might be helpful to reference #71 (noted above).
