### ISSUE TITLE
[infrastructure] Add all .js keyboards to package

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#337]
# legacy keyboards
- [ ] georgian

# release keyboards
- [x] ~arabic_izza~ (done)
- [x] balochi_phonetic
- [x] bj_cree_east
- [x] bj_oji_cree
- [x] easy_chakma // (to add on PR #167)
- [x] ekwtamil99uni

// fv append _kmw for .js files
fv_dakelh
fv_denesuline_epsilon
fv_diitiidatx
fv_gitsenimx
fv_gwichin
fv_halqemeylem
fv_han
fv_henqeminem
fv_hlgaagilda_xaayda_kil
fv_kanienkeha_e
fv_ktunaxa
fv_kwakwala
fv_kwakwala_liqwala
fv_migmaq
fv_natwits
fv_nisgaa
fv_nlekepmxcin
fv_nortern_tutchone
fv_nsilxcen
fv_nuucaanul
fv_secwepemctsin
fv_sencoten
fv_shashishalhem
fv_smalgyax
fv_southern_tuchone
fv_statimcets
fv_statlimxec
fv_tagizi_dene
fv_taltan
fv_tsekehne
fv_tsilhqotin
fv_uwikala
fv_xaislakala

- [x] ghana
- [ ] gff_ethiopic_7
- [x] jorai (use jorai.js instead of -layout.js)
- [x] kayan
- [x] kbdsn1
- [x] nw_iranian_latin
- [x] persian_phonetic
- [x] rac_kalasha
- [x] shan
- [x] ~sil_ipa~ (done)
- [x] sil_nubian
- [x] sil_torwali
- [x] tainua
- [x] tem_kdh

**Comment by LornaSIL** [comment]
@darcywong00 do you want us to manually do these or do you have a plan for a way to do this with a script?

**Comment by darcywong00** [comment]
Hmm, this might be too complicated to do with a script.
In addition to adding the JS file to the package, we'd want to make sure applicable font and language tags are associated.

And since we're already editing package files, do we want to add `<FollowKeyboardVersion/>`?  #246

**Comment by DavidLRowe** [comment]
I suspect that the version number would need to be bumped as well? That shows up in README.md, HISTORY.md, xyz.kpj, xyz.kps and perhaps other places as well.

**Comment by mcdurdin** [comment]
Note, my audit just now showed the following .js keyboards in legacy that are not yet in packages:

- [ ] a/armenian_east
- [ ] a/armenian_west
- [ ] a/azeri_latin
- [ ] b/bangla_joy_kab
- [ ] b/bangla_munir_kab
- [ ] b/bangla_probhat_kab
- [ ] b/belgian_comma
- [ ] b/bengali_kab
- [ ] b/bod
- [ ] b/bod_transliterating
- [ ] b/burmese02
- [ ] c/canadian_french
- [ ] c/canadian_french_legacy
- [ ] c/chinese
- [ ] c/comox
- [ ] c/czech
- [ ] c/czech_prog
- [ ] c/czech_qwerty
- [ ] d/danish
- [ ] d/dari_clra
- [ ] d/deneunicode
- [ ] d/dutch
- [ ] d/dvorak
- [ ] e/ekwbamuni
- [ ] e/ekwnewtwuni
- [ ] e/ekwtamil99uniext
- [ ] e/ekwunitamil
- [ ] e/estonian
- [ ] f/faeroese
- [ ] f/faroese
- [ ] f/farsi_kab
- [ ] f/finnish
- [ ] f/french
- [ ] g/gaelic
- [ ] g/german
- [ ] g/german_ibm
- [ ] g/greek
- [ ] g/greek_220
- [ ] g/greek_220_latin
- [ ] g/greek_319
- [ ] g/greek_319_latin
- [ ] g/greek_latin
- [ ] g/greek_polytonic
- [ ] g/greenlandic
- [ ] g/gujarati_kab
- [ ] gff/gff_awn_7
- [ ] gff/gff_bcq_7
- [ ] gff/gff_mym_7
- [ ] gff/gff_sgw_7
- [ ] h/har10
- [ ] h/harethi11
- [ ] h/hebrew
- [ ] h/helabasauni
- [ ] h/hindi_modular_kab
- [ ] h/hungarian
- [ ] h/hungarian_101
- [ ] i/icelandic
- [ ] i/irish
- [ ] i/italian
- [ ] i/italian_142
- [ ] j/japanese
- [ ] k/kannada
- [ ] k/kannada_kab
- [ ] k/klallam2
- [ ] k/korean_rr
- [ ] l/latin_american
- [ ] l/latvian
- [ ] l/latvian_qwerty
- [ ] l/lithuanian_ibm
- [ ] m/malayalam
- [ ] m/malayalam_kab
- [ ] m/maltese_47
- [ ] m/maltese_48
- [ ] m/maori
- [ ] m/marathi
- [ ] m/marathi_kab
- [ ] n/nasuni
- [ ] n/norwegian
- [ ] n/norwegian_sami
- [ ] o/osmanya10
- [ ] p/polish
- [ ] p/polish_214
- [ ] p/polish_prog
- [ ] p/portuguese
- [ ] p/ps32
- [ ] p/punjabi_kab
- [ ] r/rawangu
- [ ] r/romanian
- [ ] s/sami_finland_sweden
- [ ] s/sami_norway
- [ ] s/serbian_latin
- [ ] s/sliammon
- [ ] s/slovak
- [ ] s/slovak_qwerty
- [ ] s/spanish
- [ ] s/spanish_var
- [ ] s/swedish
- [ ] s/swiss_german
- [ ] s/syriac
- [ ] s/syriac_phon
- [ ] t/tamil
- [ ] t/tamil_kab
- [ ] t/tamil99m
- [ ] t/telegu_kab
- [ ] t/thai_kedmanee
- [ ] t/thai_kedmanee_nsl
- [ ] t/thai_pattachote
- [ ] t/thai_pattachote_nsl
- [ ] t/tir_er_uni_ez
- [ ] t/tir_et_uni_ez
- [ ] t/tkmcaus3
- [ ] t/turkish_f
- [ ] t/turkish_q
- [ ] u/uk
- [ ] u/uk_extended
- [ ] u/urdu_kab
- [ ] u/us_dvorak
- [ ] u/us_dvorak_lh
- [ ] u/us_dvorak_rh
- [ ] u/us_int
- [ ] v/vietnamese
- [ ] v/vietweb11
- [ ] v/visual_media_tamil_modular
- [ ] v/visual_media_tamil_typewriter
- [ ] x/xaadkil
- [ ] y/yorubabar
- [ ] y/yorubadot

This has become more urgent with the change to the Keyman site to no longer list .js files for download in the apps.

**Comment by LornaSIL** [comment]
@makara has been assigned 50 of the Windows keyboards and I've got about 36 Windows keyboards left. That's the majority of what you've listed. If he could make them a priority that would be good. I'm planning to complete mine by the end of December if possible.

The others are complicated and may require some discussion after I'm available again. For instance, the kab keyboard author doesn't even want his keyboards listed anymore. It's possible they could be deprecated as they are based on a standard layout that we have other keyboards that support the same layout.

**Comment by mcdurdin** [comment]
That list I realise isn't complete; there are no doubt packages there that include .kmp and .js where the .js hasn't made its way into the package.

**Comment by mcdurdin** [comment]
Yep. I think many of the KAB keyboards could probably be marked deprecated. Or we could remove them as many of them are not really in use (gosh it would be good to be collecting usage stats... task for another day)

**Comment by mcdurdin** [comment]
I expect many of these keyboards are not really used. But we just don't have the stats to know at this point :(

**Comment by LornaSIL** [comment]
If you have a way to get stats let me know. Otherwise, I can use the spreadsheet from 18-24 months ago to prioritize. But, I'm not expecting to be able to work this week. I may start working for short periods the following week.

**Comment by mcdurdin** [comment]
We don’t currently collect the stats in a useful way. Collecting stats is on our radar.

**Comment by LornaSIL** [comment]
@mcdurdin you mention this is more important now.  I'd like to understand the timing and expectations better. I'm working on them as quickly as I can, but if it's urgent, we will need Makara prioritized to help.

**Comment by mcdurdin** [comment]
The reason it is more important than previously is that the keyman.com site now only shows the .kmp install link. However, the in-app selector still downloads the old .js version, for now. This will change with version 14.0 -- from there on we will only download .kmp versions.

I could write a script that generated a .kps and thus .kmp, as is, in the legacy folder, to take the pressure off. I don't think it would be a huge amount of work but the results wouldn't be perfect.

**Comment by mcdurdin** [comment]
It can be challenging to keep on top of the various requirements for platform support. While the .keyboard_info data generally does a good job, and kmcomp is pretty good at filling in the gaps, the edge cases still sometimes trip me up.

Good news:
* we now collect stats on keyboard downloads.
* keymanapp/keyman#2334 fixes metadata which incorrectly made some keyboards available to mobile apps.

Bad news:
* Still got to sort out the rest of these keyboards to finalise the .js -> .kmp transition and I won't get that finished today!

**Comment by LornaSIL** [comment]
>we now collect stats on keyboard downloads.

Where can I find the stats? Or is it too new to be useful?

**Comment by mcdurdin** [comment]
The stats are available through Google Analytics but they've only been going a couple of days... so we should wait a little while to get clarity.

**Comment by mcdurdin** [comment]
Yesterday's stats (incomplete because we still aren't capturing all of the mobile events -- that will come later):

![image](https://user-images.githubusercontent.com/4498365/68807141-661c4080-06bb-11ea-8539-0ed57f73093b.png)

**Comment by LornaSIL** [comment]
I think these are the remaining 51:

- [ ] b/bod
- [ ] b/bod_transliterating
- [ ] b/burmese02
- [ ] c/chinese
- [ ] c/comox
- [ ] d/dari_clra
- [ ] d/deneunicode
- [ ] e/ekwbamuni
- [ ] e/ekwnewtwuni
- [ ] e/ekwtamil99uniext
- [ ] e/ekwunitamil
- [ ] g/greek_220_latin
- [ ] g/greek_319_latin
- [ ] g/greek_latin
- [ ] gff/gff_awn_7
- [ ] gff/gff_bcq_7
- [ ] gff/gff_mym_7
- [ ] gff/gff_sgw_7
- [ ] h/har10
- [ ] h/harethi11
- [ ] h/helabasauni
- [ ] h/hindi_modular_kab
- [ ] h/hungarian
- [ ] i/icelandic
- [ ] i/irish
- [ ] j/japanese
- [ ] k/klallam2
- [ ] k/korean_rr
- [ ] l/latvian
- [ ] l/latvian_qwerty
- [ ] n/nasuni
- [ ] n/norwegian
- [ ] n/norwegian_sami
- [ ] o/osmanya10
- [ ] p/polish_prog
- [ ] p/ps32
- [ ] r/rawangu
- [ ] s/sami_finland_sweden
- [ ] s/sami_norway
- [ ] s/sliammon
- [ ] s/slovak
- [ ] s/slovak_qwerty
- [ ] s/swiss_german
- [ ] t/tkmcaus3
- [ ] u/uk_extended
- [ ] v/vietweb11
- [ ] v/visual_media_tamil_modular
- [ ] v/visual_media_tamil_typewriter
- [ ] x/xaadkil
- [ ] y/yorubabar
- [ ] y/yorubadot

**Comment by LornaSIL** [comment]
@mcdurdin @darcywong00 for the keyboards we don't have enough information to move to "release"... I added a .kpj and .kps file assuming the build system would build a .kmp. Was that a wrong assumption? 

For example https://github.com/keymanapp/keyboards/tree/master/legacy/b/bod | https://keyman.com/keyboards/bod Do I need to actually add the .kmp to the source folder?

**Comment by mcdurdin** [comment]
> Do I need to actually add the .kmp to the source folder?

The 'legacy' keyboards should not have any source files added to them. They are there so we don't lose distribution of them, and they are treated specially -- just a .js or .kmp.

If we add source files, they should either go to experimental, or release, as then they are treated as under maintenance. So in this case, I'd put it in experimental with a note in the readme as to why it's there rather than release.

At distribution point, all three categories are treated identically -- there is no differentiation in the way it's presented to the end user. So while 'experimental' might feel a little weird, I think it works okay.

**Comment by LornaSIL** [comment]
@mcdurdin 

> If we add source files, they should either go to experimental, or release, as then they are treated as under maintenance. So in this case, I'd put it in experimental with a note in the readme as to why it's there rather than release.

So, I tried that and the error on TeamCity says `Could not find output file build/bod.js` even though my kps is calling for `source/bod.js`. (https://github.com/keymanapp/keyboards/pull/1170)

So, I think I should just commit the kmp into the legacy folder? I don't know what else to try.

If I commit the kmp...do I keep the .kpj and .kps files that I used to create them in the repo, or do I throw them out.

**Comment by mcdurdin** [comment]
Oh I see -- I thought you were building bod from some source files. My bad. Yes, then in this situation just add the compiled .kmp to the legacy/ folder, and might as well put the .kpj and .kps in as well with a note. Of note here is that we can't (easily) change version number in the .js (and this is worse in the .kmx) so we'll be stuck with the existing version.

**Comment by LornaSIL** [comment]
> Oh I see -- I thought you were building bod from some source files. My bad. Yes, then in this situation just add the compiled .kmp to the legacy/ folder, and might as well put the .kpj and .kps in as well with a note. Of note here is that we can't (easily) change version number in the .js (and this is worse in the .kmx) so we'll be stuck with the existing version.

Do I need to add `    "packageFilename": "bod.kmp",` to the keyboard_info? At least at the time of writing this the bod keyboard isn't showing the .kmp. https://keyman.com/keyboards/bod
I really don't know what else to do.

**Comment by LornaSIL** [comment]
I think these are the remaining 23:

- [ ] e/ekwbamuni
- [ ] e/ekwnewtwuni
- [ ] e/ekwtamil99uniext
- [ ] e/ekwunitamil
- [ ] h/helabasauni
- [x] k/korean_rr
- [ ] v/visual_media_tamil_modular
- [ ] v/visual_media_tamil_typewriter

FV
- [ ] c/comox
- [ ] k/klallam2
- [ ] n/nasuni
- [ ] s/sliammon
- [ ] x/xaadkil

Daniel Yacob:
- [ ] gff/gff_awn_7
- [ ] gff/gff_bcq_7
- [ ] gff/gff_mym_7
- [ ] gff/gff_sgw_7

Andrew Cunningham
- [ ] d/dari_clra
- [ ] h/har10
- [ ] h/harethi11
- [ ] o/osmanya10
- [ ] p/ps32
- [ ] v/vietweb11

**Comment by mcdurdin** [comment]
Over the weekend I located some old backups and found some additional source files! As usual these may need work... but may help us for deciding what we do with these keyboards. I've messaged a private link to you, @LornaSIL.

**Comment by DavidLRowe** [comment]
@mcdurdin Can you clarify the timing on this issue? When do these need to be completed (to fit with the deployment of version 14)? @LornaSIL has done most of the ones on your list, but some are waiting on others.

Outstanding keyboards:
- fv keyboards, now managed by @madebybridget 
- some keyboards submitted by @dyacob and @andjc who wanted to deal with their own keyboards
- legacy/h/helabasauni 
- others?

**Comment by mcdurdin** [comment]
The timing for this is linked to the release of Keyman 14, which is scheduled for around the end of this year. Keyboards which are not packaged will not be available for mobile use. So it's not disastrous if a handful of keyboards are not available before Keyman 14 is released; we can always fix them as requested by the community for the less-used ones.

**Comment by andjc** [comment]
In my case, the keyboards in question were never designed and optimised for
touch layouts so will need a complete review and in some cases a redesign.

Will try to get to it soon, but depends on other factors my timelines have
been thrown out of wack.

Andrew

**Comment by andjc** [comment]
I know, but they are layouts I never created mobile layouts for, so would
prefer to go through each to see if the existing files are suitable and
match desktop versions, or whether more work needs to go into them.

In some cases the js versions are divergent and not a good fit, or reflect
older versions of the layout.

**Comment by mcdurdin** [comment]
@andjc no worries. That work can happen independently of this particular effort, which is basically just to maintain status quo. I'd prefer to look at improvements as separate parcels of work, which can happen in a timeframe which works for you and doesn't have to be tied to a release date for Keyman.

**Comment by andjc** [comment]
Problem is that in certain cases the js file is based on a different
version from kmp file and in at least one case may reflect a different
orthography. So should not be bundled together.

**Comment by mcdurdin** [comment]
@andjc which keyboards are in this situation?

**Comment by LornaSIL** [comment]
Remaining keyboards listed in #1293
