### ISSUE TITLE
[isis_bangla] User from community site wishes to update keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#338]
Reference: https://community.software.sil.org/t/bengali-isis-keyboard-missing-characters/425/3

- [ ] Follow-up and obtain permission from original author
- [ ] Update keyboard accordingly

**Comment by LornaSIL** [comment]
So far we have not been able to get permission to move any of these keyboards to MIT.

**Comment by LornaSIL** [comment]
New itrans_bengali keyboard supports the characters requested. I'm checking to see if the itrans keyboard will work for the user.

**Comment by LornaSIL** [comment]
The itrans_bengali keyboard supports the need.
