### ISSUE TITLE
[khmer_angkor] Keyboard font on iOS doesn't show coeng characters on longpress

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#350]
The default iOS font for Khmer does not show isolated coeng characters for Khmer with the Khmer Angkor keyboard khmer_angkor version 1.0.3:

![38217](https://user-images.githubusercontent.com/4498365/41530549-c7212138-731a-11e8-8a8c-cce312af6032.jpg)

On Android, it does display correctly with the system font:

![screenshot_20180609-205753](https://user-images.githubusercontent.com/4498365/41530588-dc2b70c4-731a-11e8-92ce-6831fea7a656.png)

Adding Khmer Mondulkiri font to the package (and setting the keyboard font as appropriate) increases file size by a few hundred KB but does resolve the issue:

![image](https://user-images.githubusercontent.com/4498365/41530665-1b3948cc-731b-11e8-8f4b-cc7162188cc1.png)

We currently don't support setting the font per platform so this would mean that Khmer Mondulkiri would be shown also for Android. Not sure if this is ideal:

![image](https://user-images.githubusercontent.com/4498365/41530893-c19e908c-731b-11e8-9e11-6bead44a34ec.png)

**Comment by MakaraSok** [comment]
fixed by adding Mondulkiri font to the package at #310

**Comment by DavidLRowe** [comment]
@MakaraSok Can you verify that this (issue 350) is fixed by your #310 ? If so, this issue can be closed. Thanks!

**Comment by MakaraSok** [comment]
Fixed
