### ISSUE TITLE
Deprecated keyboards are still shown in Keyman mobile apps but not distinguished from new versions

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#374]
Per https://community.software.sil.org/t/setting-keyboard-names-for-android/1057/3

There's no way to display the keyboard filename in the app. The gff_amh_7 keyboard is deprecated. In the keyboard catalogue it is shown as deprecated but we don't have any API yet to pass that information on to the Keyman apps.

The best way forward for now I think is for us to rename deprecated keyboards in the keyboards repository, e.g. "Amharic (old version 1.4)". (Use 'old version' as opposed to 'deprecated' because 'deprecated' is a technical term that many people won't understand.)

**Comment by LornaSIL** [comment]
If we rename keyboards won't this require us to change the version number or how do we handle this?

**Comment by mcdurdin** [comment]
I've opened an issue to resolve this in the API and backend for api.keyman.com. Closing here.
