### ISSUE TITLE
[easy_chakma] The Touch Keyboard Gives an Error When Installed on Android

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#383]
The keyboard is built successfully, but when installing the package, an error popped up (see the screenshot).
![image](https://user-images.githubusercontent.com/28331388/42289590-90aba952-7fea-11e8-9847-feb2e1fb8d73.png)

I think there may be an issue with the script tag. Chakma script is probably not yet supported on android.

However, the keyboard is working OK on windows and web for mobile.

**Comment by LornaSIL** [comment]
The language name is just "Chakma" not Keyman suggests "Chakma (Chakma, Bangladesh)"

I have no idea what else the problem might be. We'll have to look at it tomorrow.
I don't understand why "_easy_chakma" is part of the keyboard name.

**Comment by MakaraSok** [comment]
When leaving only "ccp" in the BCP47 tag, the package asks for "ccp-Latn" instead of "ccp-Cakm". (see the screenshot below)

![image](https://user-images.githubusercontent.com/28331388/42297389-503b3b28-8029-11e8-950f-d45aa3cf5826.png)

**Comment by mcdurdin** [comment]
Okay, there is probably an issue here with the Keyman app. I will debug this. It may be related to the script tag but I don't think so.

**Comment by LornaSIL** [comment]
@MakaraSok do you know if this was resolved with your latest update to the keyboard?

**Comment by MakaraSok** [comment]
Yes. This has been fixed, and the issue was with the Keyman for Android, not the keyboard itself.
