### ISSUE TITLE
Typing አዕምሮ on gff_amh_7 keyboard is difficult

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#40]
I am using the Amharic fonts and I have hard time to script the word አዕምሮ. After I write አ to write ዕ when I press e twice it changes the first letter አ to ኧ. I tried reading the manual and using ' to keep the letter not to change with the vowels but it does not work for me. I would like to write without any interruption and editing. So, if you have any idea please help...

Response from myself: The best I can suggest right now is to type a'eemro and then go back and delete the apostrophe (') mark.

https://secure.tavultesoft.com/forums/topic.php?ForumTopicID=488&ForumPostID=1643

**Comment by dyacob** [comment]
I'm a little confused by this one.  The apostrophe should not appear following a vowel, unless truck twice.  I do the issue described for Amharic at the keyman web site.  On my home laptop, with Keyman Desktop 9, loading the gff-amh-7.kmx (built with Keyman 7), I see not issue, it works as expected.

Could a problem with apostrophe have crept in when the .kmn file was recompiled with a newer keyman?  If so, I should carve out time to review they keyboard sources carefully under KM9.

Just a linguistic note here that having to type apostrophe is unfortunate (when two vowels occur in sequence), its a trade off for having the convenience of being able to type vowels with a single keystroke against the infrequent occurrences of two vowels in sequence (አዕምሮ is a borrowed word from Ge'ez). Also a consequence of Ethiopic having more vowels than English.

**Comment by mcdurdin** [comment]
I took some time to compare ftp://ftp.geez.org/pub/keyboards/Keyman/7.0/keyboard-source/gff-amh-7.kmn with this keyboard. There are some differences -- it appears that the sources diverged at some point because while this version includes additional code around KeymanWeb and cross-platform, there are also a number of other changes which don't make sense to me, and suggest that this version came from an older version of the one on ftp.geez.org. @dyacob would you mind doing a comparison? I would certainly accept a PR.

**Comment by dyacob** [comment]
@mcdurdin i'll be happy to evaluate and update the input methods against the current keyman, and create a PR. i'm long overdue to do this. however, i'm going to have wait for some time to free up, which may not be until the Easter holiday period.

**Comment by mcdurdin** [comment]
That sounds great; I look forward to hearing from you!

**Comment by dyacob** [comment]
This issue has been addressed in v1.5 of the gff_amharic keyboard. The sequence "a'eemro" will produce "አዕምሮ".  Previously apostrophe after "a" (አ) was not recognized, the sequence "ae" maps map to "ኧ" which also interfered.

**Comment by DavidLRowe** [comment]
fixed by #302
