### ISSUE TITLE
[khmer_angkor] The Subscripts in the Long Press Disappear in iOS11

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#436]
![image](https://user-images.githubusercontent.com/28331388/44699264-9cb56d80-aaad-11e8-9a71-775a2ae3c0af.png)

**Comment by darcywong00** [comment]
@jahorton Does keymanapp/keyman#1407 fix this?

**Comment by jahorton** [comment]
It'll fix it within KMW, but not within the Keyman app.  That'll need a separate PR, which I'll base off #1407 once it's properly reviewed.  (I plan to use the same approach, and it's also needed for the base keyboard within the apps.)
