### ISSUE TITLE
Proposing alternate version of EuroLatin keyboard for Paratext users

### ISSUE THREAD

**Issue by sewhite** [keymanapp/keyboards#449]
Peter Knapp says the keyboard cannot be used in Paratext because Paratext reacts to the \ key by popping up the marker list. I made a version of the keyboard that uses ] instead of \. I submitted a pull request (#448)  to add this to the repository but it was denied. A repository maintainer needs to do this.

**Comment by LornaSIL** [comment]
@mcdurdin I see a couple of ways forward.
* Add the new keyboard. Call it *EuroLatin??? (SIL)* (not anything to do with Paratext, keyboards should not just be for one app IMO).
     * The downside is we have to maintain two almost identical keyboards.
* Change the existing keyboard to use ```]``` instead of ```\```. 
     * What would be the negatives to that? Users would need to learn a new way of typing.
* Add a second way to type using both ```]``` *and* ```\``` to get the same characters.
     * I guess the only downside would be that we need to add a way to access the square bracket?

My own preference is the last one. What do you think we should do?

**Comment by mcdurdin** [comment]
So, a few questions:

* How many people are experiencing this problem? 
* How many other keyboard layouts will have this problem with Paratext? There are plenty that use the backslash key. 
* Do we need to put this keyboard into the repository? Can we just give the @sewhite's kmp directly to Peter?
* Is it possible to configure Paratext to not override a base input key (IMO that can be considered a bug or at least an accessibility/i18n defect)? Could we involve the PT developers in this issue?

If we do decide to go ahead and I think @DavidLRowe's suggestion is most appropriate, using keyboard options (aka [variable stores](https://help.keyman.com/developer/language/guide/variable-stores)).

Side note: Steve, the message "Keyboards: This pull request is not from a keyboards maintainer and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR." is denying the Pull Request, just not building and testing it automatically.

**Comment by sewhite** [comment]
I have shared the keyboard with Peter. I also submitted it here because the source file said if anyone made a modification they were invited to share it with others on tavultesoft. So I thought I would notify the repository owners of what I had done if they wanted to include it or not.

**Comment by LornaSIL** [comment]
The options dialog in the keyboard allows RAlt or RCtrl so it is not necessary to use "\".
