### ISSUE TITLE
[multiple] Investigate expanding &TARGETS store from 'windows'

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#450]
Found during verification of keymanapp/keyman#1158

@andjc  and @LornaSIL 

Is it possible for the following keyboards to expand their [&TARGETS](https://help.keyman.com/developer/language/reference/targets) store from `'windows'` to `'windows macosx linux'`?

- [ ] el_naija
- [ ] sil_cameroon_azerty
- [ ] galaxie_greek_mnemonic
- [ ] sil_hebrew
- [ ] sil_tai_dam
- [ ] sil_tai_dam_lao
- [ ] sil_yupik_cyrillic

**Comment by andjc** [comment]
@darcywong00

For el_naija I would prefer not to add macosx. I prefer a slightly different behaviour for MacOS keyboards compared to Windows. I am planning on updating this keyboard to provide cross platform support and review languages.

Regarding Linux: will Linux support all rules in Windows?

What is current support for european style keyboard mnemonic layouts on Linux and Mac OS?

**Comment by mcdurdin** [comment]
Version 11 will support macOS and Linux; it will aim to support all desktop platforms equally, including at least some support for mnemonic layouts (may be limited to a subset of European languages for Linux and macOS initially). Version 10 does not support mnemonic layouts on macOS (and definitely not in KMFL).

**Comment by LornaSIL** [comment]
I've asked @JBrase to do the last 3. I'll do cameroon to hebrew.

**Comment by LornaSIL** [comment]
How were these keyboards chosen? I see other keyboards that only support Windows. Especially,
* kayan
* sil_boonkit

Also, some or all of gff ones.

**Comment by darcywong00** [comment]
> How were these keyboards chosen?

When I was validating keymanapp/keyman#1158 I was comparing the generated keyboard_info files with what was on api.keyman.com at the time.

For the keyboards above, the "new" keyboard_info files didn't list "macos" because the kmn didn't have it as a target. But previous keyboard_info files listed "macos" as fully supported.

**Comment by LornaSIL** [comment]
We did all of these except for el_naija as the author does not want that one to be macOS. Can we close this issue?

**Comment by mcdurdin** [comment]
Agree.

**Comment by darcywong00** [comment]
Fixed by #452 and #453
