### ISSUE TITLE
fv_hailzaqvla and fv_yukon plus possibly others. Canonical ordering of diacritic marks

### ISSUE THREAD

**Issue by alex-fpcc** [keymanapp/keyboards#485]
In the FirstVoices keyboard app on iPhone. After upgrading to ios 11 the are symbols that are now in the wrong place.  This is for the  Haíɫzaqvḷa keyboard. 

For example - ṃ́ ḷ́ ṇ́ ṇ̓ ṃ̓ ḷ̓ 
the second symbol under the “.” Is supposed to be over the letters. 
Feedback From Rory Housty <rhousty@gmail.com>
This seems to be a font issue in iOS 11&12 as my iPad running ios 9 is still working fine.
Characters are displayed correctly in the keyboard button but when typed one of the marks moves bellow the other one.

From Marc:

> I've tested this here and it appears to be a renderer change in iOS 11 with multiple marks: the keyboard is incorrect because the dot-below should be before the mark above in the text store for canonical ordering. If you manually insert them in the right order they display correctly.
> 
> Earlier versions of iOS were less pedantic about this but it the keyboard as it stands is technically incorrect.
> 
> It is not a complex change to the keyboard but would involve putting out an update to the FV app. On the Keyman side, the process is now to submit a pull-request to the Keyman keyboards repository at https://github.com/keymanapp/keyboards with a corrected keyboard. The fix goes out to the Keyman app automatically when the change is approved.
>

**Comment by alex-fpcc** [comment]
Is there an easy way for me to tell all of the keyboards that are affected by this?

So far I know it is the haizla and all of the Yukon keyboards.

**Comment by DavidLRowe** [comment]
Here's an attempt to look for U+0323 (combining dot below) in the FirstVoices keyboards in the Keyman keyboards repository under `release`, using `grep` from command line in Ubuntu. This is not exhaustive (and may not even be the best way to search!). Result is `<filename>:<number of occurrences>`

Look for U+0301 U+0323 sequence (wrong canonical ordering):
```
  grep -r -c -H  $'\u0301\u0323' fv*/source/*.kmn
fv_hailzaqvla_kmw/source/fv_hailzaqvla_kmw.kmn:6
fv_nlekepmxcin_kmw/source/fv_nlekepmxcin_kmw.kmn:6
fv_stlatlimxec_kmw/source/fv_stlatlimxec_kmw.kmn:40
```
Look for U+0313 U+0323 sequence (wrong canonical ordering):
```
  grep -r -c -H  $'\u0313\u0323' fv*/source/*.kmn
fv_hailzaqvla_kmw/source/fv_hailzaqvla_kmw.kmn:6
fv_stlatlimxec_kmw/source/fv_stlatlimxec_kmw.kmn:10
```
Look for any occurrence of U+0323:
```
  grep -r -c -H  $'\u0323' fv*/source/*.kmn
fv_dakota_mb_kmw/source/fv_dakota_mb_kmw.kmn:24
fv_diitiidatx_kmw/source/fv_diitiidatx_kmw.kmn:6
fv_diitiidatx/source/fv_diitiidatx.kmn:7
fv_hailzaqvla_kmw/source/fv_hailzaqvla_kmw.kmn:18
fv_nexwslayemucen_kmw/source/fv_nexwslayemucen_kmw.kmn:2
fv_nlekepmxcin_kmw/source/fv_nlekepmxcin_kmw.kmn:48
fv_nsilxcen_kmw/source/fv_nsilxcen_kmw.kmn:4
fv_nuucaanul_kmw/source/fv_nuucaanul_kmw.kmn:8
fv_nuucaanul/source/fv_nuucaanul.kmn:8
fv_stlatlimxec_kmw/source/fv_stlatlimxec_kmw.kmn:92
```
Look for the literal string "U+0323"
```
  grep -r -c -H  'U+0323' fv*/source/*.kmn
fv_gwichin_kmw/source/fv_gwichin_kmw.kmn:1
fv_gwichin/source/fv_gwichin.kmn:1
fv_han_kmw/source/fv_han_kmw.kmn:1
fv_han/source/fv_han.kmn:1
fv_nlekepmxcin_kmw/source/fv_nlekepmxcin_kmw.kmn:4
fv_nlekepmxcin/source/fv_nlekepmxcin.kmn:4
fv_northern_tutchone_kmw/source/fv_northern_tutchone_kmw.kmn:1
fv_northern_tutchone/source/fv_northern_tutchone.kmn:1
fv_nsilxcen_kmw/source/fv_nsilxcen_kmw.kmn:2
fv_nsilxcen/source/fv_nsilxcen.kmn:2
fv_nuucaanul_kmw/source/fv_nuucaanul_kmw.kmn:2
fv_nuucaanul/source/fv_nuucaanul.kmn:2
fv_southern_tutchone_kmw/source/fv_southern_tutchone_kmw.kmn:1
fv_southern_tutchone/source/fv_southern_tutchone.kmn:1
fv_stlatlimxec_kmw/source/fv_stlatlimxec_kmw.kmn:2
fv_stlatlimxec/source/fv_stlatlimxec.kmn:2
fv_tagizi_dene_kmw/source/fv_tagizi_dene_kmw.kmn:1
fv_tagizi_dene/source/fv_tagizi_dene.kmn:1
fv_uwikala_kmw/source/fv_uwikala_kmw.kmn:2
fv_uwikala/source/fv_uwikala.kmn:2
```

**Comment by DavidLRowe** [comment]
@alex-fpcc Currently @LornaSIL is merging the web and desktop versions of a number of FirstVoices keyboards. One of these is fv_han (#489 ). For this one, she noted in the README.md under the "To do" section that there is an issue with reordering of diacritics.

**Comment by LornaSIL** [comment]
See also #492

**Comment by LornaSIL** [comment]
I think we've handled everything we are aware of.
