### ISSUE TITLE
[lahu] User request for touch layout

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#488]
@sdysart has a user requesting a touch keyboard for Lahu.

We could update an existing [https://keyman.com/keyboards/lahu](Lahu) keyboard  and add the touch layout.

### TODO ###
- [x] Get permission from the original keyboard author

**Comment by LornaSIL** [comment]
@sdysart we've added a touch layout with permission of the author. As soon as it builds it should be available here: https://keyman.com/keyboards/lahu
