### ISSUE TITLE
[sil_cameroon_qwerty] CSS styling precision

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyboards#553]
Styling Question

In this discussion:
https://community.software.sil.org/t/advanced-re-styling-of-mobile-keyboards-with-css/874/8
@mcdurdin recommended limiting the styles to only the current keyboard, but I never got styling to work unless the CSS pointed to a specific class or key on ALL keyboards. I'm doubtful that CSS included with a keyboard would affect all installed keyboards, but I can't find another KB using the deadkey style to test it.

https://github.com/keymanapp/keyboards/blob/356b89e6f23cf500dc35669bd2674575c77b0095/release/sil/sil_cameroon_qwerty/source/sil_cameroon_qwerty.css#L18

 If this is truly a problem, could someone update (and test) the enabled CSS rules with .kmw-keyboard-sil_cameroon_qwerty (and on .kmw-keyboard-sil_cameroon_azerty) on the deadkey and diacritics to make sure that it still works. 

Also, I was hoping to have all vowels (both static keys and popup keys) in yellow (the commented section of the CSS). I was able to test styling the static keys, but it seems I couldn't recolor a popup key. is that still true?

**Comment by mcdurdin** [comment]
> I'm doubtful that CSS included with a keyboard would affect all installed keyboards, but I can't find another KB using the deadkey style to test it.

It is definitely important to make sure that the CSS is targeted at a specific keyboard. Although you only see one keyboard visible at a time, multiple keyboard layouts will stay loaded, and the CSS can impact other keyboards. This is true both for the mobile apps and for KeymanWeb.

**Comment by erros84** [comment]
Thanks. From the outside, it seems like sandboxing would be more efficient as I can imagine a lot of duplication and some errors like mine, but I guess much of the risk is mitigated as you control the input to the system. 

Restricting CSS needs to be on the checklist for approvers, and it needs to be fixed on my keyboards, As I said, I never found a combination that worked properly locally, so I couldn't implement the change myself. I welcome some help to see what I was getting wrong (on the implemented styling and maybe a suggestion on the the colored vowels keys and popups I hope to have).
https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_cameroon_azerty
and
https://github.com/keymanapp/keyboards/tree/master/release/sil/sil_cameroon_qwerty

**Comment by erros84** [comment]
@darcywong00, I'm testing updated CSS as above in KMD11, but not having much luck when adding sil_cameroon_qwerty.
Results:
.ios #default-T_0300 does work, but 
.kmw-keyboard-sil_cameroon_qwerty .ios #default-T_0300 does not work in testing.

.kmw-keyboard-sil_cameroon_qwerty .phone.ios .kmw-key.kmw-key-deadkey seems to work

What is the proper CSS target for: 
sil_cameroon_qwerty + iOS + #default-T_0300
and
sil_cameroon_qwerty + android + #default-T_0300

**Comment by erros84** [comment]
I figured it out. I had the order wrong.  
android .kmw-keyboard-sil_cameroon_qwerty #default-T_0300
