### ISSUE TITLE
Keyman 10.0 is not working in windows 8.1

### ISSUE THREAD

**Issue by rachitralli** [keymanapp/keyboards#578]
I am working on Desktop Windows 10 and laptop Windows 8.1, while working in Windows 8.1 an error occurred and keyman developer stopped working and closed authomatically. Now I am unable to edit in keyman developer 10.0 in windows 8.1, please guide me what can I do now?. thanks

**Comment by rachitralli** [comment]
@mcdurdin

**Comment by mcdurdin** [comment]
What was the error that you received? Have you followed the advice @LornaSIL provided?

**Comment by rachitralli** [comment]
@LornaSIL @Mcdurdin tried many times rebooting, uninstalled and then installed but both keyman dev and keyman desktop not working, I was working in kmn and kps files the keyman encountered a problem and showing the following error:-

Keyman encountered a problem

Pls check and help me. thanks

**Comment by mcdurdin** [comment]
So the error `Keyman encountered a problem` is difficult to diagnose. It's generic and could be mean about anything. Can you send us a diagnostic report following the steps at https://help.keyman.com/kb/40?

**Comment by rachitralli** [comment]
@darcywong00 after right clicking on note ++ I am able to edit the kpj, kmn and kps but unable to edit directly. There is no syntax error but both the Keyman Dev and Keyman Desktop are not working in Windows 8.1.

**Comment by rachitralli** [comment]
here is the screenshot

**Comment by rachitralli** [comment]
![image](https://user-images.githubusercontent.com/8731787/50199132-0618ff00-0371-11e9-8495-ca40ae7ca807.png)
@mcdurdin

**Comment by rachitralli** [comment]
![image](https://user-images.githubusercontent.com/8731787/50199442-a0c60d80-0372-11e9-867c-1da959d03ded.png)
@mcdurdin @darcywong00 @LornaSIL

**Comment by mcdurdin** [comment]
It looks like the files in the folder `c:\users\rehmat~1\appdata\roaming\keyman\keyman developer 10.0` may have been corrupted. You can access them by pressing Win+R, pasting `%appdata%\keyman\keyman developer 10.0`. Can you share the files Untitled.kps and Untitled.kps.user from that folder with us?

Then, if you delete them, Keyman Developer should start.

**Comment by rachitralli** [comment]
@mcdurdin thanks I have deleted the above files as suggested, the kmn file is working now but the kps file is not working 

![error reort](https://user-images.githubusercontent.com/8731787/50200677-b9d1bd00-0378-11e9-83f2-7a677126a47b.png)

**Comment by rachitralli** [comment]
Thanks @mcdurdin, after downloading the latest version 10.0.1206.0 this issues has been solved. Therefore I am closing this issue as Done.
