### ISSUE TITLE
Potential font corruption issue

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyboards#580]
Discovered during an initial run of https://github.com/keymanapp/keyman/pull/1432 across the cloud repo's keyboards.

Browser:  Chrome (v 70.0.3538.110)
Environment:  Windows 10

This error was logged within Development mode, emulating an iPhone X.

> Failed to decode downloaded font:  https://s.keyman.com/font/deploy/NotoSansSyriacEastern-Regular.ttf
> OTS parsing error: glyf: Failed to parse table

**Comment by darcywong00** [comment]
Same error on
https://keymanweb.com/#syc,Keyboard_syriac_phon

with Chrome. fwiw, the font loads fine in Firefox.

**Comment by DavidLRowe** [comment]
Where are you seeing the error? Using Chrome (71.0.3578.98) on Windows 10 (1803) with the https://keymanweb.com/#syc,Keyboard_syriac_phon link, I don't see any error message and can type the test text.

**Comment by darcywong00** [comment]
The appear in the "Console" tab of Chrome's Developer tools (Ctrl-Shift-I or F12)

**Comment by LornaSIL** [comment]
@darcywong00 @jahorton is this still a problem?

**Comment by darcywong00** [comment]
Hmm, I'm not seeing it on https://keymanweb.com/#syc-syrc,Keyboard_syriac_phonetic anymore
Windows 10
Chrome 83.0.4103.61

**Comment by jahorton** [comment]
I don't see it either.  I'll assume the root cause, whatever it was, has been fixed since this was posted.
