### ISSUE TITLE
How to use multi Characters in one button key?

### ISSUE THREAD

**Issue by saitawngpha** [keymanapp/keyboards#59]
Dear,

I have created a keyboard for touch screen. My problem is I want to use more than one characters words in one button key but I can not do it. 
In my language, we have to use multi characters for complete the one word such as, မ + ႂ် = မႂ် . The word of ႂ် is a separate character like this ႂ + ် = ႂ် . 
Can anyone tell me the way to use multi characters in one button? Please help and hope to hear from your respond soon.
Best Regards,
Sai Tawng Pha

**Comment by mcdurdin** [comment]
I'm not entirely sure I understand your request, but for example you could do what you are asking in the source of your keyboard with:
````
+ [K_W] > U+1082 U+103A   c ႂ်
````
Further information on keyboard rules is available in https://help.keyman.com/developer/language/  If I haven't understood you correctly, can you give a bit more detail in your query?

**Comment by saitawngpha** [comment]
Dear mcdurdin,

I have tried like  your mention but I still have the same problem. To make you clear what I want, please look at the photo below.

![problem](https://user-images.githubusercontent.com/9567660/28009258-c85f93de-6580-11e7-8eb6-02820cf4b431.png)

I want to combine two characters for output in one word. 

![problem2](https://user-images.githubusercontent.com/9567660/28009262-cc10cff2-6580-11e7-9067-eba4357218a8.png)

I have got the error message when I build the keyboard. Please help.

Best regards,
STP

**Comment by mcdurdin** [comment]
Okay, I understand what you are trying to do. In this situation, you need to use a rule in the "Layout" tab ("Code" view) to output more than one character from a single key.

I would rename the code from `U+1082 U+103A` to `T_1082_103A` and then add the following rule into the code view, within the `group(main)` section:
````
+ [T_1082_103A] > U+1082 U+103A
````

Have a read of https://help.keyman.com/developer/9.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty#toc-key-code for more details on how the key codes work in touch layouts.
