### ISSUE TITLE
[ekwbamuni] Tamil Character Missing

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#607]
@pc8181 reports:
> I am using Keyman 11.0 beta with Tamil Suratha Bamini Keyboard.
>
> but could not identified the charact 'JU' only available 'JII"
> 
> for ex can type
> " JULY " = ஜீலை
> but not = ஜூலை
>
> where can i type " ஜூ " in tamil suratha bamini keyboard ?
>
> help
>
> Thanks

**Comment by LornaSIL** [comment]
@marc U+0BC2 does not appear to be in the keyboard. This keyboard is copyright "thamizha.com and Tavultesoft". The keyboard is already under MIT according to the keyboard page. Does this mean we can move this keyboard from legacy to release and enhance the keyboard? Or do we need to get with the author for permission? The domain still seems to be working so we might be able to talk to the author.

**Comment by LornaSIL** [comment]
@pc8181 After a very long wait I moved the bamini keyboard to our "release" version. The new keyboard is here: https://keyman.com/keyboards/thamizha_bamini

The keys to produce ஜூ is `[--`. I hope this works for you.
