### ISSUE TITLE
Keyman stops working when switching between languages using 'Arrow key' and then 'enter'

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#62]
The popup message read, "Unfortunately, Keyman has stopped."

**Comment by mcdurdin** [comment]
Moved to keymanapp/keyman#362 as this is a Keyman bug not a keyboard-specific bug

**Comment by darcywong00** [comment]
@MakaraSok can you provide more details on how to replicate the crash?

On 10.0.10000016 alpha, I'm able to use the arrow keys to change language both in-app and as system keyboard.
