### ISSUE TITLE
Lazuri mobile keyboard cannot be downloaded

### ISSUE THREAD

**Issue by rlqmadkqk** [keymanapp/keyboards#643]
I tested both on Android and apple and keyboard didn’t work.

On iphone I got an error message like below.
 
![keyman](https://user-images.githubusercontent.com/24529517/54219339-60ed6d00-4500-11e9-9331-c28ccb7a2675.jpg)

**Comment by DavidLRowe** [comment]
The developers are looking into the problem. It seems that there are other keyboards affected as well.

**Comment by DavidLRowe** [comment]
@rlqmadkqk Can you test it now to verify that it is working?

If it's working you can close this issue. If you're still having problems, please let us know that.
