### ISSUE TITLE
Definition of K_EQUAL does not work in KeymanWeb

### ISSUE THREAD

**Issue by rimas-kudelis** [keymanapp/keyboards#653]
While testing #652, I noticed that the definitions of `KP_EQUAL` in that file are ignored. I checked with https://keymanweb.com/#lt,Keyboard_lithuanian, and the same problem is reproducible there.
For the reference, I'm using Firefox on Linux.

**Comment by mcdurdin** [comment]
I'm curious why you closed this issue?

**Comment by jahorton** [comment]
Probably related to the diagnosis on https://github.com/keymanapp/keyman/issues/1694?

**Comment by rimas-kudelis** [comment]
Yeah, i figured this wasn't the right repository to file this issue.

Rimas
