### ISSUE TITLE
Lazuri Mobile keyboard name.

### ISSUE THREAD

**Issue by rlqmadkqk** [keymanapp/keyboards#675]
Lazuri keyboard was updated recently in order to change the keyboard name for mobile.

![02badb9e-710d-461b-9a10-3a6b393da432](https://user-images.githubusercontent.com/24529517/56498001-95454780-6508-11e9-846b-7755cd206aad.jpg)

As you can see the picture above, "Laz (Latin)" is shown on mobile keyboards.
How can I change that into "Laz" only? 

Thank you for your services.

**Comment by LornaSIL** [comment]
@mcdurdin where do we change this? We've been several rounds with this keyboard and it is still not displaying the name they want displayed.
Right now the .kps file has ```<Language ID="lzz-Latn">Lazuri</Language>```
And on Keyman on my android I'm seeing 
```Laz (Latin)```
```Lazca Klavye```

Where is it getting the language name with script?

**Comment by mcdurdin** [comment]
At present, the language name cannot be changed by the keyboard; that comes from the BCP 47 registry and SIL's alltags.json data. However, the infrastructure is there for us to be able to search on and show the language name in a future version of Keyman; a revamp of language searching is planned for 13.0 (see [roadmap](https://blog.keyman.com/2019/02/keyman-roadmap-february-2019/))
