### ISSUE TITLE
Keyboard_chinese (bcp47: cmn) fails to show Chinese IME suggestions

### ISSUE THREAD

**Issue by jacobbowdoin** [keymanapp/keyboards#682]
On both my local implementation of KeymanWeb 11.0.224 and online at https://keymanweb.com/?_ga=2.164907647.11266167.1555962656-1596750058.1549995025#cmn,Keyboard_chinese, the Chinese character suggestions don’t show up. Instead on each keystroke an error is logged:

Uncaught TypeError: KeymanWeb.ShowPinnedHelp is not a function
at Keyboard_chinese.show (chinese-1.0.js:formatted:136)
at Keyboard_chinese.showCandidates (chinese-1.0.js:formatted:309)

Interestingly when I press PgDn or PgUp, the suggestions show up. I could hack a workaround which adds a PgUp keystroke after the user’s every character, but was wondering if this bug is just a typo or result of a breaking change over the years?

**Comment by mcdurdin** [comment]
See https://github.com/keymanapp/keyman/issues/1742 and https://github.com/keymanapp/keyman/issues/1754
