### ISSUE TITLE
Modify BCP47 codes for fv keyboards: list mismatch

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#695]
List mismatch: fv_anishinaabemowin
List mismatch: fv_cree_latin
List mismatch: fv_dine_bizaad
List mismatch: fv_hlgaagilda_xaayda_kil
List mismatch: fv_maori
List mismatch: fv_shashishalhem
List mismatch: fv_statimcets
List mismatch: fv_xaislakala

**Comment by LornaSIL** [comment]
#713

**Comment by DavidLRowe** [comment]
Fixed by #713
