### ISSUE TITLE
fv_australian keyboard listed under English rather than Yolngu

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#754]
The fv_australian keyboard appears to be missing the correct bcp47 association; it should include Yolngu at least and probably not be listed under English.

**Comment by LornaSIL** [comment]
Dhangu-Djangu (Yolngu-Matha) - dhg or 
Dhuwal (Yolngu) - dwu
or both?

Help file says: "This keyboard is designed for the Australian language of the Pacific region of Canada. " I assume that is wrong?

**Comment by mcdurdin** [comment]
> This keyboard is designed for the Australian language of the Pacific region of Canada.

Ah, yes. I guess the automated tool got confused with all the British place names, Victoria, Sidney, etc etc ;-)

**Comment by mcdurdin** [comment]
In terms of languages to list under, I am not sure -- would need to ask the FV team? Probably both...

**Comment by LornaSIL** [comment]
If you can find out, or tell me who to ask, I can do the work on updating it.

**Comment by LornaSIL** [comment]
Fixed by #760
