### ISSUE TITLE
[sil_myanmar_mywinext] "store(sil_myanmar_mywinext.ico)" is meaningless

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#911]
The line `store(sil_myanmar_mywinext.ico)` does nothing except create an empty store called "sil_myanmay_mywinext.ico"; the keyboard still references a .bmp and not an .ico for the `store(&BITMAP) 'sil_myanmar_mywinext.bmp'` line.

**Comment by DavidLRowe** [comment]
Agreed that that line is useless. But it's not doing any harm, is it? It doesn't seem worth changing the .kmn file, which would then mean incrementing the version number in several places and changing the copyright date in several more places!

What if I add a "TO DO" section to the README.md file that indicates that that line should be deleted? Then anyone who does more work on this keyboard will be alerted to this change.

**Comment by mcdurdin** [comment]
Yes that sounds good to me -- the main reason I noted this was that it might mislead maintenance developers or others who use this keyboard as a model for their own keyboards.
