### ISSUE TITLE
[Infrastructure] Keyboards build still uses old language tag database

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#917]
Keyboards build references to alltags needs to be updated to use https://ldml.api.sil.org?query=langtags&ext=json

**Comment by LornaSIL** [comment]
@mcdurdin is this still true or have you updated to use langtags?

**Comment by mcdurdin** [comment]
This hasn't been resolved yet

**Comment by mcdurdin** [comment]
Duplicate of keymanapp/api.keyman.com#44.
