### ISSUE TITLE
[sil_cipher_music] Things to check on keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#947]
Some of these items stem from the [community site](https://community.software.sil.org/t/cant-install-cipher-music-on-ios-13-and-some-input-does-not-work/2757) where a user originally reported not being able to install the keyboard on iOS 13.

- [ ] He was able to install on iOS 11, but wasn't able to input some sequences:
>Both in my iPhone and my Mac, I just can input the following, from 1-8
double for dot over number: 1̇,
triple for dot under number 1̣, it works very well.
>
>But cannot have underline under the numebr,
double ‘-’ can put ‘-’ above the letter: 1̅,
but triple ‘-’ only put one more ‘-’ after: 1̅-
>
>Also I cannot add underdot under an underline, overdot after an underline, single barline, slur… all cannot input. I am using Mac OS Catalina.

- [ ] User also requests to separate Cipher Music keyboard into two, one for Indonesia Cipher, one is Chinese Juian Pu. (Desktop option to toggle not available on Mac/Linux?)

-------

- [ ] @mcdurdin recommends
> using only Shift, RAlt, and RAlt+Shift modifiers for desktop-style keyboards.

---------
The keyboard support for mobile may be incomplete. I can download the keyboard from Keyman for Android 12.0.4206, but I can't access the RCtrl or Shift-RCtrl layers.
- [ ] .kmn targets windows, macosx, linux, web; but the generated .keyboard_info says full support for all platforms
- [ ] There a .keyman-touch-layout file - Does it need to be added to .kmn?
- [ ] The DoulosSILCipher-R.ttf font is included in the package. Does it need to be applied to the "Keyboard font" and "Display font" so mobile will use it?

---------

- [ ] In the  Keyman for Android language picker, the keyboard appears at the very bottom of the alphabetical list
> in
Cipher Music (SIL)

Should the language tag be `id` instead of `in`? That's what basic_kbdus uses.

**Comment by LornaSIL** [comment]
> Should the language tag be id instead of in? That's what basic_kbdus uses.

Yes, ```id``` seems to be the preference in the IANA subtag registry altho ```in``` should have worked.

>User also requests to separate Cipher Music keyboard into two, one for Indonesia Cipher, one is Chinese Juian Pu. (Desktop option to toggle not available on Mac/Linux?)

I don't want to split the keyboard, so I'm adding the ability to use a toggle key for mac/linux.

>There a .keyman-touch-layout file - Does it need to be added to .kmn?

I don't really want to support a mobile keyboard yet (and the one there is not correct) so I'll delete the .keyman-touch-layout file

I'm changing the CTRL keys to RALT.

**Comment by LornaSIL** [comment]
Fixed by #957
