### ISSUE TITLE
[meta] Investigate blank <Languages /> in .kps files

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#979]
From review of #959 

release/packages/gff_amh_powerpack_7/source/gff_amh_powerpack_7.kps
Is a very old package that doesn't have associated languages for
```
      <Name>Ethiopic - (Language Neutral)</Name>
      <ID>gff_ethiopic_7</ID>
      <Version>1.0</Version>
      <Languages/>
```

Per @mcdurdin 
> We should probably document the language metadata gaps in these .kps files on the keyboards repo... to investigate. [Ethiopic packages] are kinda old so that's why they don't have the language data yet.

**Comment by DavidLRowe** [comment]
What is the status of this issue? The current release/gff/gff_ethiopic_7/gff_ethiopic_7.keyboard_info file has 
```
    "languages": {
        "gez": {}
    }
```
Does that mean this issue can be closed?

**Comment by darcywong00** [comment]
The issue is in the .kps XML file where `<Languages/>` isn't specifying a language for the package.

Compare to the release/gff/gff_amharic/source/gff_amharic.kps file
```
      <Name>አማርኛ (Amharic)</Name>
      <ID>gff_amharic</ID>
      <Version>1.9.2</Version>
      <OSKFont>..\..\..\shared\fonts\sil\abyssinica\AbyssinicaSIL-Regular.ttf</OSKFont>
      <DisplayFont>..\..\..\shared\fonts\sil\abyssinica\AbyssinicaSIL-Regular.ttf</DisplayFont>
      <Languages>
        <Language ID="am">Amharic</Language>
      </Languages>
```

**Comment by darcywong00** [comment]
Maybe it's fine for keyboard packages that only contain .kmx desktop keyboards?

**Comment by mcdurdin** [comment]
> Maybe it's fine for keyboard packages that only contain .kmx desktop keyboards?

For old desktop-only keyboards, where the .kmn includes a language code, we don't need the data in the .kps.

I'd say we can go ahead and close this.
